# Generated automatically from Makefile.in by configure.
 srcdir = .
  VPATH = .
  SHELL = /bin/sh
SUBDIRS = Wc Xp

all:
	@for i in $(SUBDIRS) ; do \
		echo Making $@ in ./$${i} ... ; \
		( cd $$i ; $(MAKE) $(MFLAGS) $@ ) ; \
	done

ALLDIR = Wc Xmp Xp Xop

clean mostlyclean realclean:
	@for i in $(ALLDIR) ; do \
		echo Making $@ in ./$${i} ... ; \
		( cd $$i ; $(MAKE) $(MFLAGS) $@ ) ; \
	done

