PROGRAMS=arrow arrow_timer drawn multi_click pixmaps pushb xcal radio_box simple_radio toggle toggle_box

CFLAGS=
INCLUDES = -I/usr/Motif12/include -I/usr/X11R6/include
LIBS= -L/usr/Motif12/lib -L/usr/X11R6/lib -lXm -lXt -lSM -lICE -lX11

all: $(PROGRAMS) 

.c: ; $(CC) $(CFLAGS) $(INCLUDES) $@.c $(LIBS) -o $@
