/*  -------------------------------------------------------------------

This program is the property of:

                             Cornell University 
                        Center for Applied Mathematics 
                              Ithaca, NY 14853

and may be used, modified and distributed freely, subject to the 
following restrictions:

       Any product which incorporates source code from the dstool
       program or utilities, in whole or in part, is distributed
       with a copy of that source code, including this notice. You
       must give the recipients all the rights that you have with
       respect to the use of this software. Modifications of the
       software must carry prominent notices stating who changed
       the files and the date of any change.

DsTool is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of FITNESS 
FOR A PARTICULAR PURPOSE.  The software is provided as is without 
any obligation on the part of Cornell faculty, staff or students to 
assist in its use, correction, modification or enhancement.

  -----------------------------------------------------------------  */
#ifndef	tclwin_HEADER
#define	tclwin_HEADER

/*
 * tclwin_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `tclwin.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	pan;
	Xv_opaque	directory;
	Xv_opaque	filename;
	Xv_opaque	option;
	Xv_opaque	load;
} tclwin_win_objects;

extern tclwin_win_objects	*tclwin_win_objects_initialize();

extern Xv_opaque	tclwin_win_win_create();
extern Xv_opaque	tclwin_win_pan_create();
extern Xv_opaque	tclwin_win_directory_create();
extern Xv_opaque	tclwin_win_filename_create();
extern Xv_opaque	tclwin_win_option_create();
extern Xv_opaque	tclwin_win_load_create();
#endif
