.TH hz2ps 1 "10 October 1993"
.SH NAME
hz2ps (version 3.1) \- convert a hanzi (GB/BIG5) file to PostScript
.SH SYNTAX
.B hz2ps
[
.I options
] [
.I file
]
.SH DESCRIPTION
The
.PN hz2ps
program converts a GB or BIG5 hanzi file to PostScript.  
It supports both horizontal and vertical printing mode with
or without page numbering.
All or parts of the file can be selected for conversion.
Other printing options and fonts can also be chosen.
.PP
The possible options are
.IP \-gb
use GB encoding. This is the default.
.IP \-big
use BIG5 encoding.
.IP \-h
horizontal printing mode. This is the default.
.IP \-v
vertical printing mode.
.TP 5
.BI \-margin "\ left \ right \ bottom \ top"
margins measured in inches from lower left corner of a page.
Default is \-margin 1 7.5 1 10.
.TP 5
.BI \-ls \ line-spacing
line height (width) in horizontal (vertical) printing mode,
measured in points (1 in = 72 points).
Default is \-ls 15.
.TP 5
.BI \-htab \ n
number of hanzi between two adjacent tabs.
Default is 4.
.TP 5
.BI \-hf "\ hanzi-font \ point-size \ inter-hanzi-spacing"
measure in points. Default is \-hf ccs24.hbf 10 1.
.TP 5
.BI \-af "\ ascii-font \ point-size \ width \ descender"
Default is \-af Courier 10 6 2.
.TP 5
.BI \-pf \ page-number
first page to be printed.
.TP 5
.BI \-pl \ page-number
last page to be printed.
.TP 5
.BI \-pnp "\ left \ bottom"
positions to print page number, 
measured in inches from the lower left corner of a page.
Default is \-pnp 4.15 0.5.
.TP 5
.BI \-pnoffset \ number
offset to be added to get the printed page numbers.
Default is 0.
This is useful if you want contiguous page numbering 
when a document is stored in several files.
.TP 5
.BI \-nopn
no page number to be printed.
.PP
If the environment variable HBFPATH is set,
(e.g. setenv HBFPATH "~/hanzi/hbf:/usr/local/hanzi/fonts/hbf"),
hzview will search for the HBF (header) file under each directory 
in the path list HBFPATH in order.
Otherwise, the current directory is the default directory.
.SH COPYRIGHT
Copyright (C) 1989-1993  Fung F. Lee
.sp
All rights reserved.
Permission to copy and distribute verbatim copies of the source code
and accompanied documents for non-commercial purposes is granted,
but changing them is not allowed.
There is absolutely no warranty for this program.
.SH AUTHOR
Fung F. Lee
.SH BUGS
Bug reports and comments should be sent to lee@csl.stanford.edu.




