.\" Copyright 1994 NEC Corporation, Tokyo, Japan.
.\"
.\" Permission to use, copy, modify, distribute and sell this software
.\" and its documentation for any purpose is hereby granted without
.\" fee, provided that the above copyright notice appear in all copies
.\" and that both that copyright notice and this permission notice
.\" appear in supporting documentation, and that the name of NEC
.\" Corporation not be used in advertising or publicity pertaining to
.\" distribution of the software without specific, written prior
.\" permission.  NEC Corporation makes no representations about the
.\" suitability of this software for any purpose.  It is provided "as
.\" is" without express or implied warranty.
.\"
.\" NEC CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN 
.\" NO EVENT SHALL NEC CORPORATION BE LIABLE FOR ANY SPECIAL, INDIRECT OR
.\" CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF 
.\" USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR 
.\" OTHER TORTUOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR 
.\" PERFORMANCE OF THIS SOFTWARE. 
.\"
.\" $Id: RkGoto.man,v 2.1 1994/04/21 00:46:41 kuma Exp $ NEC;
.TH "RKGOTO" "3"
.SH "NAME"
\f4RkGoTo\f1 \- change the current clause
.SH "SYNOPSIS"
.nf
.ft 4
#include <canna/RK.h>
int RkGoTo(cxnum, bnum)
int cxnum;
int bnum;
.ft 1
.fi
.SH "DESCRIPTION"
\f2RkGoTo\f1 sets the clause with the specified clause number \f2bnum\f1 as the current clause.  The clause number must be 0 or greater but less than the last clause number.  The current clause does not change when a clause number outside this range is specified.
.SH "RETURN VALUE"
If successful, this function moves the current clause in the context and returns the current clause number after the move.  It returns \f40\f1, without doing anything, if it has been run in a nonconversion mode context.
