.\" Copyright 1994 NEC Corporation, Tokyo, Japan.
.\"
.\" Permission to use, copy, modify, distribute and sell this software
.\" and its documentation for any purpose is hereby granted without
.\" fee, provided that the above copyright notice appear in all copies
.\" and that both that copyright notice and this permission notice
.\" appear in supporting documentation, and that the name of NEC
.\" Corporation not be used in advertising or publicity pertaining to
.\" distribution of the software without specific, written prior
.\" permission.  NEC Corporation makes no representations about the
.\" suitability of this software for any purpose.  It is provided "as
.\" is" without express or implied warranty.
.\"
.\" NEC CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN 
.\" NO EVENT SHALL NEC CORPORATION BE LIABLE FOR ANY SPECIAL, INDIRECT OR
.\" CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF 
.\" USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR 
.\" OTHER TORTUOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR 
.\" PERFORMANCE OF THIS SOFTWARE. 
.\"
.\" $Id: RkMountD.man,v 2.1 1994/04/21 00:46:56 kuma Exp $ NEC;
.TH "RKMOUNTDIC" "3"
.SH "NAME"
\f4RkMountDic\f1 \- mount a dictionary in the dictionary list
.SH "SYNOPSIS"
.nf
.ft 4
#include <canna/RK.h>
int RkMountDic(cxnum, dicname, mode)
int cxnum;
char *dicname;
int mode;
.ft 1
.fi
.SH "DESCRIPTION"
\f2RkMountDic\f1 mounts a dictionary in the dictionary list.  The dictionary name is got with \f2RkGetDicList(3)\f1.  \f2RkMountDic\f1 appends the named dictionary to the dictionary list.  The dictionary thus mounted can be used from the next run of kana-kanji conversion.  \f2mode\f1 is meaningless at this moment.
.P
The dictionary to be mounted must not have already been mounted in the present context.
.SH "RETURN VALUE"
This function returns \f40\f1 if successful; otherwise, it returns \f4-1\f1.  
.SH "SEE ALSO"
.na
\f4RkUnmountDic\f1(3)
.ad
