#ifndef	rasview_HEADER
#define	rasview_HEADER

/*
 * rasview_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `rasview.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;

extern Xv_opaque	rasview_file_menu_create();

typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls;
	Xv_opaque	file_button;
	Xv_opaque	drop_target1;
	Xv_opaque	canvas;
} rasview_win_objects;

extern rasview_win_objects	*rasview_win_objects_initialize();

extern Xv_opaque	rasview_win_win_create();
extern Xv_opaque	rasview_win_controls_create();
extern Xv_opaque	rasview_win_file_button_create();
extern Xv_opaque	rasview_win_drop_target1_create();
extern Xv_opaque	rasview_win_canvas_create();
#endif
