.TH ASET 1 "Release 1"  "AF Version 3"
.SH NAME
axset - AF control panel
.SH SYNOPSIS
.B axset
.SH DESCRIPTION
This program is an X based control panel for an AF server.

This program is implemented with the Tcl/Tk toolkit, which must be installed 
on your system for the program to run.
.SH RESTRICTIONS
Doesn't display AF events.

.SH ENVIRONMENT
.TP 8
.B AUDIOFILE
to get the default host and server to use.
.SH BUGS
If you encounter a \fBreproducible\fP bug, please 
submit a problem report to (af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1)
.SH COPYRIGHT
Copyright 1992-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHOR
Andrew Payne, Digital Cambridge Research Lab
