PROGRAMS=showuid trivial.uid kids.uid resource.uid cb.uid first.uid second.uid multiline.uid joel.uid bomb.uid globe.uid simple_lst.uid station.uid

CFLAGS=
INCLUDES = -I/usr/Motif12/include -I/usr/X11R6/include
LIBS= -L/usr/Motif12/lib -L/usr/X11R6/lib -lMrm -lXm -lXt -lSM -lICE -lX11

.SUFFIXES : .uil .uid

all: $(PROGRAMS)

.c: ; $(CC) $(CFLAGS) $(INCLUDES) $@.c $(LIBS) -o $@

.uil.uid: ; uil -o $@ $<
