.TH XVSET 1 "15 July 1994"
.SH NAME
xvset \- Open Look interface for xset(1)
.SH SYNOPSIS
.B xvset
[
.B \-v
]
[
.I generic-tool-arguments
]
.SH DESCRIPTION
.B xvset
provides a graphical interface for some of the functions of
.BR xset (1),
allowing the user to alter settings for the mouse, bell, and screen saver.  Its features are more fully documented via the XView help facility.
.SH OPTIONS
.TP
.B -v
Display version number.
.TP
.I generic-tool-arguments
.B xvset
accepts the generic tool arguments listed in
.BR xview (7).
.SH SEE ALSO
.BR xset (1)
.BR xview (7)
.SH BUGS
.LP
.B xvset
is at an early stage of development.
.LP
.B xvset
does not support several options supported by
.BR xset (1),
so it cannot be considered a complete replacement.
.LP
The code incorporates no error-handling routines.
.SH AUTHOR
Copyright (C) Brian L. Brush <brush@acomp.usf.edu>, 223 S. Riverhills Dr., Tampa, FL 33617-7240, USA.
