# Makefile for fractool

CC =		cc
CFLAGS =	-I/usr/openwin/include
LIBS =		-lXView -lolgx -lX11 -lm

OBJS =	 	fractool.o init.o notify.o math.o utils.o ruledef.o \
		allocate.o io.o automatic.o
fractool:	$(OBJS)
		$(CC) -o fractool $(OBJS) ${LIBS}

clean:
		rm -f fractool *.o *.BAK
