.TH INSTALL_DSUSER 1 "9 September 1992"
.SH NAME
install_dsuser \- install a user configuration for dstool, a 
dynamical systems analysis and exploration toolkit 
.SH SYNOPSIS
.B install_dsuser
.SH USAGE
The 
.B install_dsuser 
script prompts the user for a 
.I destination directory 
and delivers 
to that directory all files required for a personal 
.I user dstool configuration. 
If necessary, it creates the 
.I destination directory
as well as subdirectories 
.I models
and
.I userlib.
The 
.I models
subdirectory contains a file 
.I README.models
describing the procedure for entering new models into 
dstool.

The 
.B install_dsuser 
script uses the environment variable: 
.RS

.B DSTOOL
\- location of the main dstool distribution, 
for example /usr/local/dstool.
.SH AUTHORS
M. R. Myers, A. Back

Center for Applied Mathematics, Cornell University

Ithaca, New York 14853
.SH FILES
$DSTOOL/bin/install_dsuser
.SH SEE ALSO
.B dstool(1)

.B dstool Installation Manual
.SH BUGS
Pathnames must be fully specified without the use of environment
variables or other csh shorthand.

Please report bugs as well as other comments related to
dstool to 
.I dstool_bugs@macomb.tn.cornell.edu.
