= The OPEN LOOK and XView CD-ROM (Archived)

Lifetimes ago, I wrote a book for O'Reilly Media called
_X Windows User Guide: The OPEN LOOK Edition_.
For those unfamiliar with the history, there were three implementations
of the OPEN LOOK specification:

. NeWS, the Network Extensible Window System, originated by James Gosling
at Sun, who later invented the Java language;
. OLIT, the OPEN LOOK Intrinsics Toolkit, based on the Unix X Toolkit;
. XView, by Sun Microsystems, based on the programing paradigm of 
their earlier SunView toolkit.

Of these three, to my knowledge only XView was ever released
in source form, certainly so at the time.
Gosling once told me that NeWS had too many components from too
many other software vendors for them ever to open source it.

Unfortunately, at the time I completed writing this book,
Sun Microsystems pulled the plug on OPEN LOOK,
caving to Motif and effectively ending the "Unix UI Wars"
in return for getting a bunch of their stuff included into the
Common Desktop Environment (CDE).

In the aftermath of O'Reilly's decision not to publish the book,
I made it available on CD-ROM, and sold it through Amazon,
making me one of the few hundred earliest Amazon sellers 
other than major publishers.
In all we sold a few hundred copies over several years.
At this time, it seemed that Bruce Tognozzini's wish that OPEN LOOK
"be towed out to sea and given a decent burial" had come true,
and so I abandoned sales and put the CD-ROM up for FTP download.

You can read the README-orig.txt[original README file here].

After several changes of server and server software, this
arrangement fell apart.
So now I am putting what's left of it up on GitHub
for anyone to pick over the remains. This was created by reading
from one of my last remaining copies of the CD.

== Caveat Lector: Some files are missing.

First, I've removed all binary programs, since what worked on 
Linux or Solaris in the mid-1990's just isn't going to be useful today.
Second, some files simply weren't able to be copied from the last
copy of the CD-ROM that I could find.

----
dalai--asciidoctor $ cp -r /mnt ~/olcd
cp: readlink: /mnt/book/vol3ol/psrun: Invalid argument
cp: readlink: /mnt/book/vol3ol/psrun.awk: Invalid argument
cp: readlink: /mnt/book/vol7b/psrun: Invalid argument
cp: readlink: /mnt/book/vol7b/psrun.awk: Invalid argument
cp: readlink: /mnt/NeWS/news-tape/applications/newsline/pguide: Invalid argument
cp: readlink: /mnt/src/book-examples/ora-vol1xlib: Invalid argument
cp: readlink: /mnt/src/book-examples/ora-vol4athena: Invalid argument
cp: readlink: /mnt/src/book-examples/ora-vol4motif: Invalid argument
cp: readlink: /mnt/src/book-examples/ora-vol6motif: Invalid argument
cp: readlink: /mnt/src/motif/psview/alpha-osf1/cursor.h: Invalid argument
cp: readlink: /mnt/src/motif/psview/alpha-osf1/dps.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/alpha-osf1/gs.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/alpha-osf1/psview.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/alpha-osf1/psview.h: Invalid argument
cp: readlink: /mnt/src/motif/psview/alpha-osf1/version.h: Invalid argument
cp: readlink: /mnt/src/motif/psview/alpha-osf1/xpsview.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/mips-ultrix/cursor.h: Invalid argument
cp: readlink: /mnt/src/motif/psview/mips-ultrix/dps.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/mips-ultrix/gs.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/mips-ultrix/psview.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/mips-ultrix/psview.h: Invalid argument
cp: readlink: /mnt/src/motif/psview/mips-ultrix/version.h: Invalid argument
cp: readlink: /mnt/src/motif/psview/mips-ultrix/xpsview.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/sol2/cursor.h: Invalid argument
cp: readlink: /mnt/src/motif/psview/sol2/dps.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/sol2/gs.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/sol2/psview.c: Invalid argument
cp: readlink: /mnt/src/motif/psview/sol2/psview.h: Invalid argument
cp: readlink: /mnt/src/motif/psview/sol2/version.h: Invalid argument
cp: readlink: /mnt/src/motif/psview/sol2/xpsview.c: Invalid argument
cp: readlink: /mnt/src/NeWS: Invalid argument
cp: readlink: /mnt/src/window-managers/olwm: Invalid argument
cp: readlink: /mnt/src/window-managers/olwmslave: Invalid argument
----

If you can find any of the missing files, well, this is GitHub,
so clone the repo and send a pull request.
Or, for individual files, you could just email them to me.
