= The OPEN LOOK and XView CD-ROM (Archived)

Lifetimes ago, I wrote a book for O'Reilly Media called
_X Windows User Guide, Volume 3: OPEN LOOK Edition_.
For those unfamiliar with the history, OPEN LOOK was a very good
UI specification, of which there were three different implementations:

. NeWS, the Network Extensible Window System (an entire window system
written in PostScript), originated by James Gosling
at Sun (same James Gosling who later invented the Java language);
. OLIT, AT&T's OPEN LOOK Intrinsics Toolkit, based on the Unix Xt Toolkit;
. XView, by Sun Microsystems, using XLib and based on the programing paradigm
of their earlier SunView toolkit.

Of these three, to my knowledge only XView was ever released
in source form, certainly so at the time.
Gosling once told me that NeWS had too many components from too
many other software vendors for them ever to open source it.

Unfortunately, at the time I completed writing this book,
Sun Microsystems pulled the plug on OPEN LOOK,
caving to Motif and effectively ending the "Unix UI Wars"
in return for getting a bunch of their stuff included into the
Common Desktop Environment (CDE).

In the aftermath of O'Reilly's decision not to publish the book,
I made it available on CD-ROM. 
You can read the original README file from the CD-ROM in the file
README-orig.txt in this directory.

We mostly sold the CD-ROM through Amazon,
making me one of the few hundred earliest Amazon sellers 
other than major publishers.
In all we sold a few hundred copies over several years.
At this time, it seemed that Bruce Tognozzini's (of _Tog on Interface_ fame)
wish that OPEN LOOK "be towed out to sea and given a decent burial" 
had come true, and so I abandoned sales and put the CD-ROM up 
for FTP download as an ISO image.

After several changes of server and server software, this
arrangement fell apart.
So now I am putting what's left of it up on GitHub
for anyone to pick over the remains. This was created by reading
an early CVS archive I made at the time, merged with some additional
files in a file I found on my hard drive called "olcd.tar" and
a few from one of my last remaining copies of the CD.
That's why some of the GIT log dates are from 2001 and some from 2016.

== Caveat Lector: Some files are missing.

First, I've removed all binary programs and libs, since what worked on 
Linux or Solaris in the mid-1990's just isn't going to be useful today.
Ditto for the search index, which had been built for a proprietary
indexing program.
Second, this repository is cobbled together from sources as
described above, so there is no guarantee that it
is exactly the same as what was on the CD.
As well, there were a few minor revisions to the CD as we found
minor glitches, so there isn't even a single set of "what was on the CD".

If you find any of the missing files, well, this is GitHub,
so clone the repo and send a pull request.
Or, for individual files, you could just email them to me.
