#!/bin/sh

# TOUR -- start the HTML tour

echo "This starts the Web tour of the OPEN LOOK, XView and NeWS Archive."

# set CDROMBASE to cwd plus a slash, used for clever hack to let
# install scripts work from TOUR and also if started locally.
CDROMBASE=`pwd`/; export CDROMBASE
echo "Setting CDROMBASE to ${CDROMBASE} for use in scripts."
echo ""
echo "We assume you have a Web browser at your disposal. In case you don't,"
echo "we provide binaries of the World Wide Web Consortium's Arena 0.9x beta"
echo "browswer for SunOS and Linux (requires libX11.so.6). Alternately,"
echo "you can FTP a viewer from ftp.ncsa.uiuc.edu or ftp.mcom.com, or many"
echo "mirror sites. Or get a new Arena viewer at http:///www.w3.org/pub/arena/."
echo "Which browser do you want to use? [mosaic]"
read browser
case "$browser" in
	[aA]rena*) if [ -x /bin/sun ] && sun; then
		echo "Use Arena with static hosts[s] or Resolver[r]?";
		read ans junk;
		case "$ans" in 
		s|S) browser=arena-noresolv;;
		r|R) browser=arena-resolver;;
		*)	echo "I don't understand $ans, using arena"
			browser=arena;;
		esac
		else browser=arena;
		fi;;
	"")	browser=mosaic;;
	# anything else - don't touch!
esac

# Some systems map names to lower case(!)
if [ ! -f TOUR -a ! -f tour ]; then
	echo "You do not appear to be in the root of the CD-ROM."
	echo "Please change directory to the top-level directory"
	echo "of the XVIEW and OPEN LOOK CD-ROM, and try again. Thank you."
	exit 1
fi

# We tell WWW lib to add our mailcap stuff.
echo "Add our MailCap stuff (support for various helper applications)? [yn] "
read ans junk
case "$ans" in
	y*|Y*|ok|OK) MAILCAPS=${CDROMBASE}WebHelpers/mailcap; export MAILCAPS;;
esac

if [ -x /bin/sun ] && sun; then
	PATH=`pwd`/bin.sun:$PATH; export PATH
elif [ -f /vmlinux ]
then
	PATH=`pwd`/bin.linux:$PATH; export PATH
else
	echo "Not Sun or Linux, assuming you have the browser in your PATH..."
fi

echo "OK, launching a browser, or trying to..."

set -x

exec $browser file://localhost`pwd`/index.html
