############################################
# dstool - modellib  makefile              #
############################################

include ${DSTOOL}/site_specific/lib_incl.mk
############################################
# Modify the following segment only.       #
############################################
LIBRARY = userlib.a 

SOURCES_A = \
	user_panels.c \
	example.c \
	mult_proj.c

DEPS_A = \
	$(DSTOOL)/src/include/mult_proj.h \
	$(DSTOOL)/src/include/pm.h \
	$(DSTOOL)/src/windows/user_panels.h

SOURCES_B = 

DEPS_B = 

TEST_PROGRAM = 

TEST_SOURCES = 

TEST_DEPS =

##############################################
# The following line should not be modified  #
##############################################

include ${DSTOOL}/site_specific/win_targetsA.mk

