.\" @(#) pizzatool.6 1.1 91/03/08 SMI;
.ds Ne \s-2Ne\h'-0.2n'WS\s+2
.TH PIZZATOOL 6 "8 March 1991" "OpenWindows 3.0"
.IX "pizzatool" "" "\fLpizzatool\fP \(em a graphical pizza menu user interface"
.SH NAME
pizzatool \- a graphical pizza menu user interface
.SH SYNOPSIS
.B /usr/openwin/demo/pizzatool
.SH DESCRIPTION
.I PizzaTool
is a \*(Ne and tnt application that lets you select a pizza by
choosing toppings from checkboxes and menus, and preview a drawing of 
your pizza in a round spinning window.

The main PizzaTool window has some buttons, menus, and text fields that you 
can use to configure your order. The "Pizza Parlor" menu selects between
various pizza servers. The "Topping..." "Preview..." and "Edit..." buttons 
pop up associated control panels. The "Order!" button sends your order to 
the pizza server. You need to fill in your name and address so they know 
who you are and where to deliver your pizza. 

The Topping panel has a "Preview..." button that pops up the pizza
preview panel, and an "Order!" button to send your order, like the
main PizzaTool window. There are settings to select how big a pizza
you want, and to choose a whole or a half pizza. There is an
abbreviated menu button for selecting popular pizza styles, and lots
and lots of checkboxes, for selecting individual toppings. The field
at the bottom of the panel displays the estimated cost of the
currently selected pizza.

Popping up the pizza Preview panel paints a picture of the particular pizza 
you've picked. The round pizza is magically suspended in the hollow frame 
(it's supposed to be that way), and you can resize the frame to get a closer 
look at the pizza. Pressing the
.I MENU
button over the pizza pops up a menu of popular pizza styles, and you can 
spin the pizza around with the
.I SELECT
button, to cook it. 

The Pizza Menu Editor panel is for use by authorized pizza parlor personell
only. It can be used to add, delete, rename, and edit pizza styles, and to
change all the prices. 

.SH SEE ALSO
.I The \*(Ne Toolkit Reference Manual
.LP
.I \*(Ne 2.1 Programmer's Guide
.LP
.I OPEN LOOK Graphical User Interface
.I Functional Specification
.SH NOTES
.I \*(Ne
is a registered trademark of Sun Microsystems, Inc.
.LP
.I OPEN LOOK
is a trademark of AT&T.
.SH BUGS
There is presently no way to pay off your tab.
