.TH apower 1 "Release 1"  "AF Version 3"
.SH NAME
apower - Measure signal power of stdin
.SH SYNOPSIS
.B
apower
[\fI-bs\fP \fIblocksize\fP] 
[\fI-e\fP \fIencoding\fP] 
[\fI-ccitt\fP] 
.SH DESCRIPTION
.PP
\fIapower\fP 
measures the power of a signal on stdin, printing the power
level on stdout every \fIblocksize\fP.  arecord(1) | apower is
a useful command pipeline.
.SH OPTIONS
.TP
.B [\fI-bs\fP]
.IP
Specifies the blocksize.  Defaults to 8000 (one second).
.TP
.B [\fI-ccitt\fP]
.IP
Calculates the signal power relative to the official CCITT digital milliwatt.
Otherwise calculates the power relative to a sine wave 3.16 dB below
digital clipping level.
.TP
.B [\fI-e\fP]
.IP
Specifies the encoding of the data. Valid arguments given by giving a
random value to -e.
.SH ENVIRONMENT
.TP 15
none
.SH BUG
Probably.
.PP
If you encounter a \fBreproducible\fP bug, please submit a problem report to
(af-bugs@crl.dec.com).
.SH "SEE ALSO"
atone(1) arecord(1)
.SH COPYRIGHT
Copyright 1993-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Digital Cambridge Research Lab
