.TH atone 1 "Release 1"  "AF Version 3"
.SH NAME
atone - Generate a sine wave to stdout
.SH SYNOPSIS
.B
atone 
[\fI-freq\fP \fIfrequency\fP] 
[\fI-power\fP \fIpower\fP] 
[\fI-phase\fP \fIphase\fP] 
[\fI-peak\fP \fIpeak\fP] 
[\fI-time\fP \fItime\fP] 
.SH DESCRIPTION
.PP
\fIatone\fP 
generates a sine wave tone on stdout in MU255 format.  atone | aplay
is a useful command pipeline.
.SH OPTIONS
.TP
.B [\fI-freq\fP]
.IP
Specifies the frequency in Hz.  Defaults to 1000.0.
.TP
.B [\fI-power\fP]
.IP
Specifies the power level in dB, relative to the digital milliwatt.
Defaults to -10.0.
.TP
.B [\fI-phase\fP]
.IP
Specifies the initial phase of the sine wave.  Legal values are in the range
0 to 1024 - which represent the cycle divided into 1024 parts.
Defaults to 0.
.TP
.B [\fI-peak\fP]
.IP
Specifies the peak integer value corresponding to the digital clipping level.
Defaults to 8031.  Don't change this one.
.TP
.B [\fI-time\fP]
.IP
Generates so many seconds of tone.  Default is infinite.
.SH ENVIRONMENT
.TP 15
none
.SH BUG
Probably.
.PP
If you encounter a \fBreproducible\fP bug, please submit a problem report to
(af-bugs@crl.dec.com).
.SH "SEE ALSO"
apower(1) aplay(1)
.SH COPYRIGHT
Copyright 1993-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Digital Cambridge Research Lab
