static void abort_archie_cb P_((Widget, XtPointer, XtPointer));
static void add_archie_host P_((char*, char*));
static void add_archie_text P_((char*, int));
static void archie_cb P_((Widget, XtPointer, XtPointer));
static void archie_hosts_cb P_((Widget, XtPointer, XtPointer));
static void archie_noop_cb P_((Widget, XtPointer, XtPointer));
static void archie_notify_cb P_((Widget, XtPointer, XtPointer));
static void archie_off P_(());
static void archie_on P_(());
static void archie_once P_(());
static void archie_search P_((char*));
static void clear_archie P_((Widget, char*, char*));
static void do_archie_cb P_((Widget, XtPointer, XtPointer));
static void read_archie P_((XtPointer, int*, XtInputId*));
static void register_archie_cb P_((Widget, XtPointer, XtPointer));
static void set_item_title_a P_((int));
static void sort_by P_(());
static int sort_by_age P_((char**, char**));
static int sort_by_name P_((char**, char**));
static int sort_by_size P_((char**, char**));
