static void abort_connect P_((struct _connect*, int));
static void abort_ftp_con P_(());
static void abort_listen P_((struct _listen*, int));
static int blocked P_((int));
static void connect_to_host P_((struct _connect*));
static void do_abort_connect P_((int));
static void do_abort_listen P_((int));
static void do_next P_(());
static void finish_abort P_((caddr_t, XtIntervalId*));
static void finish_close P_((caddr_t, XtIntervalId*));
static void finish_connect P_((XtPointer, int*, XtInputId*));
static void free_output P_((struct _output*));
static void get_host_address P_((struct _connect*));
static void list_finish P_((struct _output*, int, DATA));
static void list_status P_((char*, int));
static int net2unix P_((char*, int, char*));
static void read_data P_((XtPointer, int*, XtInputId*));
static void read_dir_data P_((XtPointer, int*, XtInputId*));
static void read_ftp P_((XtPointer, int*, XtInputId*));
static void start_data P_((XtPointer, int*, XtInputId*));
static void timout_connect P_((caddr_t, XtIntervalId*));
static int unix2net P_((char*, int, char*));
static void write_data P_((XtPointer, int*, XtInputId*));
