static void cb_cd P_((DATA, int, CB*));
static void cb_clean_up_cd P_((DATA, int, CB*));
static void cb_clean_up_lcd P_((DATA, int, CB*));
static void cb_cont P_((DATA, int, CB*));
static void cb_restart_cd P_((DATA, int, CB*));
static void cb_restart_lcd P_((DATA, int, CB*));
static void cb_set_dir_type P_((DATA, int, CB*));
static void cb_up P_((DATA, int, CB*));
static void do_dir P_((struct _dirs*));
static void do_next P_((int, int, DATA));
static void fix_position P_((struct _dirs*, int));
static void list_long_dir P_((struct _dirs*, int, int*, char*));
static void list_long_unix_dir P_((struct _dirs*));
static void list_medium_unix_dir P_((struct _dirs*));
static void list_short_dir P_((struct _dirs*));
static void list_short_unix_dir P_((struct _dirs*));
static void list_translations P_((struct _dirs*));
static void retain_position P_((struct _dirs*));
static void update_translation P_((struct _dirs*, int));
static void wait_no_connect P_((caddr_t, XtIntervalId*));
