static void cb_dir P_((DATA, int, CB*));
static void cb_ldir P_((DATA, int, CB*));
static void cb_prompt P_((DATA, int, CB*));
static void cb_pwd P_((DATA, int, CB*));
static void cb_set_dir_type P_((DATA, int, CB*));
static void cb_set_mode P_((DATA, int, CB*));
static void do_help_command P_((char*));
static void do_help_list P_(());
static void finish_ls P_((struct _output*, int, DATA));
static int params P_((char*, char*, int));
static void peek_ascii P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_binary P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_cd P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_dir P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_finish P_((struct _output*, int, DATA));
static void peek_get P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_help P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_image P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_lcd P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_lmkdir P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_lpwd P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_ls P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_mkdir P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_put P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_pwd P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_quote P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_reg P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_regget P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_regput P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_rhelp P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_site P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void peek_tenex P_((int, char*, char*, void(*)(), int, void(*)(), int));
static void set_local_cb P_((DATA, int, CB*));
static void set_remote_cb P_((DATA, int, CB*));
