static void abort_cb P_((Widget, char*, caddr_t));
static void anonymous_cb P_((Widget, XtPointer, XtPointer));
static void cb_cd P_((DATA, int, CB*));
static void cd_act P_((Widget, XEvent*, String*, Cardinal*));
static void clean_str P_((char*));
static void clear_cb P_((Widget, char*, caddr_t));
static void  clear_command P_((Widget));
static void clear_connect P_((Widget, char*, char*));
static void clear_list_entry_cb P_((Widget, XtPointer, XtPointer));
static void clear_status P_((caddr_t, XtIntervalId*));
static void clear_status_shell P_((Widget, char*, char*));
static void clear_tran P_((Widget, char*, char*));
static void connect_disconnect P_((Widget, char*, caddr_t));
static void create_tran P_((Widget));
static void do_cd_cb P_((Widget, char*, caddr_t));
static void do_connect P_(());
static void do_connect_act P_((Widget, XEvent*, String*, Cardinal*));
static void do_connect_cb P_((Widget, char*, caddr_t));
static void do_dir P_(());
static void do_toggle P_((char*, char*));
static void do_up P_(());
static void do_up_act P_((Widget, XEvent *, String *, Cardinal *));
static void do_up_cb P_((Widget, XtPointer, XtPointer));
static void draw_percent P_((Widget));
static void  file_action P_((Widget, MyXawListReturnStruct*));
static void get_connect_info P_((Widget, char*, caddr_t));
static void init_connect_info P_((Widget, char*, caddr_t));
static void init_percent P_(());
static void list_notify P_((Widget, XtPointer, XtPointer));
static void list_translations_cb P_((Widget, XtPointer, XtPointer));
static void listing_type P_((Widget, char*));
static void listing_type_act P_((Widget, XEvent*, String*, Cardinal*));
static void listing_type_cb P_((Widget, char*, caddr_t));
static void mark_menu_cb P_((Widget, XtPointer, XtPointer));
static void msg_cb P_((Widget, XtPointer, XtPointer));
static void no_window_group_cb P_((Widget, XtPointer, XtPointer));
static void noop_act P_((Widget, XEvent*, String*, Cardinal*));
static void op_cb P_((Widget, XtPointer, XtPointer));
static void open_file_act P_((Widget, XEvent*, String*, Cardinal*));
static void quit_cb P_((Widget, char*, caddr_t));
static void raise_window P_((char*));
static void raise_window_cb P_((Widget, XtPointer, XtPointer));
static void reconnect_cb P_((Widget, char*, caddr_t));
static void register_action_cb P_((Widget, XtPointer, XtPointer));
static void remote_local_toggle P_(());
static void remote_local_toggle_act P_((Widget, XEvent*, String*, Cardinal*));
static void remote_local_toggle_cb P_((Widget, char*, caddr_t));
static void reset_host_search P_(());
static void resize_percent_act P_((Widget, XEvent*, String*, Cardinal*));
static void retry_connect P_((caddr_t, XtIntervalId*));
static void search_act P_((Widget, XEvent*, String*, Cardinal*));
static void search_cb P_((Widget, char*, caddr_t));
static void search_host_act P_((Widget, XEvent*, String*, Cardinal*));
static void  search_host_next P_(());
static void search_next P_(());
static void select_host_cb P_((Widget, XtPointer, XtPointer));
static void set_connect_info P_(());
static void set_file_action_act P_((Widget, XEvent*, String*, Cardinal*));
static void set_file_action_cb P_((Widget, XtPointer, XtPointer));
static void set_file_action_menu_cb P_((Widget, XtPointer, XtPointer));
static void set_host P_((int));
static void set_host_list_cb P_((Widget, XtPointer, XtPointer));
static void set_icons_act P_((Widget, XEvent*, String*, Cardinal*));
static void set_icons_cb P_((Widget, XtPointer, XtPointer));
static void set_iconx P_((Widget, char*));
static void set_status_icon_act P_((Widget, XEvent*, String*, Cardinal*));
static char * set_text_password P_((Widget, char*));
static void set_tran_cb P_((Widget, char*, caddr_t));
static void shell_tran_cb P_((Widget, char*, caddr_t));
static void single_file_actions_act P_((Widget, XEvent*, String*, Cardinal*));
static void single_file_actions_cb P_((Widget, XtPointer, XtPointer));
static void toggle_cb P_((Widget, XtPointer, XtPointer));
static void update_selections P_((struct _dirs*));
static int  verify_connect_info P_(());
static int verify_gateway P_(());
static int  verify_host P_(());
static int verify_login P_(());
static int verify_password P_(());
static void  wait_file P_((XtPointer, int*, XtInputId*));
static int white_space P_((char*));
