static Widget CreateDialogWindow P_((Widget, String, Arg*, Cardinal));
static Widget CreateRateWindow P_((Widget, String, Arg*, Cardinal));
static Widget CreateStatusWindow P_((Widget, String, Arg*, Cardinal));
static void MenuNoop_act P_((Widget, XEvent*, String*, Cardinal*));
static XawTextPosition TextGetLastPos P_((Widget));
static void WM_DELETE_UNREGISTER P_((Widget));
static void bind_menu_cb P_((Widget, XtPointer, XtPointer));
static void context_help P_(());
static void delete_char_act P_((Widget, XEvent*, String*, Cardinal*));
static void delete_line_act P_((Widget, XEvent*, String*, Cardinal*));
static void delete_view P_((Widget));
static void delete_view_file_cb P_((Widget, XtPointer, XtPointer));
static void delete_word_act P_((Widget, XEvent*, String*, Cardinal*));
static void dispatch_act P_((Widget, XEvent*, String*, Cardinal*));
static Widget findwidget P_((Widget, int, int));
static void help_act P_((Widget, XEvent*, String*, Cardinal*));
static void help_cb P_((Widget, XtPointer, XtPointer));
static void help_context_f P_(());
static void insert_char_act P_((Widget, XEvent*, String*, Cardinal*));
static void insert_space_act P_((Widget, XEvent*, String*, Cardinal*));
static void menu_cascade_act P_((Widget, XEvent*, String*, Cardinal*));
static void my_popup_act P_((Widget, XEvent *, String *, Cardinal *));
static void pop_down_subs P_((Widget));
static void pop_down_subs_act P_((Widget, XEvent*, String*, Cardinal*));
static void pop_down_subs_cb P_((Widget, XtPointer, XtPointer));
static void set_form_horiz_cb P_((Widget, XtPointer, XtPointer));
static void set_form_vert_cb P_((Widget, XtPointer, XtPointer));
static void set_retry_cb P_((Widget, char*, caddr_t));
static void set_use_gateway_cb P_((Widget, XtPointer, XtPointer));
static void set_view_file_cb P_((Widget, XtPointer, XtPointer));
static void set_width_cb P_((Widget, XtPointer, XtPointer));
static void warp_pointer_act P_((Widget, XEvent*, String*, Cardinal*));
static void wm_delete_act P_((Widget, XEvent *, String *, Cardinal *));
