/*
 * sidtool_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `sidtool.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "sidtool_ui.h"

/*
 * Initialize an instance of object `Wmain'.
 */
sidtool_Wmain_objects *
sidtool_Wmain_objects_initialize(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (sidtool_Wmain_objects *) calloc(1, sizeof (sidtool_Wmain_objects))))
		return (sidtool_Wmain_objects *) NULL;
	if (!ip->Wmain)
		ip->Wmain = sidtool_Wmain_Wmain_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = sidtool_Wmain_controls1_create(ip, ip->Wmain);
	if (!ip->Bhelp)
		ip->Bhelp = sidtool_Wmain_Bhelp_create(ip, ip->controls1);
	if (!ip->Bprops)
		ip->Bprops = sidtool_Wmain_Bprops_create(ip, ip->controls1);
	if (!ip->Bscores)
		ip->Bscores = sidtool_Wmain_Bscores_create(ip, ip->controls1);
	if (!ip->Bquit)
		ip->Bquit = sidtool_Wmain_Bquit_create(ip, ip->controls1);
	if (!ip->Mhigh_score)
		ip->Mhigh_score = sidtool_Wmain_Mhigh_score_create(ip, ip->controls1);
	if (!ip->Bnewgame)
		ip->Bnewgame = sidtool_Wmain_Bnewgame_create(ip, ip->controls1);
	if (!ip->Bstop)
		ip->Bstop = sidtool_Wmain_Bstop_create(ip, ip->controls1);
	if (!ip->SETgame)
		ip->SETgame = sidtool_Wmain_SETgame_create(ip, ip->controls1);
	if (!ip->Mhscore)
		ip->Mhscore = sidtool_Wmain_Mhscore_create(ip, ip->controls1);
	if (!ip->Mcounter1)
		ip->Mcounter1 = sidtool_Wmain_Mcounter1_create(ip, ip->controls1);
	if (!ip->Mcounter2)
		ip->Mcounter2 = sidtool_Wmain_Mcounter2_create(ip, ip->controls1);
	if (!ip->Mcounter3)
		ip->Mcounter3 = sidtool_Wmain_Mcounter3_create(ip, ip->controls1);
	if (!ip->Mcounter4)
		ip->Mcounter4 = sidtool_Wmain_Mcounter4_create(ip, ip->controls1);
	if (!ip->Mplayer1)
		ip->Mplayer1 = sidtool_Wmain_Mplayer1_create(ip, ip->controls1);
	if (!ip->Mscore1)
		ip->Mscore1 = sidtool_Wmain_Mscore1_create(ip, ip->controls1);
	if (!ip->Mplayer2)
		ip->Mplayer2 = sidtool_Wmain_Mplayer2_create(ip, ip->controls1);
	if (!ip->Mscore2)
		ip->Mscore2 = sidtool_Wmain_Mscore2_create(ip, ip->controls1);
	if (!ip->Mfruitpic)
		ip->Mfruitpic = sidtool_Wmain_Mfruitpic_create(ip, ip->controls1);
	if (!ip->Mplayer3)
		ip->Mplayer3 = sidtool_Wmain_Mplayer3_create(ip, ip->controls1);
	if (!ip->Mscore3)
		ip->Mscore3 = sidtool_Wmain_Mscore3_create(ip, ip->controls1);
	if (!ip->Mplayer4)
		ip->Mplayer4 = sidtool_Wmain_Mplayer4_create(ip, ip->controls1);
	if (!ip->Mscore4)
		ip->Mscore4 = sidtool_Wmain_Mscore4_create(ip, ip->controls1);
	if (!ip->Mfruitval)
		ip->Mfruitval = sidtool_Wmain_Mfruitval_create(ip, ip->controls1);
	if (!ip->Ccanvas)
		ip->Ccanvas = sidtool_Wmain_Ccanvas_create(ip, ip->Wmain);
	return ip;
}

/*
 * Create object `Wmain' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Wmain_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	Xv_opaque	Wmain_image;
#include "images/sidtool.xbm"
	
	Wmain_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_X_BITS, sidtool_bits,
		XV_WIDTH, sidtool_width,
		XV_HEIGHT, sidtool_height,
		NULL);
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 749,
		XV_HEIGHT, 870,
		XV_LABEL, "Software Interactive Debugger.",
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_ICON, xv_create(XV_NULL, ICON,
			ICON_IMAGE, Wmain_image,
			NULL),
		NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_controls1_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 104,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `Bhelp' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Bhelp_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	extern void		Bnotify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Help",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, Bnotify,
		NULL);
	return obj;
}

/*
 * Create object `Bprops' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Bprops_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	extern void		Bnotify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 64,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Props...",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, Bnotify,
		NULL);
	return obj;
}

/*
 * Create object `Bscores' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Bscores_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	extern void		Bnotify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 136,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Scores...",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, Bnotify,
		NULL);
	return obj;
}

/*
 * Create object `Bquit' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Bquit_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	extern void		Bnotify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 208,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Quit",
		PANEL_NOTIFY_PROC, Bnotify,
		NULL);
	return obj;
}

/*
 * Create object `Mhigh_score' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mhigh_score_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 264,
		XV_Y, 8,
		PANEL_LABEL_STRING, "High Score:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Bnewgame' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Bnewgame_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	extern void		Bnotify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 432,
		XV_Y, 8,
		PANEL_LABEL_STRING, "New Game",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, Bnotify,
		NULL);
	return obj;
}

/*
 * Create object `Bstop' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Bstop_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	extern void		Bnotify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 520,
		XV_Y, 8,
		PANEL_LABEL_WIDTH, 60,
		PANEL_LABEL_STRING, "    Stop",
		PANEL_NOTIFY_PROC, Bnotify,
		NULL);
	return obj;
}

/*
 * Create object `SETgame' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_SETgame_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 600,
		XV_Y, 8,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Play:",
		PANEL_CHOICE_STRINGS,
			"Demo",
			"Game",
			NULL,
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mhscore' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mhscore_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 350,
		XV_Y, 10,
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `Mcounter1' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mcounter1_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	Xv_opaque	Mcounter1_image;
#include "images/empty.xbm"
	
	Mcounter1_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_X_BITS, empty_bits,
		XV_WIDTH, empty_width,
		XV_HEIGHT, empty_height,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 10,
		XV_Y, 40,
		PANEL_LABEL_IMAGE, Mcounter1_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mcounter2' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mcounter2_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	Xv_opaque	Mcounter2_image;
#include "images/empty.xbm"
	
	Mcounter2_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_X_BITS, empty_bits,
		XV_WIDTH, empty_width,
		XV_HEIGHT, empty_height,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 65,
		XV_Y, 40,
		PANEL_LABEL_IMAGE, Mcounter2_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mcounter3' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mcounter3_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	Xv_opaque	Mcounter3_image;
#include "images/empty.xbm"
	
	Mcounter3_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_X_BITS, empty_bits,
		XV_WIDTH, empty_width,
		XV_HEIGHT, empty_height,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 120,
		XV_Y, 40,
		PANEL_LABEL_IMAGE, Mcounter3_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mcounter4' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mcounter4_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	Xv_opaque	Mcounter4_image;
#include "images/empty.xbm"
	
	Mcounter4_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_X_BITS, empty_bits,
		XV_WIDTH, empty_width,
		XV_HEIGHT, empty_height,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 175,
		XV_Y, 40,
		PANEL_LABEL_IMAGE, Mcounter4_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mplayer1' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mplayer1_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 264,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Player 1:",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mscore1' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mscore1_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 335,
		XV_Y, 40,
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `Mplayer2' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mplayer2_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 500,
		XV_Y, 40,
		PANEL_LABEL_STRING, "Player 2:",
		PANEL_LABEL_BOLD, TRUE,
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mscore2' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mscore2_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 588,
		XV_Y, 40,
		PANEL_LABEL_BOLD, FALSE,
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mfruitpic' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mfruitpic_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	Xv_opaque	Mfruitpic_image;
#include "images/empty.xbm"
	
	Mfruitpic_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_X_BITS, empty_bits,
		XV_WIDTH, empty_width,
		XV_HEIGHT, empty_height,
		NULL);
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 690,
		XV_Y, 40,
		PANEL_LABEL_IMAGE, Mfruitpic_image,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mplayer3' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mplayer3_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 264,
		XV_Y, 80,
		PANEL_LABEL_STRING, "Player 3:",
		PANEL_LABEL_BOLD, TRUE,
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mscore3' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mscore3_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 335,
		XV_Y, 80,
		PANEL_LABEL_BOLD, FALSE,
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mplayer4' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mplayer4_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 500,
		XV_Y, 80,
		PANEL_LABEL_STRING, "Player 4:",
		PANEL_LABEL_BOLD, TRUE,
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mscore4' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mscore4_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 588,
		XV_Y, 80,
		PANEL_LABEL_BOLD, FALSE,
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Mfruitval' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Mfruitval_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 690,
		XV_Y, 90,
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `Ccanvas' in the specified instance.
 */
Xv_opaque
sidtool_Wmain_Ccanvas_create(ip, owner)
	sidtool_Wmain_objects	*ip;
	Xv_opaque		owner;
{
	extern Notify_value	Ccanvas_event();
	extern void	Ccanvas_repaint();
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, (int)xv_get(ip->controls1, XV_Y) +
		      (int)xv_get(ip->controls1, XV_HEIGHT),
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		CANVAS_REPAINT_PROC, Ccanvas_repaint,
		CANVAS_X_PAINT_WINDOW, TRUE,
		NULL);
	xv_set(canvas_paint_window(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		LOC_WINENTER,
		LOC_WINEXIT,
		WIN_ASCII_EVENTS,
		NULL, NULL);
	notify_interpose_event_func(canvas_paint_window(obj),
		(Notify_func) Ccanvas_event, NOTIFY_SAFE);
	/*
	 * This line is here for backwards compatibility. It will be
	 * removed for the next release.
	 */
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

/*
 * Initialize an instance of object `Pprops'.
 */
sidtool_Pprops_objects *
sidtool_Pprops_objects_initialize(ip, owner)
	sidtool_Pprops_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (sidtool_Pprops_objects *) calloc(1, sizeof (sidtool_Pprops_objects))))
		return (sidtool_Pprops_objects *) NULL;
	if (!ip->Pprops)
		ip->Pprops = sidtool_Pprops_Pprops_create(ip, owner);
	if (!ip->controls2)
		ip->controls2 = sidtool_Pprops_controls2_create(ip, ip->Pprops);
	if (!ip->SETplayer)
		ip->SETplayer = sidtool_Pprops_SETplayer_create(ip, ip->controls2);
	if (!ip->SLlevel)
		ip->SLlevel = sidtool_Pprops_SLlevel_create(ip, ip->controls2);
	if (!ip->BPapply)
		ip->BPapply = sidtool_Pprops_BPapply_create(ip, ip->controls2);
	if (!ip->BPreset)
		ip->BPreset = sidtool_Pprops_BPreset_create(ip, ip->controls2);
	return ip;
}

/*
 * Create object `Pprops' in the specified instance.
 */
Xv_opaque
sidtool_Pprops_Pprops_create(ip, owner)
	sidtool_Pprops_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 295,
		XV_HEIGHT, 99,
		XV_LABEL, "Properties",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls2' in the specified instance.
 */
Xv_opaque
sidtool_Pprops_controls2_create(ip, owner)
	sidtool_Pprops_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `SETplayer' in the specified instance.
 */
Xv_opaque
sidtool_Pprops_SETplayer_create(ip, owner)
	sidtool_Pprops_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 8,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Players:",
		PANEL_CHOICE_STRINGS,
			"1",
			"2",
			"3",
			"4",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `SLlevel' in the specified instance.
 */
Xv_opaque
sidtool_Pprops_SLlevel_create(ip, owner)
	sidtool_Pprops_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 40,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_TICKS, 0,
		PANEL_LABEL_STRING, "Skill level:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 1,
		PANEL_MAX_VALUE, 10,
		PANEL_VALUE, 5,
		NULL);
	return obj;
}

/*
 * Create object `BPapply' in the specified instance.
 */
Xv_opaque
sidtool_Pprops_BPapply_create(ip, owner)
	sidtool_Pprops_objects	*ip;
	Xv_opaque		owner;
{
	extern void		Bnotify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 72,
		XV_Y, 72,
		PANEL_LABEL_STRING, "Apply",
		PANEL_NOTIFY_PROC, Bnotify,
		NULL);
	return obj;
}

/*
 * Create object `BPreset' in the specified instance.
 */
Xv_opaque
sidtool_Pprops_BPreset_create(ip, owner)
	sidtool_Pprops_objects	*ip;
	Xv_opaque		owner;
{
	extern void		Bnotify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 160,
		XV_Y, 72,
		PANEL_LABEL_STRING, "Reset",
		PANEL_NOTIFY_PROC, Bnotify,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `Pscores'.
 */
sidtool_Pscores_objects *
sidtool_Pscores_objects_initialize(ip, owner)
	sidtool_Pscores_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (sidtool_Pscores_objects *) calloc(1, sizeof (sidtool_Pscores_objects))))
		return (sidtool_Pscores_objects *) NULL;
	if (!ip->Pscores)
		ip->Pscores = sidtool_Pscores_Pscores_create(ip, owner);
	if (!ip->controls3)
		ip->controls3 = sidtool_Pscores_controls3_create(ip, ip->Pscores);
	if (!ip->MShighscore)
		ip->MShighscore = sidtool_Pscores_MShighscore_create(ip, ip->controls3);
	if (!ip->MSoldscore)
		ip->MSoldscore = sidtool_Pscores_MSoldscore_create(ip, ip->controls3);
	if (!ip->MSplayer)
		ip->MSplayer = sidtool_Pscores_MSplayer_create(ip, ip->controls3);
	if (!ip->MSname)
		ip->MSname = sidtool_Pscores_MSname_create(ip, ip->controls3);
	if (!ip->Lscores)
		ip->Lscores = sidtool_Pscores_Lscores_create(ip, ip->controls3);
	return ip;
}

/*
 * Create object `Pscores' in the specified instance.
 */
Xv_opaque
sidtool_Pscores_Pscores_create(ip, owner)
	sidtool_Pscores_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 362,
		XV_HEIGHT, 216,
		XV_LABEL, "High Scores Per Skill Level",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls3' in the specified instance.
 */
Xv_opaque
sidtool_Pscores_controls3_create(ip, owner)
	sidtool_Pscores_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `MShighscore' in the specified instance.
 */
Xv_opaque
sidtool_Pscores_MShighscore_create(ip, owner)
	sidtool_Pscores_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_LABEL_BOLD, FALSE,
		XV_SHOW, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `MSoldscore' in the specified instance.
 */
Xv_opaque
sidtool_Pscores_MSoldscore_create(ip, owner)
	sidtool_Pscores_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 32,
		PANEL_LABEL_BOLD, FALSE,
		XV_SHOW, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `MSplayer' in the specified instance.
 */
Xv_opaque
sidtool_Pscores_MSplayer_create(ip, owner)
	sidtool_Pscores_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 56,
		PANEL_LABEL_BOLD, FALSE,
		XV_SHOW, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `MSname' in the specified instance.
 */
Xv_opaque
sidtool_Pscores_MSname_create(ip, owner)
	sidtool_Pscores_objects	*ip;
	Xv_opaque		owner;
{
	extern Panel_setting	Snotify();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 80,
		PANEL_VALUE_DISPLAY_LENGTH, 30,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Name:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		XV_SHOW, FALSE,
		PANEL_READ_ONLY, FALSE,
		PANEL_NOTIFY_PROC, Snotify,
		NULL);
	return obj;
}

/*
 * Create object `Lscores' in the specified instance.
 */
Xv_opaque
sidtool_Pscores_Lscores_create(ip, owner)
	sidtool_Pscores_objects	*ip;
	Xv_opaque		owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 104,
		PANEL_LIST_WIDTH, 345,
		PANEL_LIST_DISPLAY_ROWS, 5,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		PANEL_LIST_STRINGS,
			"1:",
			"2:",
			"3:",
			"4:",
			"5:",
			"6:",
			"7:",
			"8:",
			"9:",
			"10:",
			NULL,
		NULL);
	return obj;
}

