#undef	NO_EXTENSIONS

#ifdef	NO_EXTENSIONS

#else

#define	MAX_CLIQUE_ALGORITHM

#define	HT_PLANARITY_TEST_ALGORITHM
#define	HT_DUALGRAPH_ALGORITHM
#define	DRAW_CONVEX_ALGORITHM

#define	CONNECTIVITY_TEST_ALGORITHMS
#define	PQ_PLANARITY_TEST_ALGORITHM
#define	TREE_LAYOUT_ALGORITHM
#define	SUGIYAMA_LAYOUT_ALGORITHM
#define	SPRING_EMBEDDER_DRAWING_ALGORITHM
#define	WOODS_DRAWING_ALGORITHM

#define	BENDS_DRAWING_ALGORITHM
#define	CHROBAK_PAYNE_DRAWING_ALGORITHM
#define	SPRINGEMBEDDER_KAMADA
#define	SCHNIEDERS_DRAWING_ALGORITHMS
#define	RT_TREE_DRAWING_ALGORITHM
#define	OLD_CONNECTIVITY_ALGORITHMS
#define	TERMGRAPH
#define	SCHNIEDERS_DRAWING_ALGORITHMS

#if defined(WOODS_DRAWING_ALGORITHM) || defined (SCHNIEDERS_DRAWING_ALGORITHMS)
#define	PQ_PLANARITY_TEST_ALGORITHM
#endif
#if defined(DRAW_CONVEX_ALGORITHM)
#define	HT_PLANARITY_TEST_ALGORITHM
#endif


#endif
