############################################
# dstool - GENERIC LIBRARY makefile        #
############################################

include ${DSTOOL}/site_specific/lib_incl.mk
############################################
# Modify the following segment only.       #
############################################

LIBRARY = autoiflib.a

SOURCES_A = \
	autoif.c \
	autoif_hnd.c \
	autoif_cui.c 

DEPS_A = autoif_cui.h

SOURCES_B =

DEPS_B = 

TEST_PROGRAM = 

TEST_SOURCES = 

TEST_DEPS =

##############################################
# The following lines should not be modified #
# except for working with test code          #
##############################################

include ${DSTOOL}/site_specific/win_targetsA.mk
