/*  -------------------------------------------------------------------

This program is the property of:

                             Cornell University 
                        Center for Applied Mathematics 
                              Ithaca, NY 14853

and may be used, modified and distributed freely, subject to the 
following restrictions:

       Any product which incorporates source code from the dstool
       program or utilities, in whole or in part, is distributed
       with a copy of that source code, including this notice. You
       must give the recipients all the rights that you have with
       respect to the use of this software. Modifications of the
       software must carry prominent notices stating who changed
       the files and the date of any change.

DsTool is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of FITNESS 
FOR A PARTICULAR PURPOSE.  The software is provided as is without 
any obligation on the part of Cornell faculty, staff or students to 
assist in its use, correction, modification or enhancement.

  -----------------------------------------------------------------  */
#ifndef	geomview_HEADER
#define	geomview_HEADER

/*
 * geomview_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `geomview.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	window1;
	Xv_opaque	controls1;
	Xv_opaque	window_number;
	Xv_opaque	view;
	Xv_opaque	hor;
	Xv_opaque	ver;
	Xv_opaque	depth;
	Xv_opaque	destination;
	Xv_opaque	directory;
	Xv_opaque	filename;
} geomview_window1_objects;

extern geomview_window1_objects	*geomview_window1_objects_initialize();

extern Xv_opaque	geomview_window1_window1_create();
extern Xv_opaque	geomview_window1_controls1_create();
extern Xv_opaque	geomview_window1_window_number_create();
extern Xv_opaque	geomview_window1_view_create();
extern Xv_opaque	geomview_window1_hor_create();
extern Xv_opaque	geomview_window1_ver_create();
extern Xv_opaque	geomview_window1_depth_create();
extern Xv_opaque	geomview_window1_destination_create();
extern Xv_opaque	geomview_window1_directory_create();
extern Xv_opaque	geomview_window1_filename_create();
#endif
