#ifndef	gcc_HEADER
#define	gcc_HEADER

/*
 * gcc_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `gcc.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls;
	Xv_opaque	color_list;
	Xv_opaque	color_blot;
	Xv_opaque	color_name;
	Xv_opaque	apply;
	Xv_opaque	reset;
} gcc_win_objects;

extern gcc_win_objects	*gcc_win_objects_initialize();

extern Xv_opaque	gcc_win_win_create();
extern Xv_opaque	gcc_win_controls_create();
extern Xv_opaque	gcc_win_color_list_create();
extern Xv_opaque	gcc_win_color_blot_create();
extern Xv_opaque	gcc_win_color_name_create();
extern Xv_opaque	gcc_win_apply_create();
extern Xv_opaque	gcc_win_reset_create();
#endif
