.\" @(#)cc.l    @(#)phonetool.1	
.TH PHONETOOL 1 "25 January 1991"
.SH NAME
.B phonetool
\- a message-sending tool for phone calls intercepted on behalf of a co-worker
.SH SYNOPSIS
.B phonetool
[
.I any OpenLook window options
]
.SH DESCRIPTION
.LP
.B phonetool
is an OpenLook style application that was originally created to run under Sun's OpenWindows environment.  It is written in XView, and its code skeleton was created using Sun's DevGuide product.  

.B phonetool
is a simple message-sending tool.  It does nothing that regular email won't do, but it is designed to reduce the typing involved when intercepting a call for a fellow worker who's not at his/her desk.  Users keep 
.B phonetool
iconified on their desktop, and simply pop it open and fill in a name and a phone number when they intercept a call for a co-worker.
.LP
.SH OPTIONS
.TP 12
Use any OpenLook window options with this tool.
.SH USAGE
.LP
The 
.B phonetool
application is about the same size as those little pink or yellow slips of paper your secertary leaves on your desk with phone messages on it (about 4" x 5 1/4" here in the U.S... I'm not sure what various Europeans use...).  At the top of the 
.B phonetool
pane is a "To:" text field with a "login id's" menu button to the right of it. Users can type in any valid email address in the text field that is under 80 characters.  Invalid addresses result in mail being returned to the sender.  For efficiency, users can select a name from the "login id's" menu instead, and that name will appear in the "To:" text field.

The "login id's" menu is compiled directly from the
.I .phonerc
file.  Users must have a
.I .phonerc
file in their home directory.  The
.I .phonerc
file contains the login name, email address, or email alias of co-workers for whom they might intercept phone calls.  The file may contain comments on lines beginning with a pound (#) sign.  Only one login name, email address, or email alias is allowed per line in the file.

Below the "To:" text field are three more text fields, "Caller:", "Company:", and "Phone:".  Users fill these text fields in with the relevant information while they are taking the message on the phone.  Below these fields are six checkbox items with "canned" messages next to them that users may select from.  Or, if elaboration is required, below the checkboxes is an "Other:" scrolling text pane in which users can enter a longer message.

At the bottom is a "Send Message" button that, when pressed, mails the message off to the email address specified at the top and then clears the form for the next message.  There is also a "Clear" button at the bottom which blanks out all the fields, checkboxes, and text if the user decides not to take a message he/she has already started.
.SH NOTES
.br 
.B phonetool 
should run under any X-based window manager.  It will not, however, run under a kernel-based windowing system, such as SunView.  Users must also have a copy of a
.I .phonerc 
file to build the "login id's" menu.  If the user doesn't wish to have anything in that menu, the
.I .phonerc
file may still be present, only it must be empty.  Or the user may forgo having a
.I .phonerc
file at all.  The
.I .phonerc
file must be in the home directory.  The
.I .phonerc
file contains the login name, email address, or email alias of co-workers for whom they might intercept phone calls.  The file may contain comments on lines beginning with a pound (#) sign.  Only one login name, email address, or email alias is allowed per line in the file.

.SH BUGS
.br
.B phonetool
may not run on machines other than Sun's without font problems.

The scrollbar on the scrolling text pane sometimes is drawn incorrectly, and the bottom anchor does not appear.  It is still usable.
.SH  COMPLAINTS/FIXES
.br
To indi, currently at uunet!ssi!young.
