.TH aevents 1 "Release 1"  "AF Version 3"
.SH NAME
aevents - An AF event logging client.
.SH SYNOPSIS
.B
aevents [\fB\-ringcount\fP \fIcount\fP] [\fB\-noprint\fP] 
.SH DESCRIPTION
\fIaevents\fP 
logs all audio server events to stdout.  The following event types are
logged:  phone ring, phone DTMF, phone loop current, phone hook switch,
DSP (if supported by the server), and property change events.
.SH Options
.TP
.B \-ringcount \fIcount\fP
.IP 
Causes aevents to exit after \fIcount\fP rings on the telephone.
Will not exit unless \fIcount\fP rings are received as a single
call.
.TP
.B \-noprint
.IP 
Supresses normal event printout.
.SH ENVIRONMENT
.TP 15
.B AUDIOFILE
specifies the host and server to use.
.SH BUGS
There is no way to specify any device other than device 0.
.PP
If you encounter a \fBreproducible\fP bug, please submit a problem report 
to (af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1)
.SH COPYRIGHT
Copyright 1992-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Digital Cambridge Research Lab
