############################################
# dstool - utilities  makefile             #
############################################

include ${DSTOOL}/site_specific/lib_incl.mk
############################################
# Modify the following segment only.       #
############################################
LIBRARY = utillib.a 

SOURCES_A = \
	dir_util.c \
	file_util.c \
	user_util.c \
	time_util.c \
	system_mess.c \
	macros.c \
	str_util.c \
	interrupt.c

DEPS_A = \
	$(DSTOOL)/src/include/pm.h

SOURCES_B =

DEPS_B = 

TEST_PROGRAM = 

TEST_SOURCES = 

TEST_DEPS =

##############################################
# The following line should not be modified  #
##############################################

include ${DSTOOL}/site_specific/targetsA.mk

