/*
 *	Copyright (c) 1990 by Columbia University.
 */

extern char *progname;
extern char *xdisplay;
extern char *newsdisplay;
extern char *ice_filenm;
extern char *initpsd_filenm;
extern boolean init_complete;
extern int verbose;
extern int pg_pixwidth, pg_pixheight, pg_pixdepth;
extern double pg_width, pg_height;
extern int pg_dpi;
extern int pg_update;
extern boolean pg_forceupdate;
extern int pg_units;
extern double pg_hsi, pg_vsi;
extern double pg_xri, pg_yri;
extern double pg_xru, pg_yru;
extern int pg_loc;
extern int pg_locdisplay;
extern Path *pg_clip;
extern int pg_originhlt;
extern int pg_bg;
extern unsigned char pg_rbg, pg_gbg, pg_bbg;

extern char *gdf_fontname;
extern float gdf_fontsize;
extern float gdf_fontlead;
extern float gdf_linewidth;
extern int gdf_fg;
extern unsigned char gdf_rfg, gdf_gfg, gdf_bfg;
extern int gdf_bg;
extern unsigned char gdf_rbg, gdf_gbg, gdf_bbg;
extern int gdf_mrktype;
extern float gdf_mrksize;
extern float gdf_bndwidth;
extern int gdf_bnd;
extern unsigned char gdf_rbnd, gdf_gbnd, gdf_bbnd;
extern int gdf_fill;
extern unsigned char gdf_rfill, gdf_gfill, gdf_bfill;
extern int gdf_dtk;
extern unsigned char gdf_rdtk, gdf_gdtk, gdf_bdtk;

extern int ins_newobj;

extern Display *dpy;
extern int screen;
extern Window root_win;
extern Visual *visual;
extern Colormap def_cmap, cmap, curr_cmap;
extern XColor def_colors[];
extern XFontStruct *font;
extern Atom wmpr_atom, wmsy_atom, wmdw_atom;
extern char fontnm[];
extern char geometry[];
extern int fontht, charwd;
extern unsigned long fg_pixel, bg_pixel, bdr_pixel;
extern unsigned long black_pixel, white_pixel;
extern unsigned int border_wd;
extern PSFontFamily *psfontfamilies;
extern int npsfonts, npsfontfamilies;
extern Panel_item *gdf_psff, *text_psff, *axis_psff;

extern int pg_frameleft, pg_frametop;
extern unsigned int pg_framewidth, pg_frameheight;
extern Window pg_frame;
extern Canvas *pg_canvas;
extern Window pg_cwin;
extern Pixmap pg_cpm;
extern GC pg_gc, pg_ogc, pg_igc, pg_xgc, pg_cgc;
extern unsigned long pg_bgpixel;
extern GC pg_bggc;
extern Cursor std_cursor, hg_cursor;

extern Menu *pg_menu;
extern Menu *ins_menu;
extern Menu *del_menu;
extern Menu *delpsd_menu, *delras_menu, *deltext_menu;
extern Menu *delvec_menu, *delcrv_menu, *delmrk_menu;
extern Menu *delrect_menu, *delpoly_menu, *delaxis_menu;
extern Menu *delcmp_menu, *delpth_menu;
extern Menu *attr_menu;
extern Menu *attrpsd_menu, *attrras_menu, *attrtext_menu;
extern Menu *attrvec_menu, *attrcrv_menu, *attrmrk_menu;
extern Menu *attrrect_menu, *attrpoly_menu, *attraxis_menu;
extern Menu *attrpth_menu;
extern Menu *tr_menu;
extern Menu *trpsd_menu, *trras_menu, *trtext_menu;
extern Menu *trvec_menu, *trcrv_menu, *trmrk_menu;
extern Menu *trrect_menu, *trpoly_menu, *traxis_menu;
extern Menu *trcmp_menu, *trpth_menu;
extern Menu *cp_menu;
extern Menu *cppsd_menu, *cpras_menu, *cptext_menu;
extern Menu *cpvec_menu, *cpcrv_menu, *cpmrk_menu;
extern Menu *cprect_menu, *cppoly_menu, *cpaxis_menu;
extern Menu *cpcmp_menu;
extern Menu *cmp_menu;
extern Menu *cmpattr_menu, *cmpubd_menu, *cmpadd_menu, *cmprm_menu;
extern Menu *cmpop_menu;
extern Menu *cmpoppsd_menu, *cmpopras_menu, *cmpoptext_menu;
extern Menu *cmpopvec_menu, *cmpopcrv_menu, *cmpopmrk_menu;
extern Menu *cmpoprect_menu, *cmpoppoly_menu, *cmpopaxis_menu;
extern Menu *cmpopcmp_menu;
extern Menu *cmap_menu;
extern Menu *dmp_menu, *dmpall_menu;
extern Menu *dmppsd_menu, *dmpras_menu, *dmptext_menu;
extern Menu *dmpvec_menu, *dmpcrv_menu, *dmpmrk_menu;
extern Menu *dmprect_menu, *dmppoly_menu, *dmpaxis_menu;
extern Menu *dmpcmp_menu, *dmppth_menu;

extern Window pgattr_frame;
extern Panel *pgattr_panel;
extern Panel_item *pgattr_w, *pgattr_h, *pgattr_dpi;
extern Panel_item *pgattr_update;
extern Panel_item *pgattr_loc;
extern Panel_item *pgattr_locdisplay;
extern Panel_item *pgattr_units;
extern Panel_item *pgattr_hsi, *pgattr_vsi;
extern Panel_item *pgattr_xri, *pgattr_yri;
extern Panel_item *pgattr_xru, *pgattr_yru;
extern Panel_item *pgattr_clip;
extern Panel_item *pgattr_originhlt;
extern Panel_item *pgattr_bg;
extern Panel_item *pgattr_rbg, *pgattr_gbg, *pgattr_bbg;
extern Panel_item *pgattr_cont, *pgattr_abort;

extern Window gdfattr_frame;
extern Panel *gdfattr_panel;
extern Panel_item *gdfattr_fontfamily;
extern Panel_item *gdfattr_fontsize;
extern Panel_item *gdfattr_fontlead;
extern Panel_item *gdfattr_linewidth;
extern Panel_item *gdfattr_fg;
extern Panel_item *gdfattr_rfg, *gdfattr_gfg, *gdfattr_bfg;
extern Panel_item *gdfattr_bg;
extern Panel_item *gdfattr_rbg, *gdfattr_gbg, *gdfattr_bbg;
extern Panel_item *gdfattr_mrktype;
extern Panel_item *gdfattr_mrksize;
extern Panel_item *gdfattr_bndwidth;
extern Panel_item *gdfattr_bnd;
extern Panel_item *gdfattr_rbnd, *gdfattr_gbnd, *gdfattr_bbnd;
extern Panel_item *gdfattr_fill;
extern Panel_item *gdfattr_rfill, *gdfattr_gfill, *gdfattr_bfill;
extern Panel_item *gdfattr_dtk;
extern Panel_item *gdfattr_rdtk, *gdfattr_gdtk, *gdfattr_bdtk;
extern Panel_item *gdfattr_cont, *gdfattr_abort;

extern Window insattr_frame;
extern Panel *insattr_panel;
extern Panel_item *insattr_newobj;
extern Panel_item *insattr_cont, *insattr_abort;

extern Window psdattr_frame;
extern Panel *psdattr_panel;
extern Panel_item *psdattr_fname;
extern Panel_item *psdattr_hscale, *psdattr_vscale;
extern Panel_item *psdattr_rot;
extern Panel_item *psdattr_clip;
extern Panel_item *psdattr_dtk;
extern Panel_item *psdattr_rdtk, *psdattr_gdtk, *psdattr_bdtk;
extern Panel_item *psdattr_seq;
extern Panel_item *psdattr_cont, *psdattr_abort;

extern Window rasattr_frame;
extern Panel *rasattr_panel;
extern Panel_item *rasattr_fname;
extern Panel_item *rasattr_pixrep;
extern Panel_item *rasattr_orig;
extern Panel_item *rasattr_draw;
extern Panel_item *rasattr_seq;
extern Panel_item *rasattr_fg, *rasattr_bg;
extern Panel_item *rasattr_rfg, *rasattr_gfg, *rasattr_bfg;
extern Panel_item *rasattr_rbg, *rasattr_gbg, *rasattr_bbg;
extern Panel_item *rasattr_cont, *rasattr_abort;

extern Window textattr_frame;
extern Panel *textattr_panel;
extern Panel_item *textattr_name;
extern Panel_item *textattr_src;
extern Panel_item *textattr_text;
extern Panel_item *textattr_filenm;
extern Panel_item *textattr_font;
extern Panel_item *textattr_fontfamily;
extern Panel_item *textattr_fontsz;
extern Panel_item *textattr_size;
extern Panel_item *textattr_lead;
extern Panel_item *textattr_just;
extern Panel_item *textattr_path;
extern Panel_item *textattr_pathoffset, *textattr_letterspace;
extern Panel_item *textattr_fg;
extern Panel_item *textattr_rfg, *textattr_gfg, *textattr_bfg;
extern Panel_item *textattr_bgmode;
extern Panel_item *textattr_bg;
extern Panel_item *textattr_rbg, *textattr_gbg, *textattr_bbg;
extern Panel_item *textattr_hscale, *textattr_vscale;
extern Panel_item *textattr_rot;
extern Panel_item *textattr_clip;
extern Panel_item *textattr_dtk;
extern Panel_item *textattr_rdtk, *textattr_gdtk, *textattr_bdtk;
extern Panel_item *textattr_seq;
extern Panel_item *textattr_cont, *textattr_abort;

extern Window vecattr_frame;
extern Panel *vecattr_panel;
extern Panel_item *vecattr_name;
extern Panel_item *vecattr_linewd;
extern Panel_item *vecattr_lwidth;
extern Panel_item *vecattr_linestyle;
extern Panel_item *vecattr_dashstyle;
extern Panel_item *vecattr_dashlen, *vecattr_dashgaplen;
extern Panel_item *vecattr_dashpattern, *vecattr_dashoffset;
extern Panel_item *vecattr_capstyle;
extern Panel_item *vecattr_ptr, *vecattr_ptrstyle;
extern Panel_item *vecattr_ptrwd, *vecattr_ptrolen, *vecattr_ptrilen;
extern Panel_item *vecattr_fg;
extern Panel_item *vecattr_rfg, *vecattr_gfg, *vecattr_bfg;
extern Panel_item *vecattr_clip;
extern Panel_item *vecattr_dtk;
extern Panel_item *vecattr_rdtk, *vecattr_gdtk, *vecattr_bdtk;
extern Panel_item *vecattr_seq;
extern Panel_item *vecattr_mvloc1, *vecattr_mvloc2;
extern Panel_item *vecattr_cont, *vecattr_abort;

extern Window crvattr_frame;
extern Panel *crvattr_panel;
extern Panel_item *crvattr_name;
extern Panel_item *crvattr_linewd;
extern Panel_item *crvattr_lwidth;
extern Panel_item *crvattr_linestyle;
extern Panel_item *crvattr_dashstyle;
extern Panel_item *crvattr_dashlen, *crvattr_dashgaplen;
extern Panel_item *crvattr_dashpattern, *crvattr_dashoffset;
extern Panel_item *crvattr_capstyle;
extern Panel_item *crvattr_fg;
extern Panel_item *crvattr_rfg, *crvattr_gfg, *crvattr_bfg;
extern Panel_item *crvattr_clip;
extern Panel_item *crvattr_dtk;
extern Panel_item *crvattr_rdtk, *crvattr_gdtk, *crvattr_bdtk;
extern Panel_item *crvattr_seq;
extern Panel_item *crvattr_mvloc1, *crvattr_mvloc2;
extern Panel_item *crvattr_mvcnt1, *crvattr_mvcnt2;
extern Panel_item *crvattr_cont, *crvattr_abort;

extern Window mrkattr_frame;
extern Panel *mrkattr_panel;
extern Panel_item *mrkattr_name;
extern Panel_item *mrkattr_type;
extern Panel_item *mrkattr_size;
extern Panel_item *mrkattr_radius;
extern Panel_item *mrkattr_bndmode;
extern Panel_item *mrkattr_bndwd;
extern Panel_item *mrkattr_bwidth;
extern Panel_item *mrkattr_bndcolor;
extern Panel_item *mrkattr_rbnd, *mrkattr_gbnd, *mrkattr_bbnd;
extern Panel_item *mrkattr_fillmode;
extern Panel_item *mrkattr_fillcolor;
extern Panel_item *mrkattr_rfill, *mrkattr_gfill, *mrkattr_bfill;
extern Panel_item *mrkattr_hscale, *mrkattr_vscale;
extern Panel_item *mrkattr_rot;
extern Panel_item *mrkattr_clip;
extern Panel_item *mrkattr_dtk;
extern Panel_item *mrkattr_rdtk, *mrkattr_gdtk, *mrkattr_bdtk;
extern Panel_item *mrkattr_seq;
extern Panel_item *mrkattr_cont, *mrkattr_abort;

extern Window rectattr_frame;
extern Panel *rectattr_panel;
extern Panel_item *rectattr_name;
extern Panel_item *rectattr_bndmode;
extern Panel_item *rectattr_bndwd;
extern Panel_item *rectattr_bwidth;
extern Panel_item *rectattr_linestyle;
extern Panel_item *rectattr_dashstyle;
extern Panel_item *rectattr_dashlen, *rectattr_dashgaplen;
extern Panel_item *rectattr_dashpattern, *rectattr_dashoffset;
extern Panel_item *rectattr_bndcolor;
extern Panel_item *rectattr_rbnd, *rectattr_gbnd, *rectattr_bbnd;
extern Panel_item *rectattr_fillmode;
extern Panel_item *rectattr_fillcolor;
extern Panel_item *rectattr_rfill, *rectattr_gfill, *rectattr_bfill;
extern Panel_item *rectattr_dimmode;
extern Panel_item *rectattr_width, *rectattr_height;
extern Panel_item *rectattr_rot;
extern Panel_item *rectattr_clip;
extern Panel_item *rectattr_dtk;
extern Panel_item *rectattr_rdtk, *rectattr_gdtk, *rectattr_bdtk;
extern Panel_item *rectattr_seq;
extern Panel_item *rectattr_cont, *rectattr_abort;

extern Window polyattr_frame;
extern Panel *polyattr_panel;
extern Panel_item *polyattr_name;
extern Panel_item *polyattr_closure;
extern Panel_item *polyattr_bndmode;
extern Panel_item *polyattr_bndwd;
extern Panel_item *polyattr_bwidth;
extern Panel_item *polyattr_bndcolor;
extern Panel_item *polyattr_rbnd, *polyattr_gbnd, *polyattr_bbnd;
extern Panel_item *polyattr_fillmode;
extern Panel_item *polyattr_fillcolor;
extern Panel_item *polyattr_rfill, *polyattr_gfill, *polyattr_bfill;
extern Panel_item *polyattr_hscale, *polyattr_vscale;
extern Panel_item *polyattr_rot;
extern Panel_item *polyattr_clip;
extern Panel_item *polyattr_dtk;
extern Panel_item *polyattr_rdtk, *polyattr_gdtk, *polyattr_bdtk;
extern Panel_item *polyattr_seq;
extern Panel_item *polyattr_cont, *polyattr_abort;

extern Window axisattr_frame;
extern Panel *axisattr_panel;
extern Panel_item *axisattr_name;
extern Panel_item *axisattr_orig;
extern Panel_item *axisattr_term;
extern Panel_item *axisattr_linlog;
extern Panel_item *axisattr_div;
extern Panel_item *axisattr_axiswd;
extern Panel_item *axisattr_axiswidth;
extern Panel_item *axisattr_tickloc;
extern Panel_item *axisattr_ptickht;
extern Panel_item *axisattr_stickht;
extern Panel_item *axisattr_ttickht;
extern Panel_item *axisattr_tickwd;
extern Panel_item *axisattr_tickwidth;
extern Panel_item *axisattr_lin;
extern Panel_item *axisattr_rlin, *axisattr_glin, *axisattr_blin;
extern Panel_item *axisattr_fontloc;
extern Panel_item *axisattr_font;
extern Panel_item *axisattr_fontfamily;
extern Panel_item *axisattr_fontsz;
extern Panel_item *axisattr_fontsize;
extern Panel_item *axisattr_fontorient;
extern Panel_item *axisattr_fontoff;
extern Panel_item *axisattr_lab;
extern Panel_item *axisattr_rlab, *axisattr_glab, *axisattr_blab;
extern Panel_item *axisattr_clip;
extern Panel_item *axisattr_dtk;
extern Panel_item *axisattr_rdtk, *axisattr_gdtk, *axisattr_bdtk;
extern Panel_item *axisattr_seq;
extern Panel_item *axisattr_mvloc1, *axisattr_mvloc2;
extern Panel_item *axisattr_cont, *axisattr_abort;

extern Window cmpattr_frame;
extern Panel *cmpattr_panel;
extern Panel_item *cmpattr_name;
extern Panel_item *cmpattr_scale, *cmpattr_scaleattr;
extern Panel_item *cmpattr_rot;
extern Panel_item *cmpattr_cont, *cmpattr_abort;

extern Window pthattr_frame;
extern Panel *pthattr_panel;
extern Panel_item *pthattr_name;
extern Panel_item *pthattr_src, *pthattr_filenm;
extern Panel_item *pthattr_closure;
extern Panel_item *pthattr_vis;
extern Panel_item *pthattr_fg;
extern Panel_item *pthattr_rfg, *pthattr_gfg, *pthattr_bfg;
extern Panel_item *pthattr_cont, *pthattr_abort;

extern Window locattr_frame;
extern Panel *locattr_panel;
extern Panel_item *locattr_lab;
extern Panel_item *locattr_x, *locattr_y;
extern Panel_item *locattr_cont, *locattr_abort;

extern Window dmpips_frame;
extern Panel *dmpips_panel;
extern Panel_item *dmpips_filenm;
extern Panel_item *dmpips_mode;
extern Panel_item *dmpips_ras;
extern Panel_item *dmpips_cont, *dmpips_abort;

extern Window insice_frame;
extern Panel *insice_panel;
extern Panel_item *insice_filenm;
extern Panel_item *insice_pg;
extern Panel_item *insice_gdf;
extern Panel_item *insice_currobj, *insice_newobj;
extern Panel_item *insice_cont, *insice_abort;

extern int ice_op;

extern Grobj *grobjs;
extern int npsdocs, nrasters, ntexts;
extern int nvectors, ncurves, nmarkers;
extern int nrectangles, npolygons, naxes;
extern int unnamed_texts, unnamed_vectors, unnamed_curves, unnamed_markers;
extern int unnamed_rectangles, unnamed_polygons, unnamed_axes;

extern Composite *cmpobjs;

extern Pathdir *pathdirs;

extern Path *paths;
extern int npaths;
