#ifndef	gantt_HEADER
#define	gantt_HEADER

/*
 * gantt_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `gantt.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	ganttPopup;
	Xv_opaque	canvas;
} gantt_ganttPopup_objects;

extern gantt_ganttPopup_objects	*gantt_ganttPopup_objects_initialize(gantt_ganttPopup_objects *, Xv_opaque);

extern Xv_opaque	gantt_ganttPopup_ganttPopup_create(gantt_ganttPopup_objects *, Xv_opaque);
extern Xv_opaque	gantt_ganttPopup_canvas_create(gantt_ganttPopup_objects *, Xv_opaque);
#endif
