/*
 * xplan.h - Contains the object declarations for project xplan
 * This file was generated by `gxv'.
 */


#include "main_ui.h"
#include "file_ui.h"
#include "PERT_Xui.h"
#include "dependencies_ui.h"
#include "export_ui.h"
#include "gantt_Xui.h"
#include "resources_ui.h"
#include "taskinfo_ui.h"


extern	main_mainWindow_objects	*Main_mainWindow;
extern	file_filePopup_objects	*File_filePopup;
extern	PERT_pertPopup_objects	*PERT_pertPopup;
extern	dependencies_dependenciesPopup_objects	*Dependencies_dependenciesPopup;
extern	export_exportPopup_objects	*Export_exportPopup;
extern	gantt_ganttPopup_objects	*Gantt_ganttPopup;
extern	resources_resourcesPopup_objects	*Resources_resourcesPopup;
extern	taskinfo_taskinfoPopup_objects	*Taskinfo_taskinfoPopup;


#define LOAD (0)
#define SAVE (1)
int load_save_flag;
