#!/bin/sh
# zaehlt die Anzahl der Seiten, die von einem Sender gespeichert sind
# Achtung: Es darf nichts ueber stderr ausgegeben werden, 
# da sonst Tcl/tk mit einer Fehlermeldung abbricht 

# hier sind die Seiten in Directories gespeichert, die so heissen
# wie der Sender
videotextpfad=.
ls $videotextpfad/"$1"|wc -l
exit 0
