#!/bin/sh
# sendername, seitennummer und unterseitennummer muessen als Parameter 
# uebergeben werden.
# Der Text der Seite wird auf stdout ausgegeben
# Wenn die geforderte Seite nicht da ist, 
# wird "Seite nicht vorhanden" ausgegeben
# Achtung: Es darf nichts ueber stderr ausgegeben werden, 
# da sonst Tcl/tk mit einer Fehlermeldung abbricht 

# hier sind die Seiten in Directories gespeichert, die so heissen
# wie der Sender
videotextpfad=.
for i in $videotextpfad/"$1"/$2--$3-*
 do
   if [ -r "$i" ]
   then 
     cat "$i" 2>/dev/null |tr -d '\33'
     exit 0
   fi
 done

echo Seite nicht vorhanden
exit 0
