#!/bin/sh
# gibt eine Liste aller Sender (durch white-space getrennt) zurueck zu 
# denen Videotextseiten  abgespeichert sind
# Achtung: Es darf nichts ueber stderr ausgegeben werden, 
# da sonst Tcl/tk mit einer Fehlermeldung abbricht 

# hier sind die Seiten in Directories gespeichert, die so heissen
# wie der Sender
videotextpfad=.
cd $videotextpfad
for i in *
 do
  if [ -d "$i" ]
   then 
    echo "$i"
   fi
 done

exit 0
