/*  -------------------------------------------------------------------

This program is the property of:

                             Cornell University 
                        Center for Applied Mathematics 
                              Ithaca, NY 14853

and may be used, modified and distributed freely, subject to the 
following restrictions:

       Any product which incorporates source code from the dstool
       program or utilities, in whole or in part, is distributed
       with a copy of that source code, including this notice. You
       must give the recipients all the rights that you have with
       respect to the use of this software. Modifications of the
       software must carry prominent notices stating who changed
       the files and the date of any change.

DsTool is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of FITNESS 
FOR A PARTICULAR PURPOSE.  The software is provided as is without 
any obligation on the part of Cornell faculty, staff or students to 
assist in its use, correction, modification or enhancement.

  -----------------------------------------------------------------  */
#ifndef	cmd_HEADER
#define	cmd_HEADER

/*
 * cmd_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `cmd.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;

extern Xv_opaque	cmd_filemenu_create();
extern Xv_opaque	cmd_viewmenu_create();
extern Xv_opaque	cmd_panelmenu_create();
extern Xv_opaque	cmd_settingsmenu_create();
extern Xv_opaque	cmd_dscatmenu_create();
extern Xv_opaque	cmd_modelmenu_create();
extern Xv_opaque	cmd_bigmenu_create();

typedef struct {
	Xv_opaque	win;
	Xv_opaque	pan;
	Xv_opaque	modelbutton;
	Xv_opaque	modelname;
	Xv_opaque	file;
	Xv_opaque	view;
	Xv_opaque	panels;
	Xv_opaque	settings;
	Xv_opaque	stored_points;
	Xv_opaque	messages;
} cmd_win_objects;

extern cmd_win_objects	*cmd_win_objects_initialize();

extern Xv_opaque	cmd_win_win_create();
extern Xv_opaque	cmd_win_pan_create();
extern Xv_opaque	cmd_win_modelbutton_create();
extern Xv_opaque	cmd_win_modelname_create();
extern Xv_opaque	cmd_win_file_create();
extern Xv_opaque	cmd_win_view_create();
extern Xv_opaque	cmd_win_panels_create();
extern Xv_opaque	cmd_win_settings_create();
extern Xv_opaque	cmd_win_stored_points_create();
extern Xv_opaque	cmd_win_messages_create();
#endif
