.\" Copyright 1994 NEC Corporation, Tokyo, Japan.
.\"
.\" Permission to use, copy, modify, distribute and sell this software
.\" and its documentation for any purpose is hereby granted without
.\" fee, provided that the above copyright notice appear in all copies
.\" and that both that copyright notice and this permission notice
.\" appear in supporting documentation, and that the name of NEC
.\" Corporation not be used in advertising or publicity pertaining to
.\" distribution of the software without specific, written prior
.\" permission.  NEC Corporation makes no representations about the
.\" suitability of this software for any purpose.  It is provided "as
.\" is" without express or implied warranty.
.\"
.\" NEC CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN
.\" NO EVENT SHALL NEC CORPORATION BE LIABLE FOR ANY SPECIAL, INDIRECT OR
.\" CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
.\" USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
.\" OTHER TORTUOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
.\" PERFORMANCE OF THIS SOFTWARE.

.\" $Id: cpdic.man,v 1.2 1994/01/27 10:46:34 misao Exp $
.TH CPDIC 1
.SH "NAME"
cpdic \- User Dictionary Copy Tool
.SH "SYNOPSIS"
.B "cpdic [{\-cs|\-cannaserver} \fIcanna-server\fP] [\-i|\-u \fIuser-name\fP] \fIfrom-dic\fP \fIto-dic\fP"
.SH "DESCRIPTION"
.PP
cpdic copies user dictionary \fIfrom-dic\fP to \fIto-dic\fP to rewrite
dictionary directory file \(em dics.dir \(em .
.PP
If the user dictionary directory does not exist, cpdic creates it and
creates dics.dir under it.
.PP
If the \-i option is specified, the system dictionary will be copied.
If the \-u option is specified, another user dictionary will be copied.
.SH "OPTIONS"
.IP "\-cs \fIcanna-server\fP (or \-cannaserver \fIcanna-server\fP)" 12
.PP
Specifies the name of the server machine that contains a dictionary to
be copied.
.IP "\-i" 12
Copies the system dictionary.
.IP "\-u \fIuser-name\fP" 12
Copies the dictionary of the specified user.
.SH "SEE ALSO"
.PP
lsdic(1), mkdic(1), mvdic(1), rmdic(1)
