.TH RMDIC 1
.SH "NAME"
rmdic \- Tool for deleting a user dictionary 
.SH "SYNOPSIS"
.B "rmdic [{\-cs|\-cannaserver} \fIcanna-server\fP] \fIdicname1\fP [\fIdicname2\fP ...]\fP"
.SH "DESCRIPTION"
.PP
rmdic deletes the specified user dictionary (or dictionaries).  
Dictionary directory file \(em dics.dir \(em is rewritten correspondingly 
to this.
.PP
More than one user dictionary may be specified.
.PP
The dictionary in use (i.e., the currently mounted dictionary) cannot
be deleted.
.SH "OPTION"
.IP "\-cs \fIcanna-server\fP (or \-cannaserver \fIcanna-server\fP)" 12
Specifies the name of the server machine that contains the dictionary to 
be renamed. 
.SH "SEE ALSO"
.PP
cpdic(1), lsdic(1), mkdic(1), mvdic(1)

.\" Copyright 1994 NEC Corporation, Tokyo, Japan.
.\"
.\" Permission to use, copy, modify, distribute and sell this software
.\" and its documentation for any purpose is hereby granted without
.\" fee, provided that the above copyright notice appear in all copies
.\" and that both that copyright notice and this permission notice
.\" appear in supporting documentation, and that the name of NEC
.\" Corporation not be used in advertising or publicity pertaining to
.\" distribution of the software without specific, written prior
.\" permission.  NEC Corporation makes no representations about the
.\" suitability of this software for any purpose.  It is provided "as
.\" is" without express or implied warranty.
.\"
.\" NEC CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
.\" INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN 
.\" NO EVENT SHALL NEC CORPORATION BE LIABLE FOR ANY SPECIAL, INDIRECT OR
.\" CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF 
.\" USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR 
.\" OTHER TORTUOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR 
.\" PERFORMANCE OF THIS SOFTWARE. 
.\"
.\" $Id: rmdic.man,v 1.2 1994/01/27 09:51:11 kon Exp $
