;GIL-3
(
(
	:type                   :base-window
	:name                   baseFrame
	:owner                  nil
	:width                  679
	:height                 702
	:background-color       ""
	:foreground-color       ""
	:label                  "SoftQuad Licensing: Client Site Info"
	:label-type             :string
	:initial-state          :open
	:show-footer            t
	:resizable              nil
	:icon-file              "xgenlice.icon"
	:icon-label             "XGenLicense"
	:icon-mask-file         ""
	:event-handler          nil
	:user-data              ()
	:actions                ()
)
)
