.TH rconsole 1 "09 October 1993"
.SH NAME
rconsole - dumb but fast terminal emulator
.SH SYNOPSIS
.B rconsole
.RB [ -f
.IR font]
.RB [ -fb
.IR framebuffer ]
.RB [ -e
.I executable
.RI [ options ]]
.SH DESCRIPTION
.LP
.I Rconsole
runs in the raw console on a Sun.
It looks just like the raw console driver, only it goes a lot faster.
.SH OPTIONS
.TP
.B -f
Use the specified font.  The default is gallant19.
.TP
.B -fb
Use the specified framebuffer.  The default is /dev/fb.
.TP
.B -e
Runs the specified executable in
.IR rconsole ,
instead of starting a shell.
.SH AUTHOR
Tom Lawrence, Brown University.  Converted from libpixrect to libraster
by Craig Leres and Jef Poskanzer.
