.\" This file uses -man macros.
.\"
.TH EOS 1 "July 15, 1990" " "
.SH NAME
eos  \- Educational On-Line System Student Interface
.SH SYNOPSIS
.B eos
[
.B \-c
] [
.I filename ...
]
.\" Use the B, I, BR, or BI tags to show syntax.
.SH DESCRIPTION
.PP
The 
.I eos
program is an editor, using the full multi-media functionality
of EZ, which also allows students to turn in and pick up
papers, where papers can be assignments, handouts or papers
for general viewing (Exchange papers).
.PP
Complete documentation on eos is available
in the 
.B eos
andrew help page.
.SH "EXAMPLES"
.PP
eos
.PP
eos myfile.ez
.PP
eos \-c 21.780
.PP
eos -c 21.730 myfile.ez
.SH "OPTIONS"
.PP
\-c Specify the course to be used by eos as the argument
immediately
following the -c flag.
.SH "SEE ALSO"
.PP
ez(1),
ahelp(1)
