.\" This file uses -man macros.
.\"
.TH GRADE 1 "July 15, 1990" " "
.SH NAME
grade  \- Educational On-Line System Teacher Interface
.SH SYNOPSIS
.B grade
[
.B \-c
] [
.I filename ...
]
.\" Use the B, I, BR, or BI tags to show syntax.
.SH DESCRIPTION
.PP
.I Grade
is an andrew application which allows course instructors to
view assignments turned in by students,
edit and annotate the work
and to return it back to the
student. The instructor can also create
and review handouts for courses.
.PP
Complete documentation on the grade program is available
in the 
.B grade
andrew help page.
.SH "EXAMPLES"
.PP
grade
.PP
grade \-c 21.780
.SH "OPTIONS"
.PP
\-c Specify the course to be used by grade as the argument
immediately
following the -c flag.
.SH "SEE ALSO"
.PP
ez(1),
ahelp(1),
eos(1)
