.\" @(#)faces.1 1.2 88/12/11
.TH FACES 1L "2 December 1988"
.SH NAME
faces \- visual mail and print face server for the Sun workstation
.SH SYNOPSIS
.B "faces
[
.B \-P
.I printer
]
[
.B \-a
]
[
.B \-b
.I background
]
[
.B \-f
.I facedir
]
[
.B \-i
]
[
.B \-n
]
[
.B \-p
.I period
]
[
.B \-s
.I spoolfile
]
[
.B \-t
]
[
.B \-u
]
[
.B \-v
]
[
.B \-Wi
]
[
.B \-Wp
.I x y
]
[
.B \-WP
.I x y
]
.SH DESCRIPTION
.B faces
is a window based tool for monitoring mail or print queues. It contains
graphical interfaces for SunView and NeWS. It has three different modes
of operation:
.LP
The default will monitor for new mail. Only the last ten messages are
displayed. In its iconic form, it is also possible to display the timestamp
of each message, and the open window format can give the username.
.LP
The second choice is to monitor the whole of a mail file. The icon and open
window display the appropriate faces, and dynamically change size as a new
check is made and if the mail file has altered size. In the iconic form, a
timestamp of the last message plus the number of mail messages from this
person are optional display parameters.
.LP
The final option allows this program to monitor a given print queue.
This will generate a single face icon showing the job at the top of the print
queue, and a text message will display the number of messages to be printed.
Opening the window will show all the jobs in the queue with the owners' name
and the size of the job in bytes.
.LP
There are special displays for no mail, no faces found, no print jobs, and
no paper in the printer.
.LP
.B faces
is based on the AT&T v8 program
.B vismon.
This program is not derived from
.B vismon
source.
.LP
There is a special faces directory containing a fixed three-level hierarchy,
which by default is
.I /usr/local/faces.
The first level is a machine name, the second level a user name, and the
third level is the actual face image, which can be stored in three formats.
If the file is named
.I 48x48x1
then it is a Blit ikon, and if it is called
.I sun.icon
then the image is stored in Sun icon format, and if the file is named
.I face.ps
then it contains executable NeWS code.
.LP
To access the face for a mail name
.I machine!uid
take the result of the first successful open from the following list of files:
.LP
	/usr/local/faces/machine/uid/face.ps
.br
	/usr/local/faces/machine/uid/sun.icon
.br
	/usr/local/faces/machine/uid/48x48x1
.br
	/usr/local/faces/misc./uid/face.ps
.br
	/usr/local/faces/misc./uid/sun.icon
.br
	/usr/local/faces/misc./uid/48x48x1
.br
	/usr/local/faces/machine/unknown/face.ps
.br
	/usr/local/faces/machine/unknown/sun.icon
.br
	/usr/local/faces/machine/unknown/48x48x1
.br
	/usr/local/faces/misc./unknown/face.ps
.br
	/usr/local/faces/misc./unknown/sun.icon
.br
	/usr/local/faces/misc./unknown/48x48x1
.LP
The directory
.I misc.
hold faces for generic users such as
.I root
and
.I uucp.
.LP
Faces information is administered by a pair of ASCII files that associate
related machines and faces. The machine table
.I machine.tab
attaches machines to communities; the line
.LP
	stard=sunaus
.LP
puts the machine
.I stard
in community
.I sunaus.
The people table associates a community/alias pair, with a real username.
.LP
	sunaus/rburridge=richb
.LP
causes the alias
.I rburridge
to be translated into the real username
.I richb
for the community
.I sunaus
.LP
Domain name structure would be handled in the same way. For example:
.LP
	sunaus.sun.oz=sunaus
.LP
would map the full domain name in the community
.I sunaus.
.LP
If the faces directory hierarchy is not found, then a blank face image
will be used.
.LP
Note that you still need to use
.I mailtool
or some other mail reading utility to actually read the mail that this program
monitors;
.I faces
simply displays who the mail is from.
.LP
When new mail arrives,
.B faces
will beep and flash appropriately, depending upon the set parameters in
the users
.I .mailrc
file.
.LP
If you are using the NeWS version and creating face images of the
.I face.ps
form, then the following points should be noted:
.LP
	All graphics operations should be performed on the unit square.
.br
	The final image will be translated to a 64 x 64 square image at
.br
	the appropriate position in the faces display.
.br
.SH OPTIONS
.TP
.BI \-P " printer"
Printer name to monitor. If this and a mail spool file are given with the -s
option,
.B faces
will monitor the print queue.
.TP
.B \-a
Monitor the whole of the specified mail file. The icon and open window display
the appropriate faces, and dynamically change size as a new check is made and
if the mail file has altered size.
.TP
.BI \-b " background"
Sun icon file containing an alternate background pattern. The default is
root grey.
.TP
.BI \-f " facedir"
Use an alternate name for the faces directory. The default is
.BR /usr/local/faces .
.TP
.B \-i
Invert the faces images before displaying them. For use by people who
started SunView with the
.B \-i
option.
.TP
.B \-n
Do not display the number of messages from this person. The default is to
display, and a count is shown at the bottom right corner of the face for
this person.
.TP
.BI \-p " period"
The period in seconds before the mail spool file or the print queue is
scanned again for new mail. The default is 60 seconds.
.TP
.BI \-s " spoolfile"
Use an alternate mail spool file to monitor. The default is
.BI /var/spool/mail/ username
where
.I username
is the name of the user currently logged in.
.TP
.B \-t
Do not display a timestamp of the last message from this person. The
default is to display, and a timestamp is shown at the bottom left
corner of the face for this person.
.TP
.B \-u
Do not display the username on the face icon. The default is to display,
and the username will appear over the face icon, when the window is
opened.
.TP
.B \-v
Print the version number of this release of the
.B faces
program.
.TP
.B \-Wi
Start the
.B faces
program up in iconic form. SunView automatically uses this flag, but the
NeWS version will also.
.TP
.BI \-Wp " x y"
Start the open window position at
.I x y
.TP
.BI \-WP " x y"
Start the icon position at
.I x y
.SH FILES
.TP
.B /var/spool/mail
directory for system mailboxes
.TP
.B /.mailrc
mail startup file
.TP
.B /usr/local/faces
main directory containing the face icons.
.TP
.B /usr/local/faces/people.tab
people/file equivalences
.TP
.B /usr/local/faces/machine.tab
machine/community equivalences
.SH BUGS
The machine and people table lookup is hopelessly inefficient and
will need to be improved as the faces database gets larger.
.br
If the window/icon for the NeWS version is moved, then the window or
icon is redrawn at the original position.
.SH AUTHOR
Rich Burridge,        DOMAIN: richb@sunaus.oz.au
.nf
PHONE: +61 2 413 2666   UUCP:   {uunet,mcvax,ukc}!munnari!sunaus.oz!richb
.fi
