/*
 * yamailt_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `yamailt.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "yamailt_ui.h"


/*
 * Global object definitions.
 */
yamailt_baseWindow_objects	*Yamailt_baseWindow;
yamailt_compWindow_objects	*Yamailt_compWindow;
yamailt_sendPopup_objects	*Yamailt_sendPopup;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(int argc, char **argv)
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Yamailt_baseWindow = yamailt_baseWindow_objects_initialize(NULL, NULL);
	Yamailt_compWindow = yamailt_compWindow_objects_initialize(NULL, NULL);
	Yamailt_sendPopup = yamailt_sendPopup_objects_initialize(NULL, Yamailt_compWindow->compWindow);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Yamailt_baseWindow->baseWindow);
	exit(0);
}

#endif


