/*
 * yamailt_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `yamailt.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "yamailt_ui.h"

/*
 * Initialize an instance of object `baseWindow'.
 */
yamailt_baseWindow_objects *
yamailt_baseWindow_objects_initialize(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (yamailt_baseWindow_objects *) calloc(1, sizeof (yamailt_baseWindow_objects))))
		return (yamailt_baseWindow_objects *) NULL;
	if (!ip->baseWindow)
		ip->baseWindow = yamailt_baseWindow_baseWindow_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = yamailt_baseWindow_controls1_create(ip, ip->baseWindow);
	if (!ip->fileButton)
		ip->fileButton = yamailt_baseWindow_fileButton_create(ip, ip->controls1);
	if (!ip->viewButton)
		ip->viewButton = yamailt_baseWindow_viewButton_create(ip, ip->controls1);
	if (!ip->editButton)
		ip->editButton = yamailt_baseWindow_editButton_create(ip, ip->controls1);
	if (!ip->composeButton)
		ip->composeButton = yamailt_baseWindow_composeButton_create(ip, ip->controls1);
	if (!ip->setting1)
		ip->setting1 = yamailt_baseWindow_setting1_create(ip, ip->controls1);
	if (!ip->prevButton)
		ip->prevButton = yamailt_baseWindow_prevButton_create(ip, ip->controls1);
	if (!ip->nextButton)
		ip->nextButton = yamailt_baseWindow_nextButton_create(ip, ip->controls1);
	if (!ip->deleteButton)
		ip->deleteButton = yamailt_baseWindow_deleteButton_create(ip, ip->controls1);
	if (!ip->replyButton)
		ip->replyButton = yamailt_baseWindow_replyButton_create(ip, ip->controls1);
	if (!ip->button9)
		ip->button9 = yamailt_baseWindow_button9_create(ip, ip->controls1);
	if (!ip->button10)
		ip->button10 = yamailt_baseWindow_button10_create(ip, ip->controls1);
	if (!ip->button11)
		ip->button11 = yamailt_baseWindow_button11_create(ip, ip->controls1);
	if (!ip->list1)
		ip->list1 = yamailt_baseWindow_list1_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `baseWindow' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_baseWindow_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 520,
		XV_HEIGHT, 300,
		XV_LABEL, "Yet Another Mail Tool",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_controls1_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `fileButton' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_fileButton_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_LABEL_STRING, "File",
		NULL);
	return obj;
}

/*
 * Create object `viewButton' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_viewButton_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 80,
		XV_Y, 8,
		PANEL_LABEL_STRING, "View",
		NULL);
	return obj;
}

/*
 * Create object `editButton' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_editButton_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 152,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Edit",
		NULL);
	return obj;
}

/*
 * Create object `composeButton' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_composeButton_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 216,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Compose",
		NULL);
	return obj;
}

/*
 * Create object `setting1' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_setting1_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 304,
		XV_Y, 8,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, "Setting:",
		PANEL_CHOICE_STRINGS,
			"Choice",
			"Choice",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `prevButton' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_prevButton_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 32,
		PANEL_LABEL_STRING, "Previous",
		NULL);
	return obj;
}

/*
 * Create object `nextButton' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_nextButton_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 80,
		XV_Y, 32,
		PANEL_LABEL_STRING, "Next",
		NULL);
	return obj;
}

/*
 * Create object `deleteButton' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_deleteButton_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 152,
		XV_Y, 32,
		PANEL_LABEL_STRING, "Delete",
		NULL);
	return obj;
}

/*
 * Create object `replyButton' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_replyButton_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 232,
		XV_Y, 32,
		PANEL_LABEL_STRING, "Reply",
		NULL);
	return obj;
}

/*
 * Create object `button9' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_button9_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 304,
		XV_Y, 32,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Create object `button10' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_button10_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 368,
		XV_Y, 32,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Create object `button11' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_button11_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 432,
		XV_Y, 32,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Create object `list1' in the specified instance.
 */
Xv_opaque
yamailt_baseWindow_list1_create(yamailt_baseWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 56,
		PANEL_LIST_WIDTH, 500,
		PANEL_LIST_DISPLAY_ROWS, 11,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `compWindow'.
 */
yamailt_compWindow_objects *
yamailt_compWindow_objects_initialize(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (yamailt_compWindow_objects *) calloc(1, sizeof (yamailt_compWindow_objects))))
		return (yamailt_compWindow_objects *) NULL;
	if (!ip->compWindow)
		ip->compWindow = yamailt_compWindow_compWindow_create(ip, owner);
	if (!ip->controls2)
		ip->controls2 = yamailt_compWindow_controls2_create(ip, ip->compWindow);
	if (!ip->button12)
		ip->button12 = yamailt_compWindow_button12_create(ip, ip->controls2);
	if (!ip->button13)
		ip->button13 = yamailt_compWindow_button13_create(ip, ip->controls2);
	if (!ip->button14)
		ip->button14 = yamailt_compWindow_button14_create(ip, ip->controls2);
	if (!ip->button15)
		ip->button15 = yamailt_compWindow_button15_create(ip, ip->controls2);
	if (!ip->button16)
		ip->button16 = yamailt_compWindow_button16_create(ip, ip->controls2);
	if (!ip->toTextfield)
		ip->toTextfield = yamailt_compWindow_toTextfield_create(ip, ip->controls2);
	if (!ip->subjectTextfield)
		ip->subjectTextfield = yamailt_compWindow_subjectTextfield_create(ip, ip->controls2);
	if (!ip->ccTextfield)
		ip->ccTextfield = yamailt_compWindow_ccTextfield_create(ip, ip->controls2);
	if (!ip->group1)
		ip->group1 = yamailt_compWindow_group1_create(ip, ip->controls2);
	if (!ip->message1)
		ip->message1 = yamailt_compWindow_message1_create(ip, ip->controls2);
	if (!ip->button17)
		ip->button17 = yamailt_compWindow_button17_create(ip, ip->controls2);
	if (!ip->button18)
		ip->button18 = yamailt_compWindow_button18_create(ip, ip->controls2);
	window_fit(ip->controls2);
	
	window_fit(ip->compWindow);
	
	xv_set(ip->controls2,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `compWindow' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_compWindow_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 532,
		XV_HEIGHT, 477,
		XV_LABEL, "Yet Another Mail Tool - Compose/Reply",
		XV_SHOW, TRUE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls2' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_controls2_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `button12' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_button12_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 8,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Create object `button13' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_button13_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 80,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Create object `button14' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_button14_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 152,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Create object `button15' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_button15_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 224,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Create object `button16' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_button16_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 296,
		XV_Y, 8,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Create object `toTextfield' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_toTextfield_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 32,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "To:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `subjectTextfield' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_subjectTextfield_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 56,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Subject:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `ccTextfield' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_ccTextfield_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 80,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Cc:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `group1' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_group1_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 32,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->toTextfield,
			ip->subjectTextfield,
			ip->ccTextfield,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `message1' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_message1_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 24,
		XV_Y, 104,
		PANEL_LABEL_STRING, "Message",
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `button17' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_button17_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 112,
		XV_Y, 392,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Create object `button18' in the specified instance.
 */
Xv_opaque
yamailt_compWindow_button18_create(yamailt_compWindow_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 192,
		XV_Y, 392,
		PANEL_LABEL_STRING, "Button",
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `sendPopup'.
 */
yamailt_sendPopup_objects *
yamailt_sendPopup_objects_initialize(yamailt_sendPopup_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (yamailt_sendPopup_objects *) calloc(1, sizeof (yamailt_sendPopup_objects))))
		return (yamailt_sendPopup_objects *) NULL;
	if (!ip->sendPopup)
		ip->sendPopup = yamailt_sendPopup_sendPopup_create(ip, owner);
	if (!ip->controls3)
		ip->controls3 = yamailt_sendPopup_controls3_create(ip, ip->sendPopup);
	if (!ip->stdSetting)
		ip->stdSetting = yamailt_sendPopup_stdSetting_create(ip, ip->controls3);
	if (!ip->whichKeySetting)
		ip->whichKeySetting = yamailt_sendPopup_whichKeySetting_create(ip, ip->controls3);
	if (!ip->encSetting)
		ip->encSetting = yamailt_sendPopup_encSetting_create(ip, ip->controls3);
	return ip;
}

/*
 * Create object `sendPopup' in the specified instance.
 */
Xv_opaque
yamailt_sendPopup_sendPopup_create(yamailt_sendPopup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 590,
		XV_HEIGHT, 144,
		XV_LABEL, "Send Options",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls3' in the specified instance.
 */
Xv_opaque
yamailt_sendPopup_controls3_create(yamailt_sendPopup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `stdSetting' in the specified instance.
 */
Xv_opaque
yamailt_sendPopup_stdSetting_create(yamailt_sendPopup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 16,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Mail Format:",
		PANEL_CHOICE_STRINGS,
			"RFC-822 (UNIX)",
			"Sun Mailtool (OWV3)",
			"MIME (New format)",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `whichKeySetting' in the specified instance.
 */
Xv_opaque
yamailt_sendPopup_whichKeySetting_create(yamailt_sendPopup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 260,
		XV_Y, 60,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, "Using key:",
		PANEL_CHOICE_STRINGS,
			"My Public Key",
			"My Private Key",
			"Sender's Public Key",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `encSetting' in the specified instance.
 */
Xv_opaque
yamailt_sendPopup_encSetting_create(yamailt_sendPopup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 64,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Encryption?",
		PANEL_CHOICE_STRINGS,
			"Cleartext",
			"PKC",
			NULL,
		NULL);
	return obj;
}

