.TH squig 1 "09 October 1993"
.SH NAME
squig - draw a squiggly tubular pattern
.SH SYNOPSIS
.B squig
.SH DESCRIPTION
.LP
.I Squig
displays pretty moving colorful splines on a Sun.
.SH "SEE ALSO"
spf3(1)
.SH AUTHOR
Copyright (C) 1990, 1993 by Jef Poskanzer <jef@netcom.com>.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
