#include <stdio.h>
char *tran_table[] = {
"translation  TOPS20",
"type	     TOPS20",
"system_note  A Dec 20 running the TOPS20 operating system.",
"no_pwd	    ",
"up_exp	     ^([A-Za-z0-9]+:<[A-Za-z\\.0-9_-]+)\\.[A-Za-z0-9_-]+>$",
"	     \\1>",
"cd_exp       ^([A-Za-z0-9_-]+:<[A-Za-z\\.0-9_-]+)>$",
"	     \\1.%s>",
"remote	     upper",
"local	     lower",
"listing_l    size(12) date(10) time(10) name",
"listing_m    size(12) name",
"convert_size ^([0-9]+)",
"	     \\1*512",
"dir_name     ^([A-Z0-9a-z_-]+:<[A-Za-z\\.0-9_-]+>)",
"size	     ^ *([0-9]+)\\([0-9]+\\)",
"date	     ([0-9]+\\-[A-Za-z][A-Za-z][A-Za-z]\\-[0-9]+)",
"time	     ([0-9][0-9]:[0-9][0-9]:[0-9][0-9])",
"name         ([A-Za-z0-9_,$-]+\\.[A-Za-z0-9_,$-]*\\.[0-9]+) ",
"isdir name   [A-Za-z0-9_,$-]+\\.DIRECTORY\\.[0-9]+",
"dir          ([A-Za-z0-9_,$-]+)\\.DIRECTORY\\.[0-9]+",
"	     \\1",
"examples_r   XX.TAR_Z;5",
"examples_r   XX.TAR_Z;3",
"examples_r   XX.TAR-Z;4",
"unix	     ^([A-Za-z0-9_,\\$-]+)\\.tar[_-]z.[0-9]+$",
"	     \\1.tar.Z tenex",
"examples_r   ACCOUNTS.TXT.5",
"examples_r   BOOSTRAP.HELP.5",
"examples_r   BINTNXVMS.README.2",
"examples_r   SIMTILE20-VHDL.INFO.1",
"examples_r   SIMTEL20-MSDOS.DIRLIST.67",
"examples_r   BINTNXVMS.C.1",
"unix	     ^([A-Za-z0-9_,$-]+)\\.(txt|help|readme|vhdl|dirlist|info)\\.[0-9]+",
"	     \\1.\\2 ascii",
"unix	     ^([A-Za-z0-9_,$-]+\\.[A-Za-z0-9_,$-]+)\\.1",
"	     \\1 ascii",
"unix	     ^([A-Za-z0-9_,$-]+\\.[A-Za-z0-9_,$-]+)\\.[0-9]+",
"	     \\1.\\2 ascii",
"end",
"translation  NOS/VE",
"system_note  A Cyber running the NOS/VE operating system.",
"guess	     B507",
"guess_cwd    NOS/VE",
"up	     $UP",
"listing_l    size(10) name",
"listing_m    size(10) name",
"name	     ^[ 	]+([A-Za-z0-9$_-]+)",
"size	     ([0-9,]+)",
"p1	     (.*)",
"convert_size ([0-9,]+)",
"	     \\1",
"isdir p1     (bytes* in [0-9]+ files* and [0-9]+ catalogs*|bytes* in [0-9]+ files*|bytes in [0-9]+ catalogs*)",
"dir	     (.*)",
"	     \\1",
"examples_r   fonst_image_hqx",
"unix         ^([A-Za-z0-9_$-]*)_(hpx|tar)$",
"	     \\1_\\2 binary",
"unix         ^([A-Za-z0-9_$-]*)$",
"	     \\1",
"examples_u   xftp.tar",
"back         ^([A-Za-z0-9_$-]*)\\.(tar|gif)$",
"	     \\1_\\2 binary",
"examples_u   xftp.tar.Z",
"back         ^([A-Za-z0-9_$-]*)\\.(tar|gif).Z$",
"	     \\1_\\2_Z binary",
"back  	     (.*)",
"	     \\1",
"end ",
"translation  VM",
"system_note  An IBM running the VM operating system.",
"type	     VM",
"listing_l    name(-17) p1(1) size(25) date(9) time(9)",
"listing_m    name(-17) p1(1) size(25)",
"remote	     lower",
"local	     lower",
"convert_size ^([0-9]+) +([0-9]+) +([0-9]+)$",
"	     \\1*\\2",
"name	     ([A-Za-z0-9\\$_-]+ +[A-Za-z0-9\\$_-]+)",
"p1	     ([A-Za-z0-9\\$_-]+)",
"size	     ([0-9]+ +[0-9]+ +[0-9])",
"date	     ([0-9]+/[0-9]+/[0-9]+)",
"time	     ([0-9][0-9]:[0-9][0-9]:[0-9][0-9])",
"rewrite	     ^([A-Za-z0-9\\$_-]+) +([A-Za-z0-9\\$_-]+)$",
"	     \\1.\\2",
"unix         ^([A-Za-z0-9\\$_-]+) +([A-Za-z0-9\\$_-]+)$",
"	     \\1.\\2",
"back  	     ^([A-Za-z0-9$_-]+\\.[A-Za-z0-9\\$_-]+)$",
"	     \\1.\\2",
"back  	     ^([A-Za-z0-9$-_]+)$",
"	     \\1",
"end ",
"translation  VMS",
"system_note  A Dec VAX running the VMS operating system.",
"type	     VMS",
"up	     -",
"indent       hanging",
"remote	     upper",
"local	     lower",
"listing_l    date(11) time(9) size(9) prot(25) name",
"listing_m    date(11) time(9) size(9) name",
"convert_size ^([0-9]+)",
"	     \\1*512",
"name         ([A-Za-z0-9_\\$-]+\\.[A-Za-z0-9_\\$-]*;[0-9]+) ",
"date	     ([0-9][0-9]*\\-[A-Z][A-Z][A-Z]\\-[0-9][0-9]*)",
"time	     ([0-9][0-9]:[0-9][0-9]:[0-9][0-9])",
"size	     ([0-9][0-9]*)\\/[0-9][0-9]*",
"prot	     (\\([A-Z\\,][A-Z\\,]*\\))",
"isdir name   [A-Za-z0-9_\\$-][A-Za-z0-0_\\$-]*\\.DIR;[0-9][0-9]*",
"dir          ([A-Za-z0-9_\\$-]+)\\.DIR;[0-9]+",
"	     \\1",
"use_other    VMS MULTINET",
"end ",
"translation  VMS MULTINET",
"system_note  A Dec VAX running the VMS operating system",
"guess	     MultiNet",
"notype	     ",
"indent       hanging",
"remote	     upper",
"local	     lower",
"up	     -",
"listing_l    date(11) time(5) size(8) prot(25) name",
"listing_m    date(11) time(5) size(8) name",
"convert_size ^([0-9]+)",
"	     \\1*512",
"name         ([A-Za-z0-9_,\\$-]+\\.[A-Za-z0-9_,\\$-]*;[0-9]+) ",
"size	     ([0-9]+)",
"date	     ([0-9]+\\-[A-Z][A-Z][A-Z]\\-[0-9]+)",
"time	     ([0-9][0-9]:[0-9][0-9])",
"owner	     (\\[[A-Za-z0-9_,$-]+\\]|[A-Za-z0-9_,$-]+)",
"prot	     (\\([A-Z\\,]+\\))",
"isdir name   [A-Za-z0-9_,\\$-]+\\.DIR;[0-9]+",
"dir          ([A-Za-z0-9_,\\$-]+)\\.DIR;[0-9]+",
"	     \\1",
"examples_r   BIN.DIR;1",
"unix         ([A-Za-z0-9_,\\$-]+)\\.dir;[0-9]+",
"	     \\1",
"examples_r   XX-TAR.Z;12",
"unix	     ^([A-Za-z0-9_,\\$-]+)\\-tar\\.z;[0-9]+$",
"	     \\1.tar.Z binary",
"examples_r   XX.TAR;1",
"examples_r   XX.TAR;12",
"unix	     ^([A-Za-z0-9_,\\$-]+)\\.tar;[0-9]+$",
"	     \\1.tar binary",
"examples_r   XX_TAR.;12",
"unix	     ^([A-Za-z0-9_,\\$-]+)_tar\\.*;[0-9]+$",
"	     \\1.tar binary",
"examples_r   XX_TAR_Z.;5	",
"examples_r   XX-TAR_Z.;3	",
"examples_r   XX-TAR-Z.;4",
"unix	     ^([A-Za-z0-9_,\\$-]+)[_-]tar[_-]z\\.*;[0-9]+$",
"	     \\1.tar.Z binary",
"examples_r   XX.TAR_Z;5	",
"examples_r   XX.TAR_Z;3	",
"examples_r   XX.TAR-Z;4",
"unix	     ^([A-Za-z0-9_,\\$-]+)\\.tar[_-]z;[0-9]+$",
"	     \\1.tar.Z binary",
"examples_r   XX-1.2-TAR-Z;4",
"unix	     ^([A-Za-z0-9_,\\$-]+)\\.([A-Za-z0-9_,\\$-]+)[_-]tar[_-]z;[0-9]+$",
"	     \\1.\\2.tar.Z binary",
"examples_r   XX.Z;6",
"examples_r   XX_Z.;6",
"examples_r   XX-Z.;6",
"unix	     ^([A-Za-z0-9_,\\$-]+)[\\._-]z\\.*;[0-9]+$",
"	     \\1.Z binary",
"examples_r   AAREADME.TXT:1",
"examples_r   HORSEHEAD.GIF;3",
"examples_r   NORTHAMERICA.TIFF;1 ",
"examples_r   OBSRVE.EXE;1 ",
"examples_r   SMUZSRC.ZIP:4",
"examples_u   NCSASRC.ARC;1",
"examples_u   TACACS010.BCK;4",
"examples_u   EDIT.OBJ;5",
"unix	     ^([A-Za-z0-9_,\\$-]+)\\.(gif|tiff|exe|zip|arc|bck|obj);[0-9]+$",
"	     \\1.\\2 binary",
"examples_r   XX.YYY;100",
"unix         ^([A-Za-z0-9_,\\$-]+)\\.([A-Za-z0-9_,\\$-]+);[0-9]+$",
"	     \\1.\\2 ascii",
"examples_r   XX.;55",
"unix         ^([A-Za-z0-9_,\\$-]+)\\.;[0-9]+$",
"	     \\1 ascii",
"examples_u   xftp.tar.Z",
"examples_u   horsehead.gif.Z",
"examples_u   observe.exe.Z",
"examples_u   northamerica.tiff.Z",
"back	     ^([A-Za-z0-9_,\\$-]+)\\.(TAR|GIF|TIFF|ZIP|EXE).Z$",
"	     \\1_\\2.Z binary",
"examples_u   hash.o",
"back	     ^([A-Za-z0-9_,\\$-]+)\\.O$",
"	     \\1.O binary",
"examples_u   Wcl.1.06.tar",
"back	     ^([A-Za-z0-9_,\\$-]+)\\.([0-9]+)\\.([0-9]+)\\.TAR",
"	     \\1-\\2.\\2-TAR binary",
"examples_u   Wcl.1.06.tar.Z",
"back	     ^([A-Za-z0-9_,\\$-]+)\\.([0-9]+)\\.([0-9]+)\\.TAR\\.Z",
"	     \\1-\\2.\\2-TAR-Z binary",
"examples_u   xx-1.2.tar.Z",
"examples_u   xx_1.2.tar.Z",
"back	     ^([A-Za-z0-9_,\\$-]+)[_-]([0-9]*).([0-9]*)\\.(TAR|GIF|TIFF|ZIP|EXE).Z$",
"	     \\1-\\2.\\3-\\4-Z binary",
"examples_u   xftp.tar",
"examples_u   horsehead.gif",
"examples_u   observe.exe",
"examples_u   northamerica.tiff ",
"examples_u   ncsarc.arc",
"examples_u   field.obj",
"examples_u   xterm.bck",
"back	     ^([A-Za_z0-9_,\\$-]+)\\.(TAR|GIF|TIFF|ZIP|EXE|ARC|OBJ|BCK)$",
"	     \\1.\\2 binary",
"examples_u   xftp.xxxx",
"back  	     ^([A-Za-z0-9_,\\$-]+)\\.([A-Za-z0-9_,\\$-]+)$ ",
"	     \\1.\\2 ascii",
"examples_u   xftp ",
"back	     ^([A-Za-z0-9_,\\$-]+)$ ",
"	     \\1 ascii",
"end ",
"translation  VMS CMU-TEK",
"system_note  A Dec VAX running the VMS operating system.",
"guess	     CMU-Tek FTP",
"notype	     ",
"remote	     upper",
"local	     lower",
"up	     [-]",
"listing_l    date(11) time(5) size(8) name",
"listing_m    size(8) name",
"convert_size ^([0-9]+)",
"	     \\1*512",
"name         [A-Za-z0-9_,$-]+:\\[[A-Za-z0-9_,$\\.-]+\\]([A-Za-z0-9_,$-]+\\.[A-Za-z0-9_,$-]*;[0-9]+) ",
"size	     ([0-9][0-9]*)\\/[0-9][0-9]*",
"date	     ([0-9]+\\-[A-Z][A-Z][A-Z]\\-[0-9]+)",
"time	     ([0-9][0-9]:[0-9][0-9])",
"dir          ([A-Za-z0-9_,\\$-]+)\\.DIR;[0-9]+",
"	     [.\\1]",
"isdir name   [A-Za-z0-9_,\\$-]+\\.DIR;[0-9]+",
"use_other    VMS MULTINET",
"end",
"translation  VMS CMU-IP",
"system_note  A Dec VAX running the VMS operating system.",
"guess	     CMU/VMS-IP",
"notype	     ",
"remote	     upper",
"local	     lower",
"up	     [-]",
"listing_l    date(11) time(5) size(8) name",
"listing_m    size(8) name",
"convert_size ^([0-9]+)",
"	     \\1*512",
"name         ([A-Za-z0-9_,$-]+\\.[A-Za-z0-9_,$-]*;[0-9]+)",
"size	     ([0-9][0-9]*)\\/[0-9][0-9]*",
"date	     ([0-9]+\\-[A-Z][A-Z][A-Z]\\-[0-9]+)",
"time	     ([0-9][0-9]:[0-9][0-9])",
"dir          ([A-Za-z0-9_,\\$-]+)\\.DIR;[0-9]+",
"	     [.\\1]",
"isdir name   [A-Za-z0-9_,\\$-]+\\.DIR;[0-9]+",
"use_other    VMS MULTINET",
"end",
"translation  UT2D",
"system_note  A Cyber system running the UT2D operating system.",
"type	     UT2D",
"init	     quote cwd  :DPC",
"remote	     upper",
"local	     lower",
"listing_l    name(-16) p1(5) size(11) time(9) date(9)",
"listing_m    name(-16) size(11)",
"convert_size ^([0-9]+)",
"	     \\1*480",
"name         (^ *[A-Z0-9]+ */[A-Z0-9]+|^ */[A-Z0-9]+|^ +[A-Z0-9]+) ",
"p1	     ([0-9]+)",
"size	     ([0-9]+)",
"time	     ([0-9][0-9]\\.[0-9][0-9]\\.[0-9][0-9]\\.)",
"date	     ([0-9][0-9] [A-Z][A-Z][A-Z] [0-9][0-9])",
"rewrite	     ([A-Z0-9]+) +/([A-Z0-9]+)",
"	     \\1/\\2",
"rewrite	     /([A-Z0-9]+)",
"	     \\1",
"rewrite	     ([a-z0-9/]+)",
"	     \\1",
"unix         ([a-z0-9]+) */([a-z0-9]+)",
"	     \\1.\\2",
"unix         [ ]*/([a-z0-9]+)",
"	     \\1",
"unix         ([a-z0-9]+)",
"	     \\1",
"back  	     (^[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]|^[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]|^[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]|^[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]|^[A-Za-z9][A-Za-z0-9][A-Za-z0-9]|^[A-Za-z][A-Za-z0-9]|^[A-Za-z])\\.([A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]$|[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]$|[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]$|[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]$|[A-Za-z9][A-Za-z0-9][A-Za-z0-9]$|[A-Za-z][A-Za-z0-9]$|[A-Za-z]$)",
"	     \\1/\\2",
"back  	     (^[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]$|^[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]$|^[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]$|^[A-Za-z][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]$|^[A-Za-z9][A-Za-z0-9][A-Za-z0-9]$|^[A-Za-z][A-Za-z0-9]$|^[A-Za-z]$)",
"	     \\1",
"end",
"translation  UNIX",
"system_note  Sum box running a version of the unix operating system.",
"guess	     (Ultrix",
"guess	     (ULTRIX",
"guess	     SunOS",
"guess	     Tahoe",
"guess	     UNIX",
"guess	     ftpd.c",
"guess	     FTP server (IG",
"guess	     FTP server (IRIX",
"guess        FTP server (Version",
"type	     UNIX",
"isunix",
"end",
"translation  IBM RT",
"system_note  IBM RT",
"guess	     (IBM RT)",
"type	     IBM RT",
"isibmrt",
"end",
"translation  Apollo",
"system_note  A Apollo system ",
"guess	     Apollo",
"type	     Apollo",
"isapollo",
"end",
"translation  AIX/370",
"system_note  A AIX/370 system (UNIX)",
"type	     AIX/370",
"isunix",
"end",
NULL,
};
