.\" $NCDId: @(#)auwave.man,v 1.3 1994/06/01 17:38:07 greg Exp $
.TH AUWAVE 1 "" ""
.SH NAME
auwave \- demonstrates the use of waveforms
.IX auwave#(1) "" "\fLauwave\fP(1)"
.SH SYNOPSIS
\fBauwave\fP [\fB\-audio\fP \fIservername\fP]
.SH DESCRIPTION
\fIauwave\fP demonstrates the use of waveform elements.  The user can
interactively select any waveform supported by the server and control its
frequency and volume.  Additionally, the gain of the output device can be
modified.
.SH AUWAVE AND THE ATHENA WIDGET SET
\fIauwave\fP uses the X Toolkit Intrinsics and the Athena Widget Set.
For more information, see the Athena Widget Set documentation.
.SH ENVIRONMENT
In addition to the standard toolkit environment variables, the
following environment variables are used by \fIauwave\fP:
.IP \fBAUDIOSERVER\fP 8
This variable specifies the default audio server to contact if \fI\-audio\fP
is not specified on the command line.  If this variable is not set and
the \fI\-audio\fP is not specified on the command line, \fIauwave\fP
will attempt to connect to the audio server running on the
X Window System display.
.SH "SEE ALSO"
nas(1), X(1)
.SH COPYRIGHT
Copyright 1993 Network Computing Devices, Inc.
.SH AUTHOR
Greg Renda, Network Computing Devices, Inc.
