# This file is generated by `guide' for project `ExampleTool.P'.
# It is to be included by the Makefile for project `ExampleTool.P'.

SOURCES.G += BaseWindow.G PropertyWindow.G CommandWindow.G 
STUBS.G += BaseWindow.G PropertyWindow.G CommandWindow.G 
