.TH ahs 1 "Release 1"  "AF Version 3"
.SH NAME
ahs - An AF hookswitch control client.
.SH SYNOPSIS
.B
ahs 
[\fI{on, off}\fP] 
.SH DESCRIPTION
.PP
\fIahs\fP 
allows you to manipulate the hookswitch on the phone device or 
determine the current state of the hookswitch.
.SH OPTIONS
.TP
.B \-d \fId\fP
.IP 
Specifies which audio device to use as the phone device.
If this parameter is not specified, \fIahs\fP defaults to device 0.
.TP
.B [\fI{on, off}\fP]
.IP
The hookswitch will be placed in the state specified by
this argument.
If no argument is given, \fIahs\fP prints the current state of the
hookswitch.
.SH ENVIRONMENT
.TP 15
.B AUDIOFILE
specifies the host and server to use.
.SH BUGS
If you encounter a \fBreproducible\fP bug, please submit a problem report to 
(af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1), aphone(1)
.SH COPYRIGHT
Copyright 1992-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Digital Cambridge Research Lab
