.TH aphone 1 "Release 1"  "AF Version 3"
.SH NAME
aphone - An AF phone dialer client.
.SH SYNOPSIS
.B
aphone 
[\fInumber\fP] 
.SH DESCRIPTION
.PP
\fIaphone\fP 
allows you to dial the phone.
.SH Options
.TP
.B \-d \fId\fP
.IP 
Specifies which audio device to use as the phone device.
If this parameter is not specified, \fIaphone\fP defaults to device 0.
.TP
.B \-af \fIserver\fP
.IP 
Specifies which audio server to use.
If this parameter is not specified, \fIaphone\fP defaults to the value
of the AUDIOFILE variable..
.TP
.B [\fInumber\fP]
.IP
Dials the number specified. Valid characters in the number are
0 through 9, *, #, and A through D.  In addition, 
the comma character (,) introduces a 500 millisecond delay.
.SH ENVIRONMENT
.TP 15
.B AUDIOFILE
specifies the host and server to use.
.SH BUG
Probably.
.PP
If you encounter a \fBreproducible\fP bug, please submit a problem report to
(af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1), ahs(1)
.SH COPYRIGHT
Copyright 1993-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Digital Cambridge Research Lab
