.TH tkPlay 1 "Release 1"  "AF Version 3"
.SH NAME
tkPlay - Tk based AF application for playing soundfiles.
.SH SYNOPSIS
.B tkPlay
.SH DESCRIPTION
.SH RESTRICTIONS
.SH ENVIRONMENT
.TP 8
.B AUDIOFILE
to get the default host and server to use.
.SH BUGS
If you encounter a \fBreproducible\fP bug, please 
submit a problem report to (af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1), aplay(1)
.SH COPYRIGHT
Copyright 1993-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHOR
Digital Cambridge Research Lab

