#!/bin/csh -f
## ###################################################################### ##
##         Copyright IBM Corporation 1988,1991 - All Rights Reserved      ##
##        For full copyright information see:'andrew/config/COPYRITE'     ##
## ###################################################################### ##

if ($#argv == 0) then
	set OBJDIR=.
else
	set OBJDIR=$1
endif
cd ${OBJDIR}
if (! -e Imakefile) then
	echo "==>>> No Imakefile - Cannot Generate Makefile <<<=="
	exit(1)
endif
set DIR=`pwd | tr '/' ' '`
