.TH ROLO 1 "May 1989"
.SH NAME
ROLO \- XView tool to manage notes like a Rolodex.
.SH SYNOPSIS
.B rolo [file]
.SH DESCRIPTION
.I Rolo
is a tool for the Sun workstation which presents a
user interface to a simple database of notes in a manner
which approximates a Rolodex file.  The information in
this man page is available, almost verbatim, within
.I Rolo
by clicking the "?" button in the control panel.
.pp
Each note in your
.I Rolo
file is meant to
simulate a 3x5 card upon which you may scribble
anything you like.  You can have any number of
cards in your Rolodex,
.I Rolo
will keep track of
them for you.  You may browse around through
them, create new ones, throw old ones away,
search for strings in them, etc.
.br
The buttons in the top part of the
.I Rolo
window provide the main controls with which
you manipulate your cards.  Every button on
the control panel has a menu attached which
can be pulled up by pressing the right mouse
button over that item.
Clicking the button directly is equivalent to
selecting the default item from the button menus.
Herewith is a quick overview of what the
buttons do.
.TP
ARROW BUTTONS
These buttons move you through the cards.
The down arrow moves you to the next card in
the file, the up arrow moves you backwards to
the previous card .
.TP
EDIT MENU
.br
.B New Card:
.br
	This creates a new blank card.  By
default, the new card will be inserted after
the currently displayed card.  Using the Shift
key will cause it to be inserted before the
current card.
.br
.B Delete:
.br
	This button deletes cards from your
Rolodex.  A click on this menu button by default
deletes the card which is currently displayed.
You can however select from the active list a
collection of cards to delete. Deleted cards are
not lost, they are saved on a stack of deleted
cards and may be retrieved any time before
.I Rolo
exits.
.br
.B Undelete Last:
.br
	This undelete the last card which was
previously deleted. It can be inserted either
before or after the current card.
.br
.B Undelete...:
.br
	This pops up a new frame below the
origial window, which will list the first line
of all the cards on the deleted stack.  You may
select any of these deleted cards directly from
the list and they will re-inserted back into the
active list of cards before or after the current
card. 
.br
	You can rearrange the order of the cards
in your Rolodex by deleting a card, moving to
a new position, then undeleting it. Note that
blanks cards containing only white space are
not saved on the undeleted stack, they are
thrown away.
.TP
VIEW BUTTON
.br
.B List...:
.br
	This is the default action.  It displays 
an index list of all the cards in your Rolodex.
The first line of each card is displayed in the
window so that you can get a quick overview of
all your cards. Selecting a card and click
"show card" will take you directly to that
card.
.br
.B Help...:
.br
	Displays the information you're reading now.
.br
.B Sort:
.br
	Sorts all the cards in ascending or
descending alphabetical order according to
their first lines.
.TP
FILE MENU
.B Load: From current file:
.br
	Loads your Rolodex cards from that file
as-of the last time they were saved.(the file name
listed in the title bar). You can also reload
the cards from that file as-of the last time
they were saved.
.br
.B Load: From named file...:
.br
	Pops a window, and prompts for a file
name. The default file is shown in the text field.
It then loads your Rolodex cards from that file.
.br
.B Save: To current file:
.br
	Saves your Rolodex cards to that file
that the cards were loaded from.(default: ~/.rolo)
.br
.B Save: To  named file...:
.br
	Pops a window, and prompts for a file
name. The default file is shown in the text field.
It then saves your Rolodex cards to that file.
Saving to or loading from a file this
way causes that new file to become the default
for the regular load and save operations.  You will
be warned about unsaved modifications to your cards,
overwriting existing files, etc.
.br
	When you start up the program, the default
file is .rolo in your home directory ($HOME). If you
wish another file you can specify it as an argument,
or load it in when the program is running.
.TP
FIND BUTTON
	This button searches for a regular expression
in your cards.  This can be used to find any
text pattern which appears anywhere in any of
your cards.  The pattern to search for may be
entered in the text item to the right of the
Find button.  If, at the time the Find
button is clicked, with no text in to text item,
the active selection will be used instead.
.br
	Pressing the return key in the search
pattern item is equivalent to clicking the Find
button but ignoring the selection.
.br
	Due to the way the library search
routines work, all the text of a given card
is treated as one logical line.  The
main effect of this is that the '^' and '$'
operations won't match individual lines within
a card, only the text of the card as a whole.
Note: "Regular expressions" are the kind used
by egrep(1), which are not the same as the
shell meta-characters.
.TP
SLIDER
	The slider item on the control panel may
be used to select any card directly.  Simply
drag the bar back and forth until the number
of the card you wish to see is displayed to
the left of the slider, then release the
mouse button.
Clicking the mouse in buttons on the ends of
the slider gets you to the first and the last
card.
.SH AUTHOR
Ron Hitchens
.br
ronbo@vixen.uucp, hitchens@cs.utexas.edu
.br
Modified by Phoebe Couch for OPEN LOOK.
May 1989.
.br
   March  1987, version 1.0
   August 1988, version 2.0

   Thanks to S. Page (spage@sun.com) and
Mike Ekberg (mae@sun.com) at Sun for changes
and improvements to the original
.I Rolo.
.SH POLICY
.I Rolo
is public domain, anyone and everyone
is welcome to it.  Feel free to give it to your
friends (or even your enemies).  I only ask
that you keep it all together, source included,
as posted.  Please send bug reports, fixes,
gripes, suggestions, etc, to me at the email
address above.
.br
  This version of
.I Rolo
has been ported to Xview
and the user interface has been modified to
conform to OPEN LOOK.  If there are any port
specific programs, please email to me at
phoebe@sun.com.

