/*
 * props_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `props.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "props_ui.h"


/*
 * Global object definitions.
 */
props_popup_objects	*Props_popup;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(argc, argv)
	int	argc;
	char	**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Props_popup = props_popup_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Props_popup->popup);
	exit(0);
}

#endif


/*
 * Notify callback function for `category'.
 */
void
props_popup_category_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	props_popup_objects *ip = (props_popup_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	fprintf(stderr, "props: props_popup_category_notify_callback: value: %u\n", value);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 3)
	{
		xv_set(Props_popup->mouse_controls, XV_SHOW, TRUE, NULL);
	}
	
	if (value == 0)
	{
		xv_set(Props_popup->icon_controls, XV_SHOW, TRUE, NULL);
	}
	
	if (value == 2)
	{
		xv_set(Props_popup->misc_controls, XV_SHOW, TRUE, NULL);
	}
	
	if (value == 1)
	{
		xv_set(Props_popup->menu_controls, XV_SHOW, TRUE, NULL);
	}
	
	/* gxv_end_connections */

}

