/*  -------------------------------------------------------------------

This program is the property of:

                             Cornell University 
                        Center for Applied Mathematics 
                              Ithaca, NY 14853

and may be used, modified and distributed freely, subject to the 
following restrictions:

       Any product which incorporates source code from the dstool
       program or utilities, in whole or in part, is distributed
       with a copy of that source code, including this notice. You
       must give the recipients all the rights that you have with
       respect to the use of this software. Modifications of the
       software must carry prominent notices stating who changed
       the files and the date of any change.

DsTool is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of FITNESS 
FOR A PARTICULAR PURPOSE.  The software is provided as is without 
any obligation on the part of Cornell faculty, staff or students to 
assist in its use, correction, modification or enhancement.

  -----------------------------------------------------------------  */
#ifndef	twoD_opt_HEADER
#define	twoD_opt_HEADER

/*
 * twoD_opt_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `twoD_opt.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	pan;
	Xv_opaque	sym;
	Xv_opaque	addpt;
	Xv_opaque	size;
	Xv_opaque	bg;
	Xv_opaque	cmap_dir;
	Xv_opaque	cmap_file;
	Xv_opaque	showcol;
	Xv_opaque	cmap_use;
	Xv_opaque	depthcoord;
	Xv_opaque	dcoord_min;
	Xv_opaque	dcoord_max;
} twoD_opt_win_objects;

extern twoD_opt_win_objects	*twoD_opt_win_objects_initialize();

extern Xv_opaque	twoD_opt_win_win_create();
extern Xv_opaque	twoD_opt_win_pan_create();
extern Xv_opaque	twoD_opt_win_sym_create();
extern Xv_opaque	twoD_opt_win_addpt_create();
extern Xv_opaque	twoD_opt_win_size_create();
extern Xv_opaque	twoD_opt_win_bg_create();
extern Xv_opaque	twoD_opt_win_cmap_dir_create();
extern Xv_opaque	twoD_opt_win_cmap_file_create();
extern Xv_opaque	twoD_opt_win_showcol_create();
extern Xv_opaque	twoD_opt_win_cmap_use_create();
extern Xv_opaque	twoD_opt_win_depthcoord_create();
extern Xv_opaque	twoD_opt_win_dcoord_min_create();
extern Xv_opaque	twoD_opt_win_dcoord_max_create();
#endif
