.\"
.TH rtf2 1 "Feb 2, 1994" " "
.SH "NAME"
rtf2 - convert a Microsoft Word RTF format document to
an EZ file capable of being used by EZ
.SH "SYNOPSIS"
rtf2 [infile [outfile]] [-t translation_table] [-e stderr_redirection]
.SH "USAGE"
rtf2 requires that you specify a file for input, \fIinfile\fR. 
If you don't specify \fIoutfile\fR, rtf2 will default
to \fIinfile\fR.rtf, stripping off a final ".ez" from
\fIinfile\fR, if appropriate.
.PP
The -t option allows you to specify a non-standard
translation table (see \fIrtftrans(1)\fR).
.PP
The -e option allows you to redirect output from stderr.
Only error messages inhibiting the normal operation of the
program are output to stderr.
.SH "DESCRIPTION"
This program, together with the 2rtf program is designed to
make it possible to edit Microsoft Word documents in EZ, and EZ
documents in Microsoft Word.
.PP
Supported Microsoft Word Commands
.sp 1
Commands in parentheses are the equivelents when the file is
written out in the RTF format.
.PP
The following Microsoft Word formats are fully supported:
.sp 1
\fBFootnote...\fR (\\footnote)
.br
\fBFooter...\fR (\\footer)
.br
Left and Right Margins from \fBDocument...\fR menu (\\margl and \\margr)
.br
Changes in the Left and Right Indentations using the Ruler -
not First line indentation (\\li and \\ri)
.br
\fBIndex Entry\fR - only normal entries (\\xe)
.br
Tab Changes from \fBParagraph...\fR menu - only regular
tabs, right 
justified and centered tabs (\\tx, \\tqr and \\tqc)
.br
\fBBold\fR (\\b)
.br
\fBItalic\fR (\\i)
.br
\fBPlain\fR (\\plain)
.br
Small caps and caps from \fBCharacter...\fR menu (\\scaps and \\caps)
.br
Changes in font (\\f)
.br
Changes in font size (\\fs)
.br
\fBUnderline\fR only normal underlining (\\ul)
.br
Superscript and Subscript from the \fBCharacter...\fR menu (\\up and \\dn)
.br
\fBchdate\fR, \fBchtime\fR, and \fBchpgn\fR for headers
and footers (\\chdate, \\chtime and \\chpgn)
.br
Page Break\fR (\\page)
.br
tabs (\\tab)
.PP
The following Microsoft Word formats are partially supported:
.sp 1
\fBHeader...\fR headers in ez are not placed on the first page. (\\header)
.br
Headers and Footers that are different on left and right pages, act like 
regular headers and footers in ez. (\\headerr, \\headerl, \\footerr and \\footerl)
.br
\fBIndex Entry\fR using bold and italic come across as normal
index entries. (\\bxe and \\ixe)
.br
Hidden Text\fR is supported only for indices and annotations. (\\v)
.br
Special \fBUnderline\fR commands are ignored, and come
accross as normal underlining. (\\ulw, \\uld and \\uldb)
.br
\fBnil\fR, \fBroman\fR, \fBswiss\fR, \fBmodern\fR, \fBscript\fR, \fBdecor\fR, and \fBtech\fR These font families 
are supported in that each family maps to one font  in that family.
.PP
Supported RTF Environments
.sp 1
The following RTF environments are fully supported by rtf2:
.sp 1
\fB\\footnote\fR, \fB\\footer\fR, \fB\
\\xe\fR, \fB\\margl\fR,\fB \\margr\fR, \fB\\pard\fR,\fB \\li\fR,\fB \\ri\fR,\fB \\tx\fR,\fB \\tqr\fR,\fB \\tqc\fR, \fB\\plain\fR, \fB\\b\fR,\fB \\i\fR,\fB \
\\scaps\fR, \fB\\caps\fR,\fB \\f\fR,\fB \\fs\fR, \fB\\ul\fR, \fB\\up\fR,\fB \\dn\fR, \fB\\chdate\fR,\fB \\chtime\fR,\fB \\chpgn\fR,\fB \\par\fR,\fB \\page\fR,\fB \
\\line\fR, and \fB\\tab\fR.
.PP
The following environments are partially supported:
.sp 1
\fB\\header\fR:   header is not put on first page.
.br
\fB\\headerl\fR, \fB\\headerr\fR, \fB\\footerl\fR, \fB\\footerr\fR:  these act like regular headers and footers.
.br
\fB\\field\fR,\fB \\fldrslt\fR:  the field result will be put straight into the document, not \
calculations will be performed.
.br
\fB\\bxe\fR,\fB \\ixe\fR:  act like regular index entries.
.br
\fB\\ftnbj\fR:  this is the ez default, so it is always used, unless specified otherwise.
.br
\fB\\qj\fR:  this is the ez default, so it is always used, unless specified otherwise.
.br
\fB\\v\fR:  supported only for annotations and indices.
.br
\fB\\ulw\fR,\fB \\uld\fR,\fB \\uldb\fR:  they all act like regular underlining.
.PP
The following font families are partially supported: 
.sp 1
\fBfnil\fR, \fBfroman\fR, \fBfswiss\fR, \fBfmodern\fR, \fB\
fscript\fR, \fBfdecor\fR, and \fBftech\fR.  Each font family maps to one ATK font, so individual fonts \
are not distinguished due to the lack of fonts in ATK.
.PP
The following special characters are fully supported: 
.sp 1
 \fB\\~\fR,\fB \\-\fR,\fB \\_\fR,\fB \\'\fR, and \fB\\:\fR.
.SH "EXAMPLES"
.PP
rtf2 resume.rtf
.br
        rtf2 tries to create resume.ez
.PP
rtf2 resume.ez.rtf
.br
        rtf2 tries to create resume.ez.ez
.PP
rtf2 resume.
.br
        rtf2 tries to create resume..ez
.SH "FILES"
.PP
$ANDREWDIR/rtf2.trans (default translation table)
.SH "SEE ALSO"
.PP
2rtf(1)
.SH "COPYRIGHT"
rtf2 is copyright (c) 1989 by the Massachusetts Institute of Technology. 
.PP
RTF is a registered trademark of Microsoft Inc.
.SH "BUGS"
RTF format enforces a stupid convention that styles begin on a
paragraph boundry.  Depending on where EZ styles begin and
end, this enforcement can inject blank lines into text where
you do not want them.
.SH "AUTHOR"
Scott Rixner, MIT Project Athena
.PP
rtf2 is based on the scribetext program written by
Jeremy Paul Kirby, MIT Project Athena
