.TH wordg2b 1 "1 June 1994"
.SH Name
wordg2b \- convert a GB file to a Big5 file based on words
.SH Syntax 
.B wordg2b
[
.B -h
]
[
.B -i
.I FileIn
]
[
.B -o
.I FileOut
]

[
.B -b
.I BMMDICT
]
[
.B -f
.I FMMDICT
]

[
.B -c
.I CharDict
]
[
.B -w
.I WordDict
]

[
.B -p
.I PrefixWordBigramDict
]
[
.B -s
.I SuffixWordBigramDict
]
.SH Description
The program
.I wordg2b
converts a GB file to a Big5 file based on Chinese words,
instead of character by character.
GB (GuoBiao) refers to the implementation of
the encoding scheme of "GB2312-80"
of Mainland China, in which each of the two bytes representing a GB code
has its most significant bit set to 1.
Big5 refers to the Big Five standard published in 1984 by
Taiwan's Institute for Information Industry.
The most significant bit of the first byte
of a Big5 code
is set to 1.

.I wordg2b
uses some tables,
in the directory specified by the environment variable
.BI WORDG2B_PATH ,
and if 
.BI WORDG2B_PATH
is not specified,
the tables must be
in the current working directory.

The possible options for
.I wordg2b
are:
.TP
.BI -h
Print the help message for using
.I wordg2b .
.TP
.BI -i
Specify the user's input GB file.
The default is the file named 'wordg2b.in',
not standard input (stdin).
.TP
.BI -o
Specify the user's output Big5 file.
The default is the file named 'wordg2b.out',
not standard output (stdout).
.TP
.BI -b
Specify the dictionary file for \fI b\fPackward maximal matching
during word segmentation by
.I wordg2b .
The default is 'DICT.BMM'.
.TP
.BI -f
Specify the dictionary file for \fI f\fPorward maximal matching
during word segmentation by
.I wordg2b .
The default is 'DICT.FMM'.
.TP
.BI -c
Specify the GB-Big5 \fI c\fPharacter table.
The default is 'g2bchar.tab'.
.TP
.BI -w
Specify the GB-Big5 \fI w\fPord table.
The default is 'g2bword.tab'.
.TP
.BI -p
Specify the GB-B5 word-bigram table,
where a \fI s\fPingle-\fI c\fPharacter-\fI w\fPord
is the \fI p\fPrefix word of the word-bigram.
The default is ''prefix.scw.bigram.tab'.
.TP
.BI -s
Specify the GB-B5 word-bigram table,
where a \fI s\fPingle-\fI c\fPharacter-\fI w\fPord
is the \fI s\fPuffix word of the word-bigram.
The default is ''suffix.scw.bigram.tab'.

.SH Copyright
Copyright (C) 1994 Man-Chi Pong
.sp
All Rights Reserved.
.sp
This program, the associated utilities
and the table files are NOT in the public domain.
.\"	.sp
.\"	You may copy and distribute verbatim copies of wordg2b source code
.\"	files, table file(s), and documentation files as you receive it
.\"	for non-commercial purposes.
.\"	.sp
.\"	If you wish to incorporate parts of wordg2b into other programs,
.\"	write to the author.  The author has not yet worked out a simple rule
.\"	that can be stated here, but usually it will be permitted.

.SH Author
Man-Chi Pong

.SH Bugs
Not known.

.SH Disclaimer
This software is provided "as is" and the author disclaim
all warranties with regard to this software
and the correctness of the table files,
including
all implied warranties of merchantability and fitness.
In no event shall
the author be liable for any special, indirect or consequential damages or
any damages whatsoever resulting from loss of use, data or profits,
whether in an action of contract, negligence or other tortious action,
arising out of or in connection with the use or performance of this
software.
