#
# Makefile for DOS machines using the Microsoft Compiler
#

CFLAGS = -AL -I.. -W2

#
# -AL = Large model
# -W2 = Set warning level 2

metamail: metamail.exe

mmencode: mmencode.exe

metamail.exe: metamail.obj codes.obj uue.obj
        link /co/st:16384 metamail codes uue,metamail,metamail/map,;

mmencode.exe: mmencode.obj codes.obj
        link mmencode codes,mmencode,,;
