.\" @(#)calctool.1 2.2 27/04/88 SMI;
.TH CALCTOOL 1L "27 April 1988"
.SH NAME
calctool \- window based calculator for the Sun workstation
.SH SYNOPSIS
.B "calctool
[
.B -h
.I helpfile
]
[
.B -v
]
[
.B -?
]
.SH DESCRIPTION
.I Calctool
is a window based calculator for the Sun. It receives input via the mouse
or the keyboard. Each calculator button has two functions associated with it.
.LP
Internal arithmetic is done with double precision floating point numbers.
Accuracy can be adjusted from zero to nine numeric places, and the base of
operation can be binary,octal,decimal or hexidecimal.  Numbers are initially
displayed to two numeric places, in decimal base.
.LP
The numeric display can be adjusted using the
.I SunView
.I Put
and
.I Get
function keys.  The previous digit entered can be removed and the
whole display cleared.
.LP
There are ten memory registers; numbers can be retrieved or stored in
these locations, and arithmetic can be performed upon register contents.
.LP
In addition to the current numerical value, the display window contains the
current base and the current trigonometrical units. If an operation needing
more than one numerical input is partially complete, the operation
is also displayed in this window as a reminder.
.LP
The calculator has arithmetical, logical and trigonometrical functions.
These are grouped together and color coded on color workstations.
.LP
Online help is provided via a help button.  Select this button, and then
the function you wish to be described.
.SH OPTIONS
.TP
.BI -h " helpfile"
Use an alternate helpfile.
.TP
.B -v
Print the version number of this release of the
.I calctool
program.
.TP
.B -?
Print the usage line for this program. Note that the
.I ?
character should be escaped if running from
.IR csh (1).
.SH CALCULATOR BUTTONS
[Keyboard equivalents appear in brackets]
.SS Numerical Keys [0-9 a-f . = <RETURN>].
.LP
Enter a digit (decimal digits 0-9 or hexidecimal digits A-F) in the display.
The . acts as the decimal point and = is used for completion of numerical
entry (<RETURN> can be also be used from the keyboard to terminate numerical
entry).
.SS Arithmetical Operations [+ - x X * /].
.LP
Perform an arithmetical operation using the preivous entry and the next entry
as operands.  Addition, subtraction, multiplication and division are denoted
by the buttons +, \-, x and / respectively (the keyboard keys * and X are
synonymous with x for multiplication).
.SS Base Changes.
.LP
.IP "\fBBIN  [ B ]\fP" 18
Change display base to binary (maximum: 32 digits).
.IP "\fBOCT  [ O ]\fP" 18
Change display base to octal (maximum: 15 digits). are allowed.
.IP "\fBDEC  [ D ]\fP" 18
Change display base to decimal (default; maximum: 12 digits).
.IP "\fBHEX  [ H ]\fP" 18
Change display base to hexidecimal (maximum: 12 digits).
.SS Trigonometric Unit Changes.
.LP
.IP "\fBDEG  [ ^d ]\fP" 18
Change current trigonometrical base to degrees.
.IP "\fBRAD  [ ^r ]\fP" 18
Change the current trigonometrical base to radians.
.IP "\fBGRAD [ ^g ]\fP" 18
Change the current trigonometrical base to gradients.
.SS Logical Operations.
.LP
.IP "\fBAND  [ & ]\fP" 18
Perform a logical AND operation on the current entry and the next entry,
treating both numbers as unsigned long integers.
.IP "\fBNOT  [ ~ ]\fP" 18
Perform the logical NOT operation of the current entry.
.IP "\fBOR   [ | ]\fP" 18
Perform a logical OR operation on the current entry and the next entry,
treating both numbers as unsigned long integers.
.IP "\fBXNOR [ n or N ]\fP" 18
Perform a logical XNOR operation on the current entry and the next entry,
treating both numbers as unsigned long integers.
.IP "\fBXOR  [ ^ ]\fP" 18
Perform a logical XOR operation on the current entry and the next entry,
treating both numbers as unsigned long integers.
.SS Trigonometrical Operators.
.LP
.IP "\fBASIN [ } ]\fP" 18
Return the trigonometric Arc Sin of the current entry, in the
current units (degrees, radians or gradients).
.IP "\fBSIN  [ { ]\fP" 18
Return the trigonometric Sin of the current entry, in the current
units (degrees, radians or gradients).
.IP "\fBACOS [ ) ]\fP" 18
Return the trigonometric Arc Cos of the current entry, in the
current units (degrees, radians or gradients).
.IP "\fBCOS  [ ( ]\fP" 18
Return the trigonometric Cos of the current entry, in the current
units (degrees, radians or gradients).
.IP "\fBATAN [ T ]\fP" 18
Return the trigonometric Arc Tan of the current entry, in the
current units (degrees, radians or gradients).
.IP "\fBTAN  [ t ]\fP" 18
Return the trigonometric Tan of the current entry, in the current
units (degrees, radians or gradients).
.SS Memory Register Operators.
.LP
.IP "\fBRCL  [ r ]\fP" 18
Retrieve memory register n.  This selection must be followed by a digit
in the range 0 to 9 to indicate a memory register.
.IP "\fBSTO  [ s ]\fP" 18
Store memory register n.  This must be followed by a digit in the range
0 to 9 to indicate a memory register.  The register number may be preceded
by an arithmetic operation (addition, subtraction, multiplication or division),
in which case the specifed operation is carred out between the
displayed entry and the value currently in register n, and the result is placed
in register n.
.SS Constants.
.LP
.IP "\fBPI   [ P ]\fP" 18
Enter the value of pi.
.IP "\fBe    [ E ]\fP" 18
Enter the value of e.
.SS Mathematical Operators.
.LP
.IP "\fB%    [ % ]\fP" 18
Perform a percentage calculation using the last entry and the next entry.
.IP "\fBe^x  [ # ]\fP" 18
Return e raised to the power of the current entry.
.IP "\fB10^x [ $ ]\fP" 18
Return 10 raised to the power of the current entry.
.IP "\fBy^x  [ Y ]\fP" 18
Take the last entry and raise it to the power of the next entry.
.IP "\fBln   [ N ]\fP" 18
Return the natural logarithm of the current entry.
.IP "\fBlog  [ G ]\fP" 18
Returns the base 10 logarithm of the current entry.
.IP "\fBSQRT [ S ]\fP" 18
Perform a square root operation on the current entry.
.IP "\fB1/x  [ R ]\fP" 18
Return the value of 1 divided by the current entry.
.IP "\fBx!   [ ! ]\fP" 18
Return the factorial of the current entry.
.IP "\fBx^2  [ @ ]\fP" 18
Return the square of the current entry.
.SS Number Manipulation Operators.
.LP
.IP "\fB<    [ < ]\fP" 18
Left shift n places. This must be followed by a digit
in the range 0 to 9 to indicate the number of places to shift.
.IP "\fB>    [ > ]\fP" 18
Right shift n places. This must be followed by a digit
in the range 0 to 9 to indicate the number of places to shift.
.IP "\fB&32  [ i ]\fP" 18
Truncate the current entry to a 32 bit unsigned integer
(logical function).
.IP "\fB&16  [ h ]\fP" 18
Truncate the given number to a 16 bit unsigned integer
(logical function).
.IP "\fBclr  [ Delete ]\fP" 18
Clear the calculator display.
.IP "\fBbsp  [ BackSpace ]\fP" 18
Remove the rightmost character of the current entry
and recalculate the the displayed value (note: internal accuracy is
lost with this operation).
.IP "\fBINT  [ I ]\fP" 18
Return the integer portion of the current entry.
.IP "\fBFRAC [ F ]\fP" 18
Return the fractional portion of the current entry.
.IP "\fBACC  [ A ]\fP" 18
Set accuracy. This must be followed by a digit in the range 0 to 9 to
indicate how many digits are to be displayed.
.IP "\fBCHS  [ C ]\fP" 18
Change the arithmetic sign of the current entry.
.IP "\fBABS  [ U ]\fP" 18
Return the absolute value of the current entry.
.SS Other keys.
.LP
.IP "\fBMEM  [ M ]\fP" 18
Toggle the display of the popup register window.
Values of the ten memory registers are displayed in the current
base, to the current accuracy.
.IP "\fBKEYS [ K ]\fP" 18
Toggle the labels on the calctool buttons between mouse and
keyboard equivalents.
.IP "\fB?    [ ? ]\fP" 18
Display a help message for a particular button.  First select this key, then
the key to be described.
.IP "\fBQUIT [q or Q]\fP" 18
Exit (without user verification).
.IP "\fBOFF  [ o ]\fP" 18
Change \fIcalctool\fP to an icon.
.SH FILES
.TP
/usr/local/lib/calctool.help
.SH BUGS
Parsing of the online help file is very primative.
.LP
Handling of errors generated by the mathematical routines is poorly
done.
.SH AUTHOR
Rich Burridge, Sun Microsystems, Unit 2, 49-53 Hotham Pde, Artarmon, N.S.W.
2164, AUSTRALIA.  PHONE: +61 2 436 4699
.nf
JANET: richb%sunaus.oz@uk.ac.ucl.cs
ACSnet:  richb@sunaus.oz
UUCP: {uunet,hplabs,mcvax,ukc}!munnari!sunaus.oz!richb
ARPAnet: rburridge@Sun.COM
.fi
.br
Manual page modified by R. P. C. Rodgers, UCSF School of Pharmacy, San
Francisco, CA 94143.
