PROGRAMS=allcaps cut_paste editor error_test file_browser modify_text password prompt_phone prompt_phone2 replace search_text select_text simple_text text_box

CFLAGS=
INCLUDES = -I/usr/Motif12/include -I/usr/X11R6/include
LIBS= -L/usr/Motif12/lib -L/usr/X11R6/lib -lXm -lXt -lSM -lICE -lX11

all: $(PROGRAMS) 

.c: ; $(CC) $(CFLAGS) $(INCLUDES) $@.c $(LIBS) -o $@
