#ifndef	psdraw_HEADER
#define	psdraw_HEADER

/*
 * psdraw_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `psdraw.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls;
	Xv_opaque	mode;
	Xv_opaque	props_button;
	Xv_opaque	clear_button;
	Xv_opaque	text;
	Xv_opaque	group7;
	Xv_opaque	canvas;
} psdraw_win_objects;

extern psdraw_win_objects	*psdraw_win_objects_initialize();

extern Xv_opaque	psdraw_win_win_create();
extern Xv_opaque	psdraw_win_controls_create();
extern Xv_opaque	psdraw_win_mode_create();
extern Xv_opaque	psdraw_win_props_button_create();
extern Xv_opaque	psdraw_win_clear_button_create();
extern Xv_opaque	psdraw_win_text_create();
extern Xv_opaque	psdraw_win_group7_create();
extern Xv_opaque	psdraw_win_canvas_create();

typedef struct {
	Xv_opaque	popup;
	Xv_opaque	props_controls;
	Xv_opaque	fill;
	Xv_opaque	fill_color;
	Xv_opaque	line_color;
	Xv_opaque	line_width;
	Xv_opaque	group1;
	Xv_opaque	line_style;
	Xv_opaque	line_dash;
	Xv_opaque	line_cap;
	Xv_opaque	line_join;
	Xv_opaque	group2;
	Xv_opaque	miter_limit;
	Xv_opaque	group3;
	Xv_opaque	font;
	Xv_opaque	font_size;
	Xv_opaque	group5;
	Xv_opaque	hold_mode;
	Xv_opaque	group4;
} psdraw_popup_objects;

extern psdraw_popup_objects	*psdraw_popup_objects_initialize();

extern Xv_opaque	psdraw_popup_popup_create();
extern Xv_opaque	psdraw_popup_props_controls_create();
extern Xv_opaque	psdraw_popup_fill_create();
extern Xv_opaque	psdraw_popup_fill_color_create();
extern Xv_opaque	psdraw_popup_line_color_create();
extern Xv_opaque	psdraw_popup_line_width_create();
extern Xv_opaque	psdraw_popup_group1_create();
extern Xv_opaque	psdraw_popup_line_style_create();
extern Xv_opaque	psdraw_popup_line_dash_create();
extern Xv_opaque	psdraw_popup_line_cap_create();
extern Xv_opaque	psdraw_popup_line_join_create();
extern Xv_opaque	psdraw_popup_group2_create();
extern Xv_opaque	psdraw_popup_miter_limit_create();
extern Xv_opaque	psdraw_popup_group3_create();
extern Xv_opaque	psdraw_popup_font_create();
extern Xv_opaque	psdraw_popup_font_size_create();
extern Xv_opaque	psdraw_popup_group5_create();
extern Xv_opaque	psdraw_popup_hold_mode_create();
extern Xv_opaque	psdraw_popup_group4_create();
#endif
