.TH AFXCTL 1 "Release 1"  "AF Version 3"
.SH NAME
afxctl - AF control panel
.SH SYNOPSIS
.B afxctl
.SH DESCRIPTION
This program is an X based control panel for an AF server.
\fIafxctl\fP 
allows manipulation of input and output gain and input
and output device selection using an X window control panel.
.SH ENVIRONMENT
.TP 8
.B AUDIOFILE
to get the default host and server to use.
.SH BUGS
If you encounter a \fBreproducible\fP bug, please 
submit a problem report to (af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1)
.SH COPYRIGHT
Copyright 1992,1993 Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHOR
Digital Cambridge Research Lab

