############################################
# dstool - GENERIC LIBRARY makefile        #
############################################

include ${DSTOOL}/site_specific/lib_incl.mk
############################################
# Modify the following segment only.       #
############################################
LIBRARY = triallib.a

SOURCES_A = \
	trial_cui.c \
	trial_hnd.c \
	trial.c \
	trial_go.c

DEPS_A = trial_cui.h

SOURCES_B = 

DEPS_B = 

TEST_PROGRAM = 

TEST_SOURCES = 

TEST_DEPS =

##############################################
# The following line should not be modified  #
##############################################

include ${DSTOOL}/site_specific/win_targetsA.mk

