.TH GRTOOL 1 "August 1989"
.SH NAME
grtool \- graphics for exploratory data analysis
.SH SYNOPSIS
.B gr
[
.B
.I data_files] [
.B\-h
] [
.B\-p
.I parameter_file] [
.B\-i
.I IHL_formatted_file] [
.B\-r
.I result_file] [
.B\-d
.I device_number] [
.B\-f
.I graphics_output_file]
.SH DESCRIPTION
.I Grtool 
is a data/function plotting tool for Sun workstations 
Here are some of its features:
.PP
Curve fitting
.PP
Plots up to 15 datasets or functions.
.PP
User-defined scaling, tic marks, labels, symbols, line styles, colors.
.PP
Batch mode for unattended plotting.
.PP
Read and write parameters used during a session.
.PP
Support through a device independent graphics driver for
HP75xx and PostScript. Other devices can be added
but will require recompiling grtool.
.PP
.SH OPTIONS
.IP \fB\-i\fP\ [\fIfile_name]\fP
Assume 
.I file_name 
is in IHL format 
.IP \fB\-p\fP\ [\fIparm_file]\fP
Read the parameter file 
.I parm_file.
.IP \fB\-r\fP\ [\fIresult_file]\fP
Write results from regression to 
.I result_file 
.IP \fB\-d\fP\ [\fIdevice]\fP
Set the hardcopy device to 
.I device.
.IP \fB\-h\fP
Don't run interactive, just print a hardcopy and quit (used in batch mode).
.IP \fB\-f\fP\ [\fIoutput_file]\fP
When the selected device is the generic graphics driver, direct output to file
.I output_file
(used in batch mode).
.SH AUTHOR
Paul Turner, Oregon Graduate Center.
.SH BUGS
.SH SEE ALSO
disp(1)
