.TH ABOB 1 "Release 1"  "AF Version 3"
.SH NAME
abob - Bob control panel.
.SH SYNOPSIS
.B abob [\fIdir\fP]
.SH DESCRIPTION
Try it.
.LP
If \fIdir\fP is specified, abob checks for bob.snd
in that directory.
If not specified, and the environment variable \fISOUND_PATH\fP
is defined, abob will check for bob.snd in the directories specified
by \fISOUND_PATH\fP.
.SH RESTRICTIONS
Recorded Bob is only available in 8KHz mono at this time.
Watch this space for an announcment about Bob in HiFi.
.SH ENVIRONMENT
.TP 8
.B AUDIOFILE
to get the default host and server to use.
.TP 8
.B SOUND_PATH
specifies a colon-separated list of directories in which sounds may be found.
.SH BUGS
If you encounter a \fBreproducible\fP bug, please 
submit a problem report to (af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1)  aplay(1)
.SH COPYRIGHT
Copyright 1992-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHOR
Anonymous.
