# (C) Universitaet Passau, Michael Himsolt 1986-1991
#########################################################################
#									#
#			    GRAPHED MAKEFILE				#
#									#
#########################################################################


#
# Directories
#
GRAPHEDDIR = ../..

#
# Sourcefiles
#
CSOURCES = termgraph_agent.c termgraph_main.c termgraph_petrinet.c \
	   termgraph_tree.c termgraph_window.c
HSOURCES = termgraph_decl.h termgraph_main.h
MYFILES = $(HSOURCES) $(CSOURCES)

MODULE=termgraph
include ../makefile.template
include $(GRAPHEDDIR)/makefile.template

# DO NOT DELETE THIS LINE -- make depend depends on it.

termgraph_agent.o: termgraph_decl.h /usr/include/string.h
termgraph_agent.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
termgraph_agent.o: /usr/include/ctype.h /usr/include/math.h
termgraph_agent.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
termgraph_agent.o: ../../sgraph/std.h /usr/include/assert.h
termgraph_agent.o: /usr/include/stdio.h /usr/include/malloc.h
termgraph_agent.o: ../../sgraph/sgraph.h ../../sgraph/slist.h
termgraph_agent.o: ../../sgraph/graphed.h ../../sgraph/graphed_structures.h
termgraph_agent.o: /usr/openwin/include/xview/rect.h
termgraph_agent.o: /usr/openwin/include/xview/xv_c_types.h
termgraph_agent.o: ../../sgraph/dispatch_commands.h
termgraph_agent.o: ../../sgraph/sgraph_interface.h
termgraph_agent.o: ../../sgraph/sgragra_interface.h
termgraph_agent.o: /usr/openwin/include/xview/xview.h
termgraph_agent.o: /usr/openwin/include/xview/xview_xvin.h
termgraph_agent.o: /usr/include/signal.h /usr/include/sys/signal.h
termgraph_agent.o: /usr/include/vm/faultcode.h /usr/include/sys/types.h
termgraph_agent.o: /usr/include/sys/sysmacros.h
termgraph_agent.o: /usr/include/pixrect/pixrect.h
termgraph_agent.o: /usr/include/pixrect/pr_planegroups.h
termgraph_agent.o: /usr/include/pixrect/pr_util.h
termgraph_agent.o: /usr/include/pixrect/memvar.h
termgraph_agent.o: /usr/include/pixrect/pixfont.h
termgraph_agent.o: /usr/include/pixrect/traprop.h
termgraph_agent.o: /usr/include/pixrect/pr_line.h
termgraph_agent.o: /usr/openwin/include/xview/generic.h
termgraph_agent.o: /usr/openwin/include/xview/pkg_public.h
termgraph_agent.o: /usr/openwin/include/xview/pkg.h
termgraph_agent.o: /usr/openwin/include/xview/attr.h
termgraph_agent.o: /usr/openwin/include/xview/base.h
termgraph_agent.o: /usr/openwin/include/xview/notify.h
termgraph_agent.o: /usr/include/sys/wait.h /usr/include/sys/time.h
termgraph_agent.o: /usr/include/sys/time.h /usr/include/sys/resource.h
termgraph_agent.o: /usr/include/varargs.h
termgraph_agent.o: /usr/openwin/include/xview/xv_error.h
termgraph_agent.o: /usr/openwin/include/xview/sun.h
termgraph_agent.o: /usr/openwin/include/xview/server.h
termgraph_agent.o: /usr/openwin/include/xview/screen.h
termgraph_agent.o: /usr/openwin/include/xview/pixwin.h
termgraph_agent.o: /usr/openwin/include/xview/rectlist.h
termgraph_agent.o: /usr/openwin/include/xview/win_input.h
termgraph_agent.o: /usr/openwin/include/X11/Xlib.h
termgraph_agent.o: /usr/openwin/include/X11/X.h
termgraph_agent.o: /usr/openwin/include/xview/win_event.h
termgraph_agent.o: /usr/openwin/include/xview/xv_version.h
termgraph_agent.o: /usr/openwin/include/xview/icon.h
termgraph_agent.o: /usr/openwin/include/xview/window.h
termgraph_agent.o: /usr/openwin/include/xview/drawable.h
termgraph_agent.o: /usr/openwin/include/xview/attrol.h
termgraph_agent.o: /usr/openwin/include/xview/svrimage.h
termgraph_agent.o: /usr/openwin/include/xview/frame.h
termgraph_agent.o: /usr/openwin/include/xview/openmenu.h
termgraph_agent.o: /usr/openwin/include/xview/panel.h
termgraph_agent.o: /usr/openwin/include/xview/canvas.h
termgraph_agent.o: /usr/openwin/include/xview/openwin.h
termgraph_agent.o: /usr/openwin/include/xview/tty.h
termgraph_agent.o: /usr/openwin/include/xview/text.h
termgraph_agent.o: /usr/openwin/include/xview/textsw.h
termgraph_agent.o: /usr/openwin/include/xview/sel_attrs.h
termgraph_agent.o: /usr/openwin/include/xview/scrollbar.h
termgraph_agent.o: /usr/openwin/include/xview/expandname.h
termgraph_main.o: termgraph_decl.h /usr/include/string.h
termgraph_main.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
termgraph_main.o: /usr/include/ctype.h /usr/include/math.h
termgraph_main.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
termgraph_main.o: ../../sgraph/std.h /usr/include/assert.h
termgraph_main.o: /usr/include/stdio.h /usr/include/malloc.h
termgraph_main.o: ../../sgraph/sgraph.h ../../sgraph/slist.h
termgraph_main.o: ../../sgraph/graphed.h ../../sgraph/graphed_structures.h
termgraph_main.o: /usr/openwin/include/xview/rect.h
termgraph_main.o: /usr/openwin/include/xview/xv_c_types.h
termgraph_main.o: ../../sgraph/dispatch_commands.h
termgraph_main.o: ../../sgraph/sgraph_interface.h
termgraph_main.o: ../../sgraph/sgragra_interface.h
termgraph_main.o: /usr/openwin/include/xview/xview.h
termgraph_main.o: /usr/openwin/include/xview/xview_xvin.h
termgraph_main.o: /usr/include/signal.h /usr/include/sys/signal.h
termgraph_main.o: /usr/include/vm/faultcode.h /usr/include/sys/types.h
termgraph_main.o: /usr/include/sys/sysmacros.h /usr/include/pixrect/pixrect.h
termgraph_main.o: /usr/include/pixrect/pr_planegroups.h
termgraph_main.o: /usr/include/pixrect/pr_util.h
termgraph_main.o: /usr/include/pixrect/memvar.h
termgraph_main.o: /usr/include/pixrect/pixfont.h
termgraph_main.o: /usr/include/pixrect/traprop.h
termgraph_main.o: /usr/include/pixrect/pr_line.h
termgraph_main.o: /usr/openwin/include/xview/generic.h
termgraph_main.o: /usr/openwin/include/xview/pkg_public.h
termgraph_main.o: /usr/openwin/include/xview/pkg.h
termgraph_main.o: /usr/openwin/include/xview/attr.h
termgraph_main.o: /usr/openwin/include/xview/base.h
termgraph_main.o: /usr/openwin/include/xview/notify.h /usr/include/sys/wait.h
termgraph_main.o: /usr/include/sys/time.h /usr/include/sys/time.h
termgraph_main.o: /usr/include/sys/resource.h /usr/include/varargs.h
termgraph_main.o: /usr/openwin/include/xview/xv_error.h
termgraph_main.o: /usr/openwin/include/xview/sun.h
termgraph_main.o: /usr/openwin/include/xview/server.h
termgraph_main.o: /usr/openwin/include/xview/screen.h
termgraph_main.o: /usr/openwin/include/xview/pixwin.h
termgraph_main.o: /usr/openwin/include/xview/rectlist.h
termgraph_main.o: /usr/openwin/include/xview/win_input.h
termgraph_main.o: /usr/openwin/include/X11/Xlib.h
termgraph_main.o: /usr/openwin/include/X11/X.h
termgraph_main.o: /usr/openwin/include/xview/win_event.h
termgraph_main.o: /usr/openwin/include/xview/xv_version.h
termgraph_main.o: /usr/openwin/include/xview/icon.h
termgraph_main.o: /usr/openwin/include/xview/window.h
termgraph_main.o: /usr/openwin/include/xview/drawable.h
termgraph_main.o: /usr/openwin/include/xview/attrol.h
termgraph_main.o: /usr/openwin/include/xview/svrimage.h
termgraph_main.o: /usr/openwin/include/xview/frame.h
termgraph_main.o: /usr/openwin/include/xview/openmenu.h
termgraph_main.o: /usr/openwin/include/xview/panel.h
termgraph_main.o: /usr/openwin/include/xview/canvas.h
termgraph_main.o: /usr/openwin/include/xview/openwin.h
termgraph_main.o: /usr/openwin/include/xview/tty.h
termgraph_main.o: /usr/openwin/include/xview/text.h
termgraph_main.o: /usr/openwin/include/xview/textsw.h
termgraph_main.o: /usr/openwin/include/xview/sel_attrs.h
termgraph_main.o: /usr/openwin/include/xview/scrollbar.h
termgraph_main.o: /usr/openwin/include/xview/expandname.h termgraph_main.h
termgraph_petrinet.o: termgraph_decl.h /usr/include/string.h
termgraph_petrinet.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
termgraph_petrinet.o: /usr/include/ctype.h /usr/include/math.h
termgraph_petrinet.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
termgraph_petrinet.o: ../../sgraph/std.h /usr/include/assert.h
termgraph_petrinet.o: /usr/include/stdio.h /usr/include/malloc.h
termgraph_petrinet.o: ../../sgraph/sgraph.h ../../sgraph/slist.h
termgraph_petrinet.o: ../../sgraph/graphed.h
termgraph_petrinet.o: ../../sgraph/graphed_structures.h
termgraph_petrinet.o: /usr/openwin/include/xview/rect.h
termgraph_petrinet.o: /usr/openwin/include/xview/xv_c_types.h
termgraph_petrinet.o: ../../sgraph/dispatch_commands.h
termgraph_petrinet.o: ../../sgraph/sgraph_interface.h
termgraph_petrinet.o: ../../sgraph/sgragra_interface.h
termgraph_petrinet.o: /usr/openwin/include/xview/xview.h
termgraph_petrinet.o: /usr/openwin/include/xview/xview_xvin.h
termgraph_petrinet.o: /usr/include/signal.h /usr/include/sys/signal.h
termgraph_petrinet.o: /usr/include/vm/faultcode.h /usr/include/sys/types.h
termgraph_petrinet.o: /usr/include/sys/sysmacros.h
termgraph_petrinet.o: /usr/include/pixrect/pixrect.h
termgraph_petrinet.o: /usr/include/pixrect/pr_planegroups.h
termgraph_petrinet.o: /usr/include/pixrect/pr_util.h
termgraph_petrinet.o: /usr/include/pixrect/memvar.h
termgraph_petrinet.o: /usr/include/pixrect/pixfont.h
termgraph_petrinet.o: /usr/include/pixrect/traprop.h
termgraph_petrinet.o: /usr/include/pixrect/pr_line.h
termgraph_petrinet.o: /usr/openwin/include/xview/generic.h
termgraph_petrinet.o: /usr/openwin/include/xview/pkg_public.h
termgraph_petrinet.o: /usr/openwin/include/xview/pkg.h
termgraph_petrinet.o: /usr/openwin/include/xview/attr.h
termgraph_petrinet.o: /usr/openwin/include/xview/base.h
termgraph_petrinet.o: /usr/openwin/include/xview/notify.h
termgraph_petrinet.o: /usr/include/sys/wait.h /usr/include/sys/time.h
termgraph_petrinet.o: /usr/include/sys/time.h /usr/include/sys/resource.h
termgraph_petrinet.o: /usr/include/varargs.h
termgraph_petrinet.o: /usr/openwin/include/xview/xv_error.h
termgraph_petrinet.o: /usr/openwin/include/xview/sun.h
termgraph_petrinet.o: /usr/openwin/include/xview/server.h
termgraph_petrinet.o: /usr/openwin/include/xview/screen.h
termgraph_petrinet.o: /usr/openwin/include/xview/pixwin.h
termgraph_petrinet.o: /usr/openwin/include/xview/rectlist.h
termgraph_petrinet.o: /usr/openwin/include/xview/win_input.h
termgraph_petrinet.o: /usr/openwin/include/X11/Xlib.h
termgraph_petrinet.o: /usr/openwin/include/X11/X.h
termgraph_petrinet.o: /usr/openwin/include/xview/win_event.h
termgraph_petrinet.o: /usr/openwin/include/xview/xv_version.h
termgraph_petrinet.o: /usr/openwin/include/xview/icon.h
termgraph_petrinet.o: /usr/openwin/include/xview/window.h
termgraph_petrinet.o: /usr/openwin/include/xview/drawable.h
termgraph_petrinet.o: /usr/openwin/include/xview/attrol.h
termgraph_petrinet.o: /usr/openwin/include/xview/svrimage.h
termgraph_petrinet.o: /usr/openwin/include/xview/frame.h
termgraph_petrinet.o: /usr/openwin/include/xview/openmenu.h
termgraph_petrinet.o: /usr/openwin/include/xview/panel.h
termgraph_petrinet.o: /usr/openwin/include/xview/canvas.h
termgraph_petrinet.o: /usr/openwin/include/xview/openwin.h
termgraph_petrinet.o: /usr/openwin/include/xview/tty.h
termgraph_petrinet.o: /usr/openwin/include/xview/text.h
termgraph_petrinet.o: /usr/openwin/include/xview/textsw.h
termgraph_petrinet.o: /usr/openwin/include/xview/sel_attrs.h
termgraph_petrinet.o: /usr/openwin/include/xview/scrollbar.h
termgraph_petrinet.o: /usr/openwin/include/xview/expandname.h
termgraph_tree.o: termgraph_decl.h /usr/include/string.h
termgraph_tree.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
termgraph_tree.o: /usr/include/ctype.h /usr/include/math.h
termgraph_tree.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
termgraph_tree.o: ../../sgraph/std.h /usr/include/assert.h
termgraph_tree.o: /usr/include/stdio.h /usr/include/malloc.h
termgraph_tree.o: ../../sgraph/sgraph.h ../../sgraph/slist.h
termgraph_tree.o: ../../sgraph/graphed.h ../../sgraph/graphed_structures.h
termgraph_tree.o: /usr/openwin/include/xview/rect.h
termgraph_tree.o: /usr/openwin/include/xview/xv_c_types.h
termgraph_tree.o: ../../sgraph/dispatch_commands.h
termgraph_tree.o: ../../sgraph/sgraph_interface.h
termgraph_tree.o: ../../sgraph/sgragra_interface.h
termgraph_tree.o: /usr/openwin/include/xview/xview.h
termgraph_tree.o: /usr/openwin/include/xview/xview_xvin.h
termgraph_tree.o: /usr/include/signal.h /usr/include/sys/signal.h
termgraph_tree.o: /usr/include/vm/faultcode.h /usr/include/sys/types.h
termgraph_tree.o: /usr/include/sys/sysmacros.h /usr/include/pixrect/pixrect.h
termgraph_tree.o: /usr/include/pixrect/pr_planegroups.h
termgraph_tree.o: /usr/include/pixrect/pr_util.h
termgraph_tree.o: /usr/include/pixrect/memvar.h
termgraph_tree.o: /usr/include/pixrect/pixfont.h
termgraph_tree.o: /usr/include/pixrect/traprop.h
termgraph_tree.o: /usr/include/pixrect/pr_line.h
termgraph_tree.o: /usr/openwin/include/xview/generic.h
termgraph_tree.o: /usr/openwin/include/xview/pkg_public.h
termgraph_tree.o: /usr/openwin/include/xview/pkg.h
termgraph_tree.o: /usr/openwin/include/xview/attr.h
termgraph_tree.o: /usr/openwin/include/xview/base.h
termgraph_tree.o: /usr/openwin/include/xview/notify.h /usr/include/sys/wait.h
termgraph_tree.o: /usr/include/sys/time.h /usr/include/sys/time.h
termgraph_tree.o: /usr/include/sys/resource.h /usr/include/varargs.h
termgraph_tree.o: /usr/openwin/include/xview/xv_error.h
termgraph_tree.o: /usr/openwin/include/xview/sun.h
termgraph_tree.o: /usr/openwin/include/xview/server.h
termgraph_tree.o: /usr/openwin/include/xview/screen.h
termgraph_tree.o: /usr/openwin/include/xview/pixwin.h
termgraph_tree.o: /usr/openwin/include/xview/rectlist.h
termgraph_tree.o: /usr/openwin/include/xview/win_input.h
termgraph_tree.o: /usr/openwin/include/X11/Xlib.h
termgraph_tree.o: /usr/openwin/include/X11/X.h
termgraph_tree.o: /usr/openwin/include/xview/win_event.h
termgraph_tree.o: /usr/openwin/include/xview/xv_version.h
termgraph_tree.o: /usr/openwin/include/xview/icon.h
termgraph_tree.o: /usr/openwin/include/xview/window.h
termgraph_tree.o: /usr/openwin/include/xview/drawable.h
termgraph_tree.o: /usr/openwin/include/xview/attrol.h
termgraph_tree.o: /usr/openwin/include/xview/svrimage.h
termgraph_tree.o: /usr/openwin/include/xview/frame.h
termgraph_tree.o: /usr/openwin/include/xview/openmenu.h
termgraph_tree.o: /usr/openwin/include/xview/panel.h
termgraph_tree.o: /usr/openwin/include/xview/canvas.h
termgraph_tree.o: /usr/openwin/include/xview/openwin.h
termgraph_tree.o: /usr/openwin/include/xview/tty.h
termgraph_tree.o: /usr/openwin/include/xview/text.h
termgraph_tree.o: /usr/openwin/include/xview/textsw.h
termgraph_tree.o: /usr/openwin/include/xview/sel_attrs.h
termgraph_tree.o: /usr/openwin/include/xview/scrollbar.h
termgraph_tree.o: /usr/openwin/include/xview/expandname.h
termgraph_window.o: termgraph_decl.h /usr/include/string.h
termgraph_window.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
termgraph_window.o: /usr/include/ctype.h /usr/include/math.h
termgraph_window.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
termgraph_window.o: ../../sgraph/std.h /usr/include/assert.h
termgraph_window.o: /usr/include/stdio.h /usr/include/malloc.h
termgraph_window.o: ../../sgraph/sgraph.h ../../sgraph/slist.h
termgraph_window.o: ../../sgraph/graphed.h ../../sgraph/graphed_structures.h
termgraph_window.o: /usr/openwin/include/xview/rect.h
termgraph_window.o: /usr/openwin/include/xview/xv_c_types.h
termgraph_window.o: ../../sgraph/dispatch_commands.h
termgraph_window.o: ../../sgraph/sgraph_interface.h
termgraph_window.o: ../../sgraph/sgragra_interface.h
termgraph_window.o: /usr/openwin/include/xview/xview.h
termgraph_window.o: /usr/openwin/include/xview/xview_xvin.h
termgraph_window.o: /usr/include/signal.h /usr/include/sys/signal.h
termgraph_window.o: /usr/include/vm/faultcode.h /usr/include/sys/types.h
termgraph_window.o: /usr/include/sys/sysmacros.h
termgraph_window.o: /usr/include/pixrect/pixrect.h
termgraph_window.o: /usr/include/pixrect/pr_planegroups.h
termgraph_window.o: /usr/include/pixrect/pr_util.h
termgraph_window.o: /usr/include/pixrect/memvar.h
termgraph_window.o: /usr/include/pixrect/pixfont.h
termgraph_window.o: /usr/include/pixrect/traprop.h
termgraph_window.o: /usr/include/pixrect/pr_line.h
termgraph_window.o: /usr/openwin/include/xview/generic.h
termgraph_window.o: /usr/openwin/include/xview/pkg_public.h
termgraph_window.o: /usr/openwin/include/xview/pkg.h
termgraph_window.o: /usr/openwin/include/xview/attr.h
termgraph_window.o: /usr/openwin/include/xview/base.h
termgraph_window.o: /usr/openwin/include/xview/notify.h
termgraph_window.o: /usr/include/sys/wait.h /usr/include/sys/time.h
termgraph_window.o: /usr/include/sys/time.h /usr/include/sys/resource.h
termgraph_window.o: /usr/include/varargs.h
termgraph_window.o: /usr/openwin/include/xview/xv_error.h
termgraph_window.o: /usr/openwin/include/xview/sun.h
termgraph_window.o: /usr/openwin/include/xview/server.h
termgraph_window.o: /usr/openwin/include/xview/screen.h
termgraph_window.o: /usr/openwin/include/xview/pixwin.h
termgraph_window.o: /usr/openwin/include/xview/rectlist.h
termgraph_window.o: /usr/openwin/include/xview/win_input.h
termgraph_window.o: /usr/openwin/include/X11/Xlib.h
termgraph_window.o: /usr/openwin/include/X11/X.h
termgraph_window.o: /usr/openwin/include/xview/win_event.h
termgraph_window.o: /usr/openwin/include/xview/xv_version.h
termgraph_window.o: /usr/openwin/include/xview/icon.h
termgraph_window.o: /usr/openwin/include/xview/window.h
termgraph_window.o: /usr/openwin/include/xview/drawable.h
termgraph_window.o: /usr/openwin/include/xview/attrol.h
termgraph_window.o: /usr/openwin/include/xview/svrimage.h
termgraph_window.o: /usr/openwin/include/xview/frame.h
termgraph_window.o: /usr/openwin/include/xview/openmenu.h
termgraph_window.o: /usr/openwin/include/xview/panel.h
termgraph_window.o: /usr/openwin/include/xview/canvas.h
termgraph_window.o: /usr/openwin/include/xview/openwin.h
termgraph_window.o: /usr/openwin/include/xview/tty.h
termgraph_window.o: /usr/openwin/include/xview/text.h
termgraph_window.o: /usr/openwin/include/xview/textsw.h
termgraph_window.o: /usr/openwin/include/xview/sel_attrs.h
termgraph_window.o: /usr/openwin/include/xview/scrollbar.h
termgraph_window.o: /usr/openwin/include/xview/expandname.h
