############################################
# dstool - complib makefile                #
############################################

include ${DSTOOL}/site_specific/lib_incl.mk
############################################
# Modify the following segment only.       #
############################################
LIBRARY = alglib.a

SOURCES_A = \
	euler.c \
	rk4.c \
	rkqc.c \
	bs.c \
	ab4.c



DEPS_A = $(DSTOOL)/src/include/complib.h \
	$(DSTOOL)/src/include/history.h 

SOURCES_B =

DEPS_B = 

TEST_PROGRAM = 

TEST_SOURCES = 

TEST_DEPS =

##############################################
# The following line should not be modified  #
##############################################

include ${DSTOOL}/site_specific/targetsA.mk

