.TH ASET 1 "Release 1"  "AF Version 3"
.SH NAME
abrowse - X audio file browser
.SH SYNOPSIS
.B abrowse [\fIdir\fP]
.SH DESCRIPTION
This program implements an X based audio file browser.  Double-click to
play files and traverse directories.

You can select different output devices with the "Output Device" option
under the File menu.

If \fIdir\fP is specified, the file window opens with the contents of that
directory.  If not specified, and the environment variable \fISOUND_PATH\fP
is defined, the file window opens on the first directory in that list.
Otherwise, the file window opens on the current directory.

This program is implemented with the Tcl/Tk toolkit, which must be installed 
on your system for the program to run.
.SH RESTRICTIONS
There's no way to stop a playback once it is started.
.SH ENVIRONMENT
.TP 8
.B AUDIOFILE
to get the default host and server to use.
.TP 8
.B SOUND_PATH
specifies a colon-separated list of directories in which sounds may be found.
.SH BUGS
If you encounter a \fBreproducible\fP bug, please 
submit a problem report to (af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1), aplay(1)
.SH COPYRIGHT
Copyright 1992-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHOR
Andrew Payne, Digital Cambridge Research Lab
