/* Top Level Code: Group 7 interface_ui.h */

#ifndef	interface_HEADER
#define	interface_HEADER

/*
 * interface_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `interface.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;

extern Xv_opaque	interface_MainFileMenu_create(caddr_t, Xv_opaque);
extern Xv_opaque	interface_MainChartMenu_create(caddr_t, Xv_opaque);
extern Xv_opaque	interface_MainAnalyzeMenu_create(caddr_t, Xv_opaque);
extern Xv_opaque	interface_MainInsertMenu_create(caddr_t, Xv_opaque);
extern Xv_opaque	interface_MainPasteMenu_create(caddr_t, Xv_opaque);
extern Xv_opaque	interface_MainEditMenu_create(caddr_t, Xv_opaque);
extern Xv_opaque	interface_MainExportMenu_create(caddr_t, Xv_opaque);
extern Xv_opaque	interface_DependInsertMenu_create(caddr_t, Xv_opaque);

typedef struct {
	Xv_opaque	ProjectWindow;
	Xv_opaque	MainWinControls;
	Xv_opaque	MainFileButton;
	Xv_opaque	MainChartButton;
	Xv_opaque	MainAnalyzeButton;
	Xv_opaque	MainExportButton;
	Xv_opaque	TaskLabel;
	Xv_opaque	MainList;
	Xv_opaque	MainInsertButton;
	Xv_opaque	MainEditButton;
} interface_ProjectWindow_objects;

extern interface_ProjectWindow_objects	*interface_ProjectWindow_objects_initialize(interface_ProjectWindow_objects *, Xv_opaque);

extern Xv_opaque	interface_ProjectWindow_ProjectWindow_create(interface_ProjectWindow_objects *, Xv_opaque);
extern Xv_opaque	interface_ProjectWindow_MainWinControls_create(interface_ProjectWindow_objects *, Xv_opaque);
extern Xv_opaque	interface_ProjectWindow_MainFileButton_create(interface_ProjectWindow_objects *, Xv_opaque);
extern Xv_opaque	interface_ProjectWindow_MainChartButton_create(interface_ProjectWindow_objects *, Xv_opaque);
extern Xv_opaque	interface_ProjectWindow_MainAnalyzeButton_create(interface_ProjectWindow_objects *, Xv_opaque);
extern Xv_opaque	interface_ProjectWindow_MainExportButton_create(interface_ProjectWindow_objects *, Xv_opaque);
extern Xv_opaque	interface_ProjectWindow_TaskLabel_create(interface_ProjectWindow_objects *, Xv_opaque);
extern Xv_opaque	interface_ProjectWindow_MainList_create(interface_ProjectWindow_objects *, Xv_opaque);
extern Xv_opaque	interface_ProjectWindow_MainInsertButton_create(interface_ProjectWindow_objects *, Xv_opaque);
extern Xv_opaque	interface_ProjectWindow_MainEditButton_create(interface_ProjectWindow_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	PERTPopup;
	Xv_opaque	canvas1;
} interface_PERTPopup_objects;

extern interface_PERTPopup_objects	*interface_PERTPopup_objects_initialize(interface_PERTPopup_objects *, Xv_opaque);

extern Xv_opaque	interface_PERTPopup_PERTPopup_create(interface_PERTPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_PERTPopup_canvas1_create(interface_PERTPopup_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	GanttPopup;
	Xv_opaque	canvas2;
} interface_GanttPopup_objects;

extern interface_GanttPopup_objects	*interface_GanttPopup_objects_initialize(interface_GanttPopup_objects *, Xv_opaque);

extern Xv_opaque	interface_GanttPopup_GanttPopup_create(interface_GanttPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_GanttPopup_canvas2_create(interface_GanttPopup_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	TaskInfoPopup;
	Xv_opaque	TaskInfoControls;
	Xv_opaque	TaskNameField;
	Xv_opaque	TaskInfoOptions;
	Xv_opaque	TaskDescField;
	Xv_opaque	DurationField;
	Xv_opaque	FloatField;
	Xv_opaque	StartDateLabel;
	Xv_opaque	EndDateLabel;
	Xv_opaque	PlannedStartDateField;
	Xv_opaque	PlannedEndDateField;
	Xv_opaque	ActualStartDateField;
	Xv_opaque	ActualEndDateField;
	Xv_opaque	ForecastStartDateField;
	Xv_opaque	ForecastEndDateField;
	Xv_opaque	EarliestStartDateField;
	Xv_opaque	EarliestEndDateField;
	Xv_opaque	LatestStartDateField;
	Xv_opaque	LatestEndDateField;
	Xv_opaque	TaskInfoDependButton;
	Xv_opaque	TaskInfoSubtaskButton;
	Xv_opaque	TaskInfoResourceButton;
	Xv_opaque	TaskInfoApplyButton;
	Xv_opaque	TaskInfoResetButton;
} interface_TaskInfoPopup_objects;

extern interface_TaskInfoPopup_objects	*interface_TaskInfoPopup_objects_initialize(interface_TaskInfoPopup_objects *, Xv_opaque);

extern Xv_opaque	interface_TaskInfoPopup_TaskInfoPopup_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_TaskInfoControls_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_TaskNameField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_TaskInfoOptions_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_TaskDescField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_DurationField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_FloatField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_StartDateLabel_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_EndDateLabel_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_PlannedStartDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_PlannedEndDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_ActualStartDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_ActualEndDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_ForecastStartDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_ForecastEndDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_EarliestStartDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_EarliestEndDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_LatestStartDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_LatestEndDateField_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_TaskInfoDependButton_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_TaskInfoSubtaskButton_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_TaskInfoResourceButton_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_TaskInfoApplyButton_create(interface_TaskInfoPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_TaskInfoPopup_TaskInfoResetButton_create(interface_TaskInfoPopup_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	DependPopup;
	Xv_opaque	DependencyControl;
	Xv_opaque	DependencyLabel;
	Xv_opaque	DependencyList;
	Xv_opaque	DependInsertButton;
	Xv_opaque	DependEditButton;
	Xv_opaque	DependencyField;
} interface_DependPopup_objects;

extern interface_DependPopup_objects	*interface_DependPopup_objects_initialize(interface_DependPopup_objects *, Xv_opaque);

extern Xv_opaque	interface_DependPopup_DependPopup_create(interface_DependPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_DependPopup_DependencyControl_create(interface_DependPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_DependPopup_DependencyLabel_create(interface_DependPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_DependPopup_DependencyList_create(interface_DependPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_DependPopup_DependInsertButton_create(interface_DependPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_DependPopup_DependEditButton_create(interface_DependPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_DependPopup_DependencyField_create(interface_DependPopup_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	ResourcePopup;
	Xv_opaque	ResourceControl;
	Xv_opaque	ResourceLabel;
	Xv_opaque	ResourceList;
	Xv_opaque	ResourceInsertButton;
	Xv_opaque	ResourceEditButton;
	Xv_opaque	ResourceField;
} interface_ResourcePopup_objects;

extern interface_ResourcePopup_objects	*interface_ResourcePopup_objects_initialize(interface_ResourcePopup_objects *, Xv_opaque);

extern Xv_opaque	interface_ResourcePopup_ResourcePopup_create(interface_ResourcePopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ResourcePopup_ResourceControl_create(interface_ResourcePopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ResourcePopup_ResourceLabel_create(interface_ResourcePopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ResourcePopup_ResourceList_create(interface_ResourcePopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ResourcePopup_ResourceInsertButton_create(interface_ResourcePopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ResourcePopup_ResourceEditButton_create(interface_ResourcePopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ResourcePopup_ResourceField_create(interface_ResourcePopup_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	SubTaskPopup;
	Xv_opaque	SubtaskControl;
	Xv_opaque	SubtaskLabel;
	Xv_opaque	SubtaskList;
	Xv_opaque	SubtaskInsertButton;
	Xv_opaque	SubtaskEditButton;
	Xv_opaque	SubtaskField;
} interface_SubTaskPopup_objects;

extern interface_SubTaskPopup_objects	*interface_SubTaskPopup_objects_initialize(interface_SubTaskPopup_objects *, Xv_opaque);

extern Xv_opaque	interface_SubTaskPopup_SubTaskPopup_create(interface_SubTaskPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_SubTaskPopup_SubtaskControl_create(interface_SubTaskPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_SubTaskPopup_SubtaskLabel_create(interface_SubTaskPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_SubTaskPopup_SubtaskList_create(interface_SubTaskPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_SubTaskPopup_SubtaskInsertButton_create(interface_SubTaskPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_SubTaskPopup_SubtaskEditButton_create(interface_SubTaskPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_SubTaskPopup_SubtaskField_create(interface_SubTaskPopup_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	FileLoadPopup;
	Xv_opaque	controls1;
	Xv_opaque	DirectoryField;
	Xv_opaque	FileLoadList;
	Xv_opaque	FileField;
	Xv_opaque	LoadButton;
} interface_FileLoadPopup_objects;

extern interface_FileLoadPopup_objects	*interface_FileLoadPopup_objects_initialize(interface_FileLoadPopup_objects *, Xv_opaque);

extern Xv_opaque	interface_FileLoadPopup_FileLoadPopup_create(interface_FileLoadPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_FileLoadPopup_controls1_create(interface_FileLoadPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_FileLoadPopup_DirectoryField_create(interface_FileLoadPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_FileLoadPopup_FileLoadList_create(interface_FileLoadPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_FileLoadPopup_FileField_create(interface_FileLoadPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_FileLoadPopup_LoadButton_create(interface_FileLoadPopup_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	ExportOptionsPopup;
	Xv_opaque	controls2;
	Xv_opaque	DirField;
	Xv_opaque	LaTeXFileField;
	Xv_opaque	ExportOptionsApplyButton;
} interface_ExportOptionsPopup_objects;

extern interface_ExportOptionsPopup_objects	*interface_ExportOptionsPopup_objects_initialize(interface_ExportOptionsPopup_objects *, Xv_opaque);

extern Xv_opaque	interface_ExportOptionsPopup_ExportOptionsPopup_create(interface_ExportOptionsPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ExportOptionsPopup_controls2_create(interface_ExportOptionsPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ExportOptionsPopup_DirField_create(interface_ExportOptionsPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ExportOptionsPopup_LaTeXFileField_create(interface_ExportOptionsPopup_objects *, Xv_opaque);
extern Xv_opaque	interface_ExportOptionsPopup_ExportOptionsApplyButton_create(interface_ExportOptionsPopup_objects *, Xv_opaque);
#endif
