/*
 * facman_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `facman.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "facman_ui.h"
#include <group.h>

#include "svfacsw.h"

/*
 * Global object definitions.
 */
facman_mainPopup1_objects	*Facman_mainPopup1;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(argc, argv)
	int	argc;
	char	**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Facman_mainPopup1 = facman_mainPopup1_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	xv_main_loop(Facman_mainPopup1->mainPopup1);
	exit(0);
}

#endif


/*
 * Notify callback function for `quitButton'.
 */
void
facman_mainPopup1_quitButton_notify_callback(item, event)
	Panel_item	item;
	Event		*event;
{
	facman_mainPopup1_objects *ip = (facman_mainPopup1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
#if	0
	fputs("facman: facman_mainPopup1_quitButton_notify_callback\n",
		stderr);
#endif
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	{
		exit(0);	/* requested by Quit button */
	}
	
	/* gxv_end_connections */

}
