#!/bin/sh
## ###################################################################### ##
##         Copyright IBM Corporation 1988,1991 - All Rights Reserved      ##
##        For full copyright information see:'andrew/config/COPYRITE'     ##
## ###################################################################### ##


set -x
DIR=`pwd`
for i in ${3}; do
${1} ${4}/$i
${2} ${DIR}/$i ${4}
done


