/*
 * olxvman_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `olxvman.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "olxvman_ui.h"

/*
 * Create object `OptionMenu' in the specified instance.
 */
Xv_opaque
olxvman_OptionMenu_create(caddr_t ip, Xv_opaque owner)
{
	extern Menu_item	SearchHandler(Menu_item, Menu_generate);
	extern Menu_item	ShowVersionHandler(Menu_item, Menu_generate);
	extern Menu_item	PrintHandler(Menu_item, Menu_generate);
	extern Menu_item	QuitHandler(Menu_item, Menu_generate);
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_TITLE_ITEM, "Options",
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Search...",
			MENU_GEN_PROC, SearchHandler,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Show Version",
			MENU_GEN_PROC, ShowVersionHandler,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Print Current Page",
			MENU_GEN_PROC, PrintHandler,
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Quit",
			MENU_GEN_PROC, QuitHandler,
			NULL,
		MENU_GEN_PIN_WINDOW, owner, "Options",
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `OLXVMan'.
 */
olxvman_OLXVMan_objects *
olxvman_OLXVMan_objects_initialize(olxvman_OLXVMan_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (olxvman_OLXVMan_objects *) calloc(1, sizeof (olxvman_OLXVMan_objects))))
		return (olxvman_OLXVMan_objects *) NULL;
	if (!ip->OLXVMan)
		ip->OLXVMan = olxvman_OLXVMan_OLXVMan_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = olxvman_OLXVMan_controls1_create(ip, ip->OLXVMan);
	if (!ip->OptionButton)
		ip->OptionButton = olxvman_OLXVMan_OptionButton_create(ip, ip->controls1);
	if (!ip->ManualSections)
		ip->ManualSections = olxvman_OLXVMan_ManualSections_create(ip, ip->controls1);
	if (!ip->ManualPages)
		ip->ManualPages = olxvman_OLXVMan_ManualPages_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `OLXVMan' in the specified instance.
 */
Xv_opaque
olxvman_OLXVMan_OLXVMan_create(olxvman_OLXVMan_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	Xv_opaque		OLXVMan_image;
	static unsigned short	OLXVMan_bits[] = {
#include "olxvman.icon"
	};
	
	OLXVMan_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, OLXVMan_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 456,
		XV_HEIGHT, 280,
		XV_LABEL, "OLXV Man",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_ICON, xv_create(XV_NULL, ICON,
			ICON_IMAGE, OLXVMan_image,
			NULL),
		NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
olxvman_OLXVMan_controls1_create(olxvman_OLXVMan_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `OptionButton' in the specified instance.
 */
Xv_opaque
olxvman_OLXVMan_OptionButton_create(olxvman_OLXVMan_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "olxvman:OptionButton",
		XV_X, 8,
		XV_Y, 12,
		PANEL_LABEL_STRING, "Options",
		PANEL_ITEM_MENU, olxvman_OptionMenu_create((caddr_t) ip, ip->OLXVMan),
		NULL);
	return obj;
}

/*
 * Create object `ManualSections' in the specified instance.
 */
Xv_opaque
olxvman_OLXVMan_ManualSections_create(olxvman_OLXVMan_objects *ip, Xv_opaque owner)
{
	extern int		ManualSectionNotify(Panel_item, char *, Xv_opaque, Panel_list_op, Event *, int);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "olxvman:ManualSections",
		XV_X, 4,
		XV_Y, 56,
		PANEL_LIST_WIDTH, 200,
		PANEL_LIST_DISPLAY_ROWS, 10,
		PANEL_LABEL_STRING, "Manual Sections",
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_NOTIFY_PROC, ManualSectionNotify,
		NULL);
	return obj;
}

/*
 * Create object `ManualPages' in the specified instance.
 */
Xv_opaque
olxvman_OLXVMan_ManualPages_create(olxvman_OLXVMan_objects *ip, Xv_opaque owner)
{
	extern int		ManualPageNotify(Panel_item, char *, Xv_opaque, Panel_list_op, Event *, int);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "olxvman:ManualPages",
		XV_X, 232,
		XV_Y, 56,
		PANEL_LIST_WIDTH, 200,
		PANEL_LIST_DISPLAY_ROWS, 10,
		PANEL_LABEL_STRING, "Manual Pages",
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_NOTIFY_PROC, ManualPageNotify,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `SearchPopup'.
 */
olxvman_SearchPopup_objects *
olxvman_SearchPopup_objects_initialize(olxvman_SearchPopup_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (olxvman_SearchPopup_objects *) calloc(1, sizeof (olxvman_SearchPopup_objects))))
		return (olxvman_SearchPopup_objects *) NULL;
	if (!ip->SearchPopup)
		ip->SearchPopup = olxvman_SearchPopup_SearchPopup_create(ip, owner);
	if (!ip->controls2)
		ip->controls2 = olxvman_SearchPopup_controls2_create(ip, ip->SearchPopup);
	if (!ip->SearchField)
		ip->SearchField = olxvman_SearchPopup_SearchField_create(ip, ip->controls2);
	if (!ip->ManualButton)
		ip->ManualButton = olxvman_SearchPopup_ManualButton_create(ip, ip->controls2);
	if (!ip->AproposButton)
		ip->AproposButton = olxvman_SearchPopup_AproposButton_create(ip, ip->controls2);
	return ip;
}

/*
 * Create object `SearchPopup' in the specified instance.
 */
Xv_opaque
olxvman_SearchPopup_SearchPopup_create(olxvman_SearchPopup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 207,
		XV_HEIGHT, 83,
		XV_LABEL, "Manual Search",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls2' in the specified instance.
 */
Xv_opaque
olxvman_SearchPopup_controls2_create(olxvman_SearchPopup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `SearchField' in the specified instance.
 */
Xv_opaque
olxvman_SearchPopup_SearchField_create(olxvman_SearchPopup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "olxvman:SearchField",
		XV_X, 12,
		XV_Y, 8,
		PANEL_VALUE_DISPLAY_LENGTH, 23,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Please enter search string:",
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `ManualButton' in the specified instance.
 */
Xv_opaque
olxvman_SearchPopup_ManualButton_create(olxvman_SearchPopup_objects *ip, Xv_opaque owner)
{
	extern void		SearchNotify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "olxvman:ManualButton",
		XV_X, 8,
		XV_Y, 56,
		PANEL_LABEL_STRING, "Manual Page",
		PANEL_NOTIFY_PROC, SearchNotify,
		NULL);
	return obj;
}

/*
 * Create object `AproposButton' in the specified instance.
 */
Xv_opaque
olxvman_SearchPopup_AproposButton_create(olxvman_SearchPopup_objects *ip, Xv_opaque owner)
{
	extern void		SearchNotify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "olxvman:AproposButton",
		XV_X, 128,
		XV_Y, 56,
		PANEL_LABEL_STRING, "Apropos",
		PANEL_NOTIFY_PROC, SearchNotify,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `ManualPagePopup'.
 */
olxvman_ManualPagePopup_objects *
olxvman_ManualPagePopup_objects_initialize(olxvman_ManualPagePopup_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (olxvman_ManualPagePopup_objects *) calloc(1, sizeof (olxvman_ManualPagePopup_objects))))
		return (olxvman_ManualPagePopup_objects *) NULL;
	if (!ip->ManualPagePopup)
		ip->ManualPagePopup = olxvman_ManualPagePopup_ManualPagePopup_create(ip, owner);
	if (!ip->ManualPageText)
		ip->ManualPageText = olxvman_ManualPagePopup_ManualPageText_create(ip, ip->ManualPagePopup);
	return ip;
}

/*
 * Create object `ManualPagePopup' in the specified instance.
 */
Xv_opaque
olxvman_ManualPagePopup_ManualPagePopup_create(olxvman_ManualPagePopup_objects *ip, Xv_opaque owner)
{
	extern void	ManualPagePinned(Frame);
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 506,
		XV_HEIGHT, 675,
		XV_LABEL, "Manual Page",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		FRAME_DONE_PROC, ManualPagePinned,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `ManualPageText' in the specified instance.
 */
Xv_opaque
olxvman_ManualPagePopup_ManualPageText_create(olxvman_ManualPagePopup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, TEXTSW,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "olxvman:ManualPageText",
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		OPENWIN_SHOW_BORDERS, TRUE,
		TEXTSW_BROWSING, TRUE,
		TEXTSW_DISABLE_LOAD, TRUE,
		NULL);
	return obj;
}

