/* DO NOT EDIT THIS FILE.  It contains C->PostScript communication
   definitions that were automatically generated from psinter.cps */

short currentcanvas, currentfont;
#define ps_usecanvas(canvas) ((canvas) != currentcanvas ? ps_DO_usecanvas(currentcanvas = (canvas)) : 0)
#define ps_DO_usecanvas(P__0)  pprintf(PostScript, _CPS_ps_DO_usecanvas, 6, P__0)
extern char _CPS_ps_DO_usecanvas[];
#define ps_usefont(font) ((font) != currentfont ? ps_DO_usefont(currentfont = (font)) : 0)
#define ps_DO_usefont(P__0)  pprintf(PostScript, _CPS_ps_DO_usefont, 3, P__0)
extern char _CPS_ps_DO_usefont[];
#define ps_defstr(P__0,P__1,P__2,P__3,P__4,P__5) ( pprintf(PostScript, _CPS_ps_defstr, 13, P__0, P__1, P__2), ps_waitfor(PostScriptInput, 0), _CPS_RETURN_ps_defstr(P__4, P__5, P__3))
#define _CPS_RETURN_ps_defstr(P__4, P__5, P__3) pscanf(PostScriptInput,"ddd", P__4, P__5, P__3)
extern char _CPS_ps_defstr[];
#define ps_getint(P__0) (_CPS_RETURN_ps_getint(P__0))
#define _CPS_RETURN_ps_getint(P__0) pscanf(PostScriptInput,"e", P__0)
#define ps_makewindow(P__0,P__1)  pprintf(PostScript, _CPS_ps_makewindow, 8, P__0, P__1)
extern char _CPS_ps_makewindow[];
#define ps_destroywindow(P__0)  pprintf(PostScript, _CPS_ps_destroywindow, 18, P__0)
extern char _CPS_ps_destroywindow[];
#define ps_redraw(P__0,P__1,P__2) (ps_lookingat(PostScriptInput, 1) && (_CPS_RETURN_ps_redraw(P__0, P__2, P__1), 1))
#define _CPS_RETURN_ps_redraw(P__0, P__2, P__1) pscanf(PostScriptInput,"ddd", P__0, P__2, P__1)
#define ps_keyboard(P__0,P__1) (ps_lookingat(PostScriptInput, 2) && (_CPS_RETURN_ps_keyboard(P__0, P__1), 1))
#define _CPS_RETURN_ps_keyboard(P__0, P__1) pscanf(PostScriptInput,"dd", P__0, P__1)
#define ps_mouse(P__0,P__1,P__2,P__3) (ps_lookingat(PostScriptInput, 3) && (_CPS_RETURN_ps_mouse(P__0, P__1, P__2, P__3), 1))
#define _CPS_RETURN_ps_mouse(P__0, P__1, P__2, P__3) pscanf(PostScriptInput,"dddd", P__0, P__1, P__2, P__3)
#define ps_scroll(P__0,P__1) (ps_lookingat(PostScriptInput, 4) && (_CPS_RETURN_ps_scroll(P__0, P__1), 1))
#define _CPS_RETURN_ps_scroll(P__0, P__1) pscanf(PostScriptInput,"dd", P__0, P__1)
#define ps_thumb(P__0,P__1) (ps_lookingat(PostScriptInput, 5) && (_CPS_RETURN_ps_thumb(P__0, P__1), 1))
#define _CPS_RETURN_ps_thumb(P__0, P__1) pscanf(PostScriptInput,"de", P__0, P__1)
#define ps_setscroll(P__0,P__1)  pprintf(PostScript, _CPS_ps_setscroll, 8, P__1, P__0)
extern char _CPS_ps_setscroll[];
#define ps_startup()  pprintf(PostScript, _CPS_ps_startup, 2540)
extern char _CPS_ps_startup[];
#define ps_startredraw(P__0)  pprintf(PostScript, _CPS_ps_startredraw, 6, P__0)
extern char _CPS_ps_startredraw[];
#define ps_endredraw()  pprintf(PostScript, _CPS_ps_endredraw, 4)
extern char _CPS_ps_endredraw[];
#define ps_cwidthshow(P__0,P__1,L__1)  pprintf(PostScript, _CPS_ps_cwidthshow, 10, P__0, L__1, P__1)
extern char _CPS_ps_cwidthshow[];
#define ps_cashow(P__0,P__1,L__1)  pprintf(PostScript, _CPS_ps_cashow, 8, P__0, L__1, P__1)
extern char _CPS_ps_cashow[];
#define ps_cawidthshow(P__0,P__1,P__2,L__2)  pprintf(PostScript, _CPS_ps_cawidthshow, 14, P__1, P__0, L__2, P__2)
extern char _CPS_ps_cawidthshow[];
#define ps_eraserect(P__0,P__1,P__2,P__3)  pprintf(PostScript, _CPS_ps_eraserect, 12, P__2, P__3, P__0, P__1)
extern char _CPS_ps_eraserect[];
#define ps_frmoveto(P__0,P__1)  pprintf(PostScript, _CPS_ps_frmoveto, 5, P__0, P__1)
extern char _CPS_ps_frmoveto[];
#define ps_frlineto(P__0,P__1)  pprintf(PostScript, _CPS_ps_frlineto, 5, P__0, P__1)
extern char _CPS_ps_frlineto[];
#define ps_frdrawcaret(P__0,P__1)  pprintf(PostScript, _CPS_ps_frdrawcaret, 8, P__0, P__1)
extern char _CPS_ps_frdrawcaret[];
#define ps_startselect()  pprintf(PostScript, _CPS_ps_startselect, 5)
extern char _CPS_ps_startselect[];
#define ps_endselect()  pprintf(PostScript, _CPS_ps_endselect, 2)
extern char _CPS_ps_endselect[];
#define _CPS_SEENDEFS
#ifndef FILE
#include <stdio.h>
#endif
#ifndef PSFILE
#include <psio.h>
#endif
extern PSFILE *PostScript, *PostScriptInput;
PSFILE *ps_open_PostScript();
#define ps_flush_PostScript() (psio_flush(PostScript),(psio_error(PostScript) ? exit(0) : 0))
#define ps_close_PostScript() (psio_close(PostScript),PostScript = 0)
#define ps_moveto(P__0,P__1)  pprintf(PostScript, _CPS_ps_moveto, 5, P__0, P__1)
extern char _CPS_ps_moveto[];
#define ps_rmoveto(P__0,P__1)  pprintf(PostScript, _CPS_ps_rmoveto, 5, P__0, P__1)
extern char _CPS_ps_rmoveto[];
#define ps_lineto(P__0,P__1)  pprintf(PostScript, _CPS_ps_lineto, 5, P__0, P__1)
extern char _CPS_ps_lineto[];
#define ps_rlineto(P__0,P__1)  pprintf(PostScript, _CPS_ps_rlineto, 5, P__0, P__1)
extern char _CPS_ps_rlineto[];
#define ps_closepath() psio_putc('\263', PostScript)
#define ps_arc(P__0,P__1,P__2,P__3,P__4)  pprintf(PostScript, _CPS_ps_arc, 11, P__0, P__1, P__2, P__3, P__4)
extern char _CPS_ps_arc[];
#define ps_stroke() psio_putc('\305', PostScript)
#define ps_fill() psio_putc('\267', PostScript)
#define ps_show(P__0)  pprintf(PostScript, _CPS_ps_show, 3, P__0)
extern char _CPS_ps_show[];
#define ps_cshow(P__0,L__0)  pprintf(PostScript, _CPS_ps_cshow, 4, L__0, P__0)
extern char _CPS_ps_cshow[];
#define ps_findfont(P__0)  pprintf(PostScript, _CPS_ps_findfont, 3, P__0)
extern char _CPS_ps_findfont[];
#define ps_scalefont(P__0)  pprintf(PostScript, _CPS_ps_scalefont, 3, P__0)
extern char _CPS_ps_scalefont[];
#define ps_setfont() psio_putc('\302', PostScript)
#define ps_gsave() psio_putc('\272', PostScript)
#define ps_grestore() psio_putc('\271', PostScript)
extern int ps_next_user_token;
#define ps_define_stack_token(u) ps_DO_defuser(u/**/_token = ps_next_user_token++)
#define ps_define_value_token(u) (pprintf(PostScript, "/u load ", sizeof "/u load " - 1), \
ps_define_stack_token(u))
#define ps_define_word_token(u) (pprintf(PostScript, "/u cvx ", sizeof "/u cvx " - 1), \
ps_define_stack_token(u))
#define ps_DO_defuser(P__0)  pprintf(PostScript, _CPS_ps_DO_defuser, 4, P__0)
extern char _CPS_ps_DO_defuser[];
#define ps_DO_finddef(P__0,P__1)  pprintf(PostScript, _CPS_ps_DO_finddef, 7, P__0, P__1)
extern char _CPS_ps_DO_finddef[];
#define ps_finddef(font,usertoken) ps_DO_finddef(font,(usertoken)=ps_next_user_token++)
#define ps_DO_scaledef(P__0,P__1,P__2)  pprintf(PostScript, _CPS_ps_DO_scaledef, 9, P__0, P__1, P__2)
extern char _CPS_ps_DO_scaledef[];
#define ps_scaledef(font,scale,usertoken) ps_DO_scaledef(font,scale,(usertoken) = ps_next_user_token++)
#define ps_usetfont(P__0)  pprintf(PostScript, _CPS_ps_usetfont, 3, P__0)
extern char _CPS_ps_usetfont[];
