/*  -------------------------------------------------------------------

This program is the property of:

                             Cornell University 
                        Center for Applied Mathematics 
                              Ithaca, NY 14853

and may be used, modified and distributed freely, subject to the 
following restrictions:

       Any product which incorporates source code from the dstool
       program or utilities, in whole or in part, is distributed
       with a copy of that source code, including this notice. You
       must give the recipients all the rights that you have with
       respect to the use of this software. Modifications of the
       software must carry prominent notices stating who changed
       the files and the date of any change.

DsTool is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of FITNESS 
FOR A PARTICULAR PURPOSE.  The software is provided as is without 
any obligation on the part of Cornell faculty, staff or students to 
assist in its use, correction, modification or enhancement.

  -----------------------------------------------------------------  */
#ifndef	oned_HEADER
#define	oned_HEADER

/*
 * oned_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `oned.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	win;
	Xv_opaque	pan;
	Xv_opaque	points;
	Xv_opaque	iter;
	Xv_opaque	sketch;
	Xv_opaque	diagonal;
	Xv_opaque	clear;
	Xv_opaque	forward;
	Xv_opaque	backward;
	Xv_opaque       contin;
} oned_win_objects;

extern oned_win_objects	*oned_win_objects_initialize();

extern Xv_opaque	oned_win_win_create();
extern Xv_opaque	oned_win_pan_create();
extern Xv_opaque	oned_win_points_create();
extern Xv_opaque	oned_win_iter_create();
extern Xv_opaque	oned_win_sketch_create();
extern Xv_opaque	oned_win_diagonal_create();
extern Xv_opaque	oned_win_clear_create();
extern Xv_opaque	oned_win_forward_create();
extern Xv_opaque	oned_win_backward_create();
extern Xv_opaque	oned_win_continue_create();
#endif
