# (C) Universitaet Passau, Michael Himsolt 1986-1991
#########################################################################
#									#
#			    GRAPHED MAKEFILE				#
#									#
#########################################################################


#
# Directories
#
GRAPHEDDIR = ../..
#
# Sourcefiles
#
CSOURCES = connect1.c connect1_calls.c
HSOURCES = 

MYFILES = $(HSOURCES) $(CSOURCES)

MODULE = connect

include ../makefile.template
include $(GRAPHEDDIR)/makefile.template


# DO NOT DELETE THIS LINE -- make depend depends on it.

connect1.o: ../../sgraph/std.h /usr/include/assert.h /usr/include/stdio.h
connect1.o: /usr/include/malloc.h ../../sgraph/slist.h ../../sgraph/sgraph.h
connect1_calls.o: ../../sgraph/std.h /usr/include/assert.h
connect1_calls.o: /usr/include/stdio.h /usr/include/malloc.h
connect1_calls.o: ../../sgraph/slist.h ../../sgraph/sgraph.h
connect1_calls.o: ../../sgraph/graphed.h ../../sgraph/graphed_structures.h
connect1_calls.o: /usr/openwin/include/xview/rect.h
connect1_calls.o: /usr/openwin/include/xview/xv_c_types.h
connect1_calls.o: ../../sgraph/dispatch_commands.h
connect1_calls.o: ../../sgraph/sgraph_interface.h
connect1_calls.o: ../../sgraph/sgragra_interface.h ../../sgraph/algorithms.h
