.TH aprop 1 "Release 1"  "AF Version 3"
.SH NAME
aprop - property displayer for AF
.SH SYNOPSIS
.B
aprop 
[\fB\-d\fP \fIdevice\fP]
[\fB\-s\fP \fIdevice\fP]
[\fB\-remove\fP \fIproperty-name\fP]
[\fB\-notype\fP]
[\fB\-spy\fP]
.SH DESCRIPTION
The \fbaprop\fP utility is for displaying properties in an AF server.
.SH OPTIONS
.TP 8
.B \-d \fIdevice\fP
Specifies which audio device to show properties from.
If \fIdevice\fP is not specified, \fIaprop\fP 
defaults to device 0.
.TP 8
.B \-s \fIdevice\fP
Specifies which AF server to use.
.TP 8
.B \-remove \fIproperty-name\fP
Specifies the name of a property to remove.
.TP 8
.B \-spy
Examine window properties forever, looking for property change events.
.TP 8
.B \-notype
Specifies that the type of each property should not be displayed.
.SH ENVIRONMENT
.TP 15
.B AUDIOFILE
specifies the host and server to use.
.SH BUGS
No attempt is made to decode property values:  everything is assumed to be
a zero terminated string.
.PP
If you encounter a \fBreproducible\fP bug, please submit a problem report to
(af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1), arecord(1)
.SH COPYRIGHT
Copyright 1992-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Digital Cambridge Research Lab
