.TH radio_mcast 1
.SH Name
radio_mcast - a radio multicast server
.SH Synopsis
.B
radio_mcast [ options ]
.SH Description
.PP
This program takes a stream of audio input from stdin,
and uses the ULTRIX packet-filter to multicast data on to the Ethernet.
The radio_recv client can be used to listen for the data, and then send
it to a AF client such as aplay or xplay.  The program only
works on machines that have kernel support for the ULTRIX packet-filter.
.SH Options
.TP
.B \-m \fIaddress\fP
.IP 
Specify the ethernet multicast address to use, the default
is ab-00-00-12-34-00.
.TP
.B \-r \fIrate\fP
.IP
Specify the sample rate of the audio source, the
default is 8000 samples per second.
.TP
.B \-s \fIsize\fP    
.IP
Specify the sample size of the audio source, the default is 8 bits per
sample.
.TP
.B \-i \fIinterface\fP        
.IP
Specify the interface name of the ethernet device, the default name is
ln0.
.SH Bugs
None known.
.SH Author
Alec Wolman
.SH Copyright
Copyright 1990, 1991 Digital Equipment Corporation.
