.TH radio_recv 1
.SH Name
radio_recv - a radio multicast receiver
.SH Synopsis
.B
radio_recv [ options ]
.SH Description
.PP
This program takes a stream of multicast data from the Ethernet (that
was sent by radio_mcast), and sends it to stdout.  The data can either
be redirected to a file, or piped in to an AF client such as
aplay or xplay.  It uses the ULTRIX packet-filter to receive the multicast
data from the Ethernet. This program only works on machines that have
kernel support for the ULTRIX packet-filter.
.SH Options
.TP
.B \-m \fIaddress\fP
.IP 
Specify the ethernet multicast address to listen on, the default
is ab-00-00-12-34-00.
.TP
.B \-i \fIinterface\fP        
.IP
Specify the interface name of the ethernet device, the default name is
ln0.
.SH Bugs
None known.
.SH Author
Alec Wolman
.SH Copyright
Copyright 1990, 1991 Digital Equipment Corporation.
