CC=cc
INCLUDES=-I$(OPENWINHOME)/include
#
# Use -DPAN_DND if you have XView 3.0 or greater (includes drag and drop)
# Use -DHAS_STDLIB if you have stdlib.h (declares malloc() & getenv())
# Use -DSUNOS4 for XView 3.2 on SunOS 4.x (as opposed to Solaris 2.x)
# Use -DBSD if compiling on BSD UNIX
#
CFLAGS=$(INCLUDES) -g -DPAN_DND -DHAS_STDLIB -DSUNOS4

SRCS=pan.c control.c event.c folder.c hidexp.c llm.c menu.c misc.c move.c \
	note.c parser.c rmfolder.c noteaction.c search.c update.c win.c work.c\
	dnd.c
OBJS=pan.o control.o event.o folder.o hidexp.o llm.o menu.o misc.o move.o \
	note.o parser.o rmfolder.o noteaction.o search.o update.o win.o work.o\
	dnd.o
LIBS=-L$(OPENWINHOME)/lib -lxview -lolgx -lX11
TARGET=pan

$(TARGET) : $(OBJS)
	$(CC) -o $(TARGET) $(OBJS) $(LIBS)

pan.o : pan.c pan.icon panmain.icon

$(OBJS) : pan.h

clean:
	rm -f core lint.out tags $(TARGET) $(OBJS)

tags : $(SRCS) pan.h
	ctags -t *.[ch]

lint:
	lint $(INCLUDES) $(SRCS) > lint.out
