.TH AIMAKE 1 "Release 1" "AF Version 3"
.SH NAME
aimake \- simple interface to the imake utility for generating AF Makefiles
.SH SYNOPSIS
.B aimake
[
.B \-i
] [ AF source toplevel directory ]
.SH DESCRIPTION
The
.I aimake
command runs the
.I imake
command with the appropriate options to generate an AF Makefile from
an Imakefile in the current directory.
.SH OPTIONS
.TP 5
.B \-i
This option passes the
.I -DCompileWithInstalled
option to 
.I imake, 
which tells it to use the installed versions of the
AF include files, libraries and commands rather than the
ones in the source tree. Note that some environments may
have already set this option in their
.I site.def
configuration file, so it may be the default.
.SH ARGUMENTS
The location of the AF windows source directory on your system.
The default is whatever was set when 
.I aimake
was installed, and should be correct.
.SH "ENVIRONMENT VARIABLES"
Same as
.I imake
.SH "SEE ALSO"
imake(1), make(1)
.br
S. I. Feldman
.I
Make \- A Program for Maintaining Computer Programs
.br
Mark Moraes,
.I
An Imake tutorial
.SH "BUGS"
Should accept more 
.I imake
options and pass them on to
.I imake.
