/*
 * faxtool_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `faxtool.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <xview/dragdrop.h>
#include <xview/cursor.h>
#include <gdd.h>
#include <gcm.h>
#include <group.h>
#include "faxtool_ui.h"

/*
 * Initialize an instance of object `window1'.
 */
faxtool_window1_objects *
faxtool_window1_objects_initialize(faxtool_window1_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (faxtool_window1_objects *) calloc(1, sizeof (faxtool_window1_objects))))
		return (faxtool_window1_objects *) NULL;
	if (!ip->window1)
		ip->window1 = faxtool_window1_window1_create(ip, owner);
	if (!ip->top_controls)
		ip->top_controls = faxtool_window1_top_controls_create(ip, ip->window1);
	if (!ip->mode)
		ip->mode = faxtool_window1_mode_create(ip, ip->top_controls);
	if (!ip->drop_target)
		ip->drop_target = faxtool_window1_drop_target_create(ip, ip->top_controls);
	if (!ip->props_button)
		ip->props_button = faxtool_window1_props_button_create(ip, ip->top_controls);
	if (!ip->top_objects)
		ip->top_objects = faxtool_window1_top_objects_create(ip, ip->top_controls);
	window_fit(ip->top_controls);
	
	if (!ip->send_controls)
		ip->send_controls = faxtool_window1_send_controls_create(ip, ip->window1);
	if (!ip->cover)
		ip->cover = faxtool_window1_cover_create(ip, ip->send_controls);
	if (!ip->directory_button)
		ip->directory_button = faxtool_window1_directory_button_create(ip, ip->send_controls);
	if (!ip->add_dir_button)
		ip->add_dir_button = faxtool_window1_add_dir_button_create(ip, ip->send_controls);
	if (!ip->cover_top_objects)
		ip->cover_top_objects = faxtool_window1_cover_top_objects_create(ip, ip->send_controls);
	if (!ip->fax)
		ip->fax = faxtool_window1_fax_create(ip, ip->send_controls);
	if (!ip->to)
		ip->to = faxtool_window1_to_create(ip, ip->send_controls);
	if (!ip->company)
		ip->company = faxtool_window1_company_create(ip, ip->send_controls);
	if (!ip->re)
		ip->re = faxtool_window1_re_create(ip, ip->send_controls);
	if (!ip->comments)
		ip->comments = faxtool_window1_comments_create(ip, ip->send_controls);
	if (!ip->coverpage)
		ip->coverpage = faxtool_window1_coverpage_create(ip, ip->send_controls);
	if (!ip->file_list)
		ip->file_list = faxtool_window1_file_list_create(ip, ip->send_controls);
	if (!ip->files_button)
		ip->files_button = faxtool_window1_files_button_create(ip, ip->send_controls);
	if (!ip->file_objects)
		ip->file_objects = faxtool_window1_file_objects_create(ip, ip->send_controls);
	if (!ip->resolution)
		ip->resolution = faxtool_window1_resolution_create(ip, ip->send_controls);
	if (!ip->page_size)
		ip->page_size = faxtool_window1_page_size_create(ip, ip->send_controls);
	if (!ip->notify)
		ip->notify = faxtool_window1_notify_create(ip, ip->send_controls);
	if (!ip->time_unit)
		ip->time_unit = faxtool_window1_time_unit_create(ip, ip->send_controls);
	if (!ip->send)
		ip->send = faxtool_window1_send_create(ip, ip->send_controls);
	if (!ip->time)
		ip->time = faxtool_window1_time_create(ip, ip->send_controls);
	if (!ip->send_time)
		ip->send_time = faxtool_window1_send_time_create(ip, ip->send_controls);
	if (!ip->options)
		ip->options = faxtool_window1_options_create(ip, ip->send_controls);
	if (!ip->send_button)
		ip->send_button = faxtool_window1_send_button_create(ip, ip->send_controls);
	if (!ip->preview_button)
		ip->preview_button = faxtool_window1_preview_button_create(ip, ip->send_controls);
	if (!ip->send_lower_left_buttons)
		ip->send_lower_left_buttons = faxtool_window1_send_lower_left_buttons_create(ip, ip->send_controls);
	if (!ip->clear_button)
		ip->clear_button = faxtool_window1_clear_button_create(ip, ip->send_controls);
	if (!ip->reset_button)
		ip->reset_button = faxtool_window1_reset_button_create(ip, ip->send_controls);
	if (!ip->send_lower_right_buttons)
		ip->send_lower_right_buttons = faxtool_window1_send_lower_right_buttons_create(ip, ip->send_controls);
	if (!ip->send_lower_buttons)
		ip->send_lower_buttons = faxtool_window1_send_lower_buttons_create(ip, ip->send_controls);
	if (!ip->send_objects)
		ip->send_objects = faxtool_window1_send_objects_create(ip, ip->send_controls);
	window_fit(ip->send_controls);
	
	if (!ip->status_controls)
		ip->status_controls = faxtool_window1_status_controls_create(ip, ip->window1);
	if (!ip->query_mode)
		ip->query_mode = faxtool_window1_query_mode_create(ip, ip->status_controls);
	if (!ip->query_type)
		ip->query_type = faxtool_window1_query_type_create(ip, ip->status_controls);
	if (!ip->query_objects)
		ip->query_objects = faxtool_window1_query_objects_create(ip, ip->status_controls);
	if (!ip->jobs_list)
		ip->jobs_list = faxtool_window1_jobs_list_create(ip, ip->status_controls);
	if (!ip->status_view_button)
		ip->status_view_button = faxtool_window1_status_view_button_create(ip, ip->status_controls);
	if (!ip->status_print_button)
		ip->status_print_button = faxtool_window1_status_print_button_create(ip, ip->status_controls);
	if (!ip->job_queue_left_buttons)
		ip->job_queue_left_buttons = faxtool_window1_job_queue_left_buttons_create(ip, ip->status_controls);
	if (!ip->modify_button)
		ip->modify_button = faxtool_window1_modify_button_create(ip, ip->status_controls);
	if (!ip->delete_button)
		ip->delete_button = faxtool_window1_delete_button_create(ip, ip->status_controls);
	if (!ip->job_queue_right_buttons)
		ip->job_queue_right_buttons = faxtool_window1_job_queue_right_buttons_create(ip, ip->status_controls);
	if (!ip->job_queue_buttons)
		ip->job_queue_buttons = faxtool_window1_job_queue_buttons_create(ip, ip->status_controls);
	if (!ip->job_queue_objects)
		ip->job_queue_objects = faxtool_window1_job_queue_objects_create(ip, ip->status_controls);
	if (!ip->status_send_mode)
		ip->status_send_mode = faxtool_window1_status_send_mode_create(ip, ip->status_controls);
	if (!ip->status_send_time_unit)
		ip->status_send_time_unit = faxtool_window1_status_send_time_unit_create(ip, ip->status_controls);
	if (!ip->status_send)
		ip->status_send = faxtool_window1_status_send_create(ip, ip->status_controls);
	if (!ip->status_send_time)
		ip->status_send_time = faxtool_window1_status_send_time_create(ip, ip->status_controls);
	if (!ip->status_send_time_objects)
		ip->status_send_time_objects = faxtool_window1_status_send_time_objects_create(ip, ip->status_controls);
	if (!ip->reschedule_objects)
		ip->reschedule_objects = faxtool_window1_reschedule_objects_create(ip, ip->status_controls);
	if (!ip->status_notify)
		ip->status_notify = faxtool_window1_status_notify_create(ip, ip->status_controls);
	if (!ip->status_lower_objects)
		ip->status_lower_objects = faxtool_window1_status_lower_objects_create(ip, ip->status_controls);
	if (!ip->status_objects)
		ip->status_objects = faxtool_window1_status_objects_create(ip, ip->status_controls);
	window_fit(ip->status_controls);
	
	window_fit(ip->window1);
	
	xv_set(ip->top_controls, XV_WIDTH, WIN_EXTEND_TO_EDGE, NULL);
	xv_set(ip->send_controls,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	xv_set(ip->status_controls,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `window1' in the specified instance.
 */
Xv_opaque
faxtool_window1_window1_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern Notify_value	faxtool_window1_event_callback(Xv_window, Event *, Notify_arg, Notify_event_type);
	Xv_opaque	obj;
	Xv_opaque		window1_image;
	static unsigned short	window1_bits[] = {
#include "faxtool.icon"
	};
	Xv_opaque		window1_image_mask;
	static unsigned short	window1_mask_bits[] = {
#include "faxtool_mask.icon"
	};
	
	window1_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, window1_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	window1_image_mask = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, window1_mask_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 600,
		XV_HEIGHT, 700,
		XV_LABEL, "Fax Tool",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_ICON, xv_create(XV_NULL, ICON,
			ICON_IMAGE, window1_image,
			ICON_MASK_IMAGE, window1_image_mask,
			XV_LABEL, "FaxTool",
			NULL),
		NULL);
	xv_set(obj, WIN_CONSUME_EVENTS,
		NULL, NULL);
	notify_interpose_event_func(obj,
		(Notify_func) faxtool_window1_event_callback, NOTIFY_SAFE);
	return obj;
}

/*
 * Create object `top_controls' in the specified instance.
 */
Xv_opaque
faxtool_window1_top_controls_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:top_controls",
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 57,
		WIN_BORDER, TRUE,
		NULL);
	gcm_initialize_colors(obj, NULL, NULL);
	return obj;
}

/*
 * Create object `mode' in the specified instance.
 */
Xv_opaque
faxtool_window1_mode_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_mode_notify_callback(Panel_item, int, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:mode",
		XV_X, 214,
		XV_Y, 17,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Mode:",
		PANEL_NOTIFY_PROC, faxtool_window1_mode_notify_callback,
		PANEL_CHOICE_STRINGS,
			"Send Fax",
			"Status",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("white"),
		NULL);
	return obj;
}

/*
 * Create object `drop_target' in the specified instance.
 */
Xv_opaque
faxtool_window1_drop_target_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void	drop_notify(Xv_opaque, Event *, GDD_DROP_INFO *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_DROP_TARGET,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:drop_target",
		XV_X, 572,
		XV_Y, 17,
		PANEL_DROP_SITE_DEFAULT, TRUE,
		PANEL_ITEM_COLOR, gcm_color_index("firebrick"),
		NULL);
	
	xv_set(obj,
		PANEL_NOTIFY_PROC, gdd_drop_target_notify_proc,
		NULL);
		
	gdd_register_drop_target(obj, drop_notify, NULL);
	return obj;
}

/*
 * Create object `props_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_props_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_props_button_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:props_button",
		XV_X, 11,
		XV_Y, 19,
		PANEL_ITEM_COLOR, gcm_color_index("white"),
		PANEL_LABEL_STRING, "Properties...",
		PANEL_NOTIFY_PROC, faxtool_window1_props_button_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `top_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_top_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 11,
		XV_Y, 17,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->mode,
			ip->drop_target,
			ip->props_button,
			NULL,
		GROUP_ANCHOR_OBJ, ip->top_controls,
		GROUP_ANCHOR_POINT, GROUP_CENTER,
		GROUP_REFERENCE_POINT, GROUP_CENTER,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 0,
		NULL);
	return obj;
}

/*
 * Create object `send_controls' in the specified instance.
 */
Xv_opaque
faxtool_window1_send_controls_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:send_controls",
		XV_X, 0,
		XV_Y, (int)xv_get(ip->top_controls, XV_Y) +
		      (int)xv_get(ip->top_controls, XV_HEIGHT) + 2,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, TRUE,
		NULL);
	gcm_initialize_colors(obj, NULL, NULL);
	return obj;
}

/*
 * Create object `cover' in the specified instance.
 */
Xv_opaque
faxtool_window1_cover_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_cover_notify_callback(Panel_item, int, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:cover",
		XV_X, 100,
		XV_Y, 25,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, "Coverpage?:",
		PANEL_NOTIFY_PROC, faxtool_window1_cover_notify_callback,
		PANEL_CHOICE_STRINGS,
			"No",
			"Yes",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("Yellow"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("white"),
		PANEL_DEFAULT_VALUE, 1,
		PANEL_VALUE, 1,
		NULL);
	return obj;
}

/*
 * Create object `directory_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_directory_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_directory_button_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:directory_button",
		XV_X, 267,
		XV_Y, 27,
		PANEL_ITEM_COLOR, gcm_color_index("white"),
		PANEL_LABEL_STRING, "Directory...",
		PANEL_NOTIFY_PROC, faxtool_window1_directory_button_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `add_dir_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_add_dir_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		add_dir_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:add_dir_button",
		XV_X, 369,
		XV_Y, 27,
		PANEL_ITEM_COLOR, gcm_color_index("Green"),
		PANEL_LABEL_STRING, "Add To Directory",
		PANEL_NOTIFY_PROC, add_dir_notify,
		NULL);
	return obj;
}

/*
 * Create object `cover_top_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_cover_top_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 100,
		XV_Y, 25,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->cover,
			ip->directory_button,
			ip->add_dir_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 20,
		NULL);
	return obj;
}

/*
 * Create object `fax' in the specified instance.
 */
Xv_opaque
faxtool_window1_fax_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:fax",
		XV_X, 98,
		XV_Y, 58,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 25,
		PANEL_LABEL_STRING, "Fax Number:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `to' in the specified instance.
 */
Xv_opaque
faxtool_window1_to_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:to",
		XV_X, 140,
		XV_Y, 83,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Name:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `company' in the specified instance.
 */
Xv_opaque
faxtool_window1_company_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:company",
		XV_X, 115,
		XV_Y, 108,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Company:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `re' in the specified instance.
 */
Xv_opaque
faxtool_window1_re_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:re",
		XV_X, 110,
		XV_Y, 133,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Regarding:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `comments' in the specified instance.
 */
Xv_opaque
faxtool_window1_comments_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MULTILINE_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:comments",
		XV_X, 106,
		XV_Y, 158,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 512,
		PANEL_DISPLAY_ROWS, 6,
		PANEL_LABEL_STRING, "Comments:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `coverpage' in the specified instance.
 */
Xv_opaque
faxtool_window1_coverpage_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 98,
		XV_Y, 25,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->cover_top_objects,
			ip->fax,
			ip->to,
			ip->company,
			ip->re,
			ip->comments,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `file_list' in the specified instance.
 */
Xv_opaque
faxtool_window1_file_list_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:file_list",
		XV_X, 66,
		XV_Y, 272,
		PANEL_LIST_WIDTH, 450,
		PANEL_LIST_DISPLAY_ROWS, 4,
		PANEL_LIST_TITLE, "Files To Transmit               ",
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_CHOOSE_ONE, FALSE,
		PANEL_CHOOSE_NONE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `files_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_files_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		browse_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:files_button",
		XV_X, 253,
		XV_Y, 398,
		PANEL_ITEM_COLOR, gcm_color_index("white"),
		PANEL_LABEL_STRING, "Select Files...",
		PANEL_NOTIFY_PROC, browse_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `file_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_file_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 66,
		XV_Y, 272,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->file_list,
			ip->files_button,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `resolution' in the specified instance.
 */
Xv_opaque
faxtool_window1_resolution_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:resolution",
		XV_X, 170,
		XV_Y, 447,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Resolution:",
		PANEL_CHOICE_STRINGS,
			"Normal",
			"Fine",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("yellow"),
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `page_size' in the specified instance.
 */
Xv_opaque
faxtool_window1_page_size_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:page_size",
		XV_X, 180,
		XV_Y, 480,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Page Size:",
		PANEL_CHOICE_STRINGS,
			"Letter",
			"A4",
			"B4",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  2, gcm_color_index("white"),
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `notify' in the specified instance.
 */
Xv_opaque
faxtool_window1_notify_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:notify",
		XV_X, 151,
		XV_Y, 513,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, "Notify Sender:",
		PANEL_CHOICE_STRINGS,
			"On Delivery",
			"On Retry",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("yellow"),
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `time_unit' in the specified instance.
 */
Xv_opaque
faxtool_window1_time_unit_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:time_unit",
		XV_X, 364,
		XV_Y, 546,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_STRINGS,
			"Minutes",
			"Hours",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("white"),
		PANEL_DEFAULT_VALUE, 0,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `send' in the specified instance.
 */
Xv_opaque
faxtool_window1_send_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:send",
		XV_X, 151,
		XV_Y, 550,
		PANEL_VALUE_DISPLAY_LENGTH, 4,
		PANEL_VALUE_STORED_LENGTH, 4,
		PANEL_LABEL_STRING, "Time To Send:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_VALUE, "Now",
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `time' in the specified instance.
 */
Xv_opaque
faxtool_window1_time_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:time",
		XV_X, 292,
		XV_Y, 550,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 2,
		PANEL_LABEL_STRING, "+",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 99,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `send_time' in the specified instance.
 */
Xv_opaque
faxtool_window1_send_time_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 151,
		XV_Y, 546,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->send,
			ip->time,
			ip->time_unit,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 5,
		NULL);
	return obj;
}

/*
 * Create object `options' in the specified instance.
 */
Xv_opaque
faxtool_window1_options_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 151,
		XV_Y, 447,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->resolution,
			ip->page_size,
			ip->notify,
			ip->send_time,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `send_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_send_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_send_button_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:send_button",
		XV_X, 63,
		XV_Y, 599,
		PANEL_ITEM_COLOR, gcm_color_index("green"),
		PANEL_LABEL_STRING, "Send",
		PANEL_NOTIFY_PROC, faxtool_window1_send_button_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `preview_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_preview_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		preview_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:preview_button",
		XV_X, 161,
		XV_Y, 599,
		PANEL_ITEM_COLOR, gcm_color_index("white"),
		PANEL_LABEL_STRING, "Preview...",
		PANEL_NOTIFY_PROC, preview_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `send_lower_left_buttons' in the specified instance.
 */
Xv_opaque
faxtool_window1_send_lower_left_buttons_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 63,
		XV_Y, 599,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->send_button,
			ip->preview_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 50,
		NULL);
	return obj;
}

/*
 * Create object `clear_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_clear_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_clear_button_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:clear_button",
		XV_X, 387,
		XV_Y, 599,
		PANEL_ITEM_COLOR, gcm_color_index("firebrick"),
		PANEL_LABEL_STRING, "Clear",
		PANEL_NOTIFY_PROC, faxtool_window1_clear_button_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `reset_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_reset_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_reset_button_notify_callback(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:reset_button",
		XV_X, 487,
		XV_Y, 599,
		PANEL_ITEM_COLOR, gcm_color_index("Yellow"),
		PANEL_LABEL_STRING, "Reset",
		PANEL_NOTIFY_PROC, faxtool_window1_reset_button_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `send_lower_right_buttons' in the specified instance.
 */
Xv_opaque
faxtool_window1_send_lower_right_buttons_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 387,
		XV_Y, 599,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->clear_button,
			ip->reset_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 50,
		NULL);
	return obj;
}

/*
 * Create object `send_lower_buttons' in the specified instance.
 */
Xv_opaque
faxtool_window1_send_lower_buttons_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 63,
		XV_Y, 599,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->send_lower_left_buttons,
			ip->send_lower_right_buttons,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 150,
		NULL);
	return obj;
}

/*
 * Create object `send_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_send_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 63,
		XV_Y, 25,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->coverpage,
			ip->file_objects,
			ip->options,
			ip->send_lower_buttons,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 30,
		GROUP_ANCHOR_OBJ, ip->send_controls,
		GROUP_ANCHOR_POINT, GROUP_CENTER,
		GROUP_REFERENCE_POINT, GROUP_CENTER,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 0,
		NULL);
	return obj;
}

/*
 * Create object `status_controls' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_controls_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:status_controls",
		XV_X, 0,
		XV_Y, (int)xv_get(ip->top_controls, XV_Y) +
		      (int)xv_get(ip->top_controls, XV_HEIGHT) + 2,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		XV_SHOW, FALSE,
		WIN_BORDER, TRUE,
		NULL);
	gcm_initialize_colors(obj, NULL, NULL);
	return obj;
}

/*
 * Create object `query_mode' in the specified instance.
 */
Xv_opaque
faxtool_window1_query_mode_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_query_mode_notify_callback(Panel_item, int, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:query_mode",
		XV_X, 166,
		XV_Y, 29,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Query For:",
		PANEL_NOTIFY_PROC, faxtool_window1_query_mode_notify_callback,
		PANEL_CHOICE_STRINGS,
			"All Jobs",
			"My Jobs Only",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("white"),
		PANEL_VALUE, 1,
		NULL);
	return obj;
}

/*
 * Create object `query_type' in the specified instance.
 */
Xv_opaque
faxtool_window1_query_type_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_query_type_notify_callback(Panel_item, int, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:query_type",
		XV_X, 161,
		XV_Y, 62,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Job Queue:",
		PANEL_NOTIFY_PROC, faxtool_window1_query_type_notify_callback,
		PANEL_CHOICE_STRINGS,
			"Receive Queue",
			"Send Queue",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("white"),
		PANEL_VALUE, 1,
		NULL);
	return obj;
}

/*
 * Create object `query_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_query_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 161,
		XV_Y, 29,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->query_mode,
			ip->query_type,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `jobs_list' in the specified instance.
 */
Xv_opaque
faxtool_window1_jobs_list_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern int		jobs_list_notify(Panel_item, char *, Xv_opaque, Panel_list_op, Event *, int);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:jobs_list",
		XV_X, 35,
		XV_Y, 115,
		PANEL_LIST_WIDTH, 511,
		PANEL_LIST_DISPLAY_ROWS, 17,
		PANEL_LIST_TITLE, "Job  Modem Destination     Time-To-Send     Sender         Status                        ",
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		PANEL_NOTIFY_PROC, jobs_list_notify,
		NULL);
	return obj;
}

/*
 * Create object `status_view_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_view_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		view_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:status_view_button",
		XV_X, 89,
		XV_Y, 475,
		PANEL_ITEM_COLOR, gcm_color_index("white"),
		PANEL_LABEL_STRING, "View...",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, view_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `status_print_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_print_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		print_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:status_print_button",
		XV_X, 196,
		XV_Y, 475,
		PANEL_ITEM_COLOR, gcm_color_index("white"),
		PANEL_LABEL_STRING, "Print",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, print_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `job_queue_left_buttons' in the specified instance.
 */
Xv_opaque
faxtool_window1_job_queue_left_buttons_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 89,
		XV_Y, 475,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->status_view_button,
			ip->status_print_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 50,
		NULL);
	return obj;
}

/*
 * Create object `modify_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_modify_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		modify_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:modify_button",
		XV_X, 344,
		XV_Y, 475,
		PANEL_ITEM_COLOR, gcm_color_index("yellow"),
		PANEL_LABEL_STRING, "Modify",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, modify_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `delete_button' in the specified instance.
 */
Xv_opaque
faxtool_window1_delete_button_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		delete_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:delete_button",
		XV_X, 454,
		XV_Y, 475,
		PANEL_ITEM_COLOR, gcm_color_index("firebrick"),
		PANEL_LABEL_STRING, "Delete",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, delete_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `job_queue_right_buttons' in the specified instance.
 */
Xv_opaque
faxtool_window1_job_queue_right_buttons_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 344,
		XV_Y, 475,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->modify_button,
			ip->delete_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 50,
		NULL);
	return obj;
}

/*
 * Create object `job_queue_buttons' in the specified instance.
 */
Xv_opaque
faxtool_window1_job_queue_buttons_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 89,
		XV_Y, 475,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->job_queue_left_buttons,
			ip->job_queue_right_buttons,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 100,
		NULL);
	return obj;
}

/*
 * Create object `job_queue_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_job_queue_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 35,
		XV_Y, 132,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->jobs_list,
			ip->job_queue_buttons,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `status_send_mode' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_send_mode_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	extern void		faxtool_window1_status_send_mode_notify_callback(Panel_item, int, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:status_send_mode",
		XV_X, 138,
		XV_Y, 524,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, TRUE,
		PANEL_LABEL_STRING, "Reschedule:",
		PANEL_NOTIFY_PROC, faxtool_window1_status_send_mode_notify_callback,
		PANEL_CHOICE_STRINGS,
			"Now",
			"Specify",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("White"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("white"),
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `status_send_time_unit' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_send_time_unit_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:status_send_time_unit",
		XV_X, 337,
		XV_Y, 557,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOICE_STRINGS,
			"Minutes",
			"Hours",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("white"),
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `status_send' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_send_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:status_send",
		XV_X, 124,
		XV_Y, 561,
		PANEL_VALUE_DISPLAY_LENGTH, 4,
		PANEL_VALUE_STORED_LENGTH, 4,
		PANEL_LABEL_STRING, "Time To Send:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE_UNDERLINED, FALSE,
		PANEL_VALUE, "Now",
		PANEL_INACTIVE, TRUE,
		PANEL_READ_ONLY, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `status_send_time' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_send_time_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:status_send_time",
		XV_X, 265,
		XV_Y, 561,
		PANEL_VALUE_DISPLAY_LENGTH, 2,
		PANEL_VALUE_STORED_LENGTH, 2,
		PANEL_LABEL_STRING, "+",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 99,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_INACTIVE, TRUE,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `status_send_time_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_send_time_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 124,
		XV_Y, 557,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->status_send,
			ip->status_send_time,
			ip->status_send_time_unit,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 5,
		NULL);
	return obj;
}

/*
 * Create object `reschedule_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_reschedule_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 124,
		XV_Y, 524,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->status_send_mode,
			ip->status_send_time_objects,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `status_notify' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_notify_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:status_notify",
		XV_X, 124,
		XV_Y, 590,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, TRUE,
		PANEL_LABEL_STRING, "Notify Sender:",
		PANEL_CHOICE_STRINGS,
			"None",
			"On Delivery",
			"On Retry",
			"Both",
			NULL,
		PANEL_CHOICE_COLOR,  0, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  1, gcm_color_index("white"),
		PANEL_CHOICE_COLOR,  2, gcm_color_index("yellow"),
		PANEL_CHOICE_COLOR,  3, gcm_color_index("yellow"),
		PANEL_INACTIVE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `status_lower_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_lower_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 124,
		XV_Y, 524,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->reschedule_objects,
			ip->status_notify,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `status_objects' in the specified instance.
 */
Xv_opaque
faxtool_window1_status_objects_create(faxtool_window1_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 35,
		XV_Y, 29,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->query_objects,
			ip->job_queue_objects,
			ip->status_lower_objects,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 30,
		GROUP_ANCHOR_OBJ, ip->status_controls,
		GROUP_ANCHOR_POINT, GROUP_CENTER,
		GROUP_REFERENCE_POINT, GROUP_CENTER,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 0,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `directory_popup'.
 */
faxtool_directory_popup_objects *
faxtool_directory_popup_objects_initialize(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (faxtool_directory_popup_objects *) calloc(1, sizeof (faxtool_directory_popup_objects))))
		return (faxtool_directory_popup_objects *) NULL;
	if (!ip->directory_popup)
		ip->directory_popup = faxtool_directory_popup_directory_popup_create(ip, owner);
	if (!ip->directory_controls)
		ip->directory_controls = faxtool_directory_popup_directory_controls_create(ip, ip->directory_popup);
	if (!ip->directory_list)
		ip->directory_list = faxtool_directory_popup_directory_list_create(ip, ip->directory_controls);
	if (!ip->dir_add_button)
		ip->dir_add_button = faxtool_directory_popup_dir_add_button_create(ip, ip->directory_controls);
	if (!ip->dir_change_button)
		ip->dir_change_button = faxtool_directory_popup_dir_change_button_create(ip, ip->directory_controls);
	if (!ip->dir_delete_button)
		ip->dir_delete_button = faxtool_directory_popup_dir_delete_button_create(ip, ip->directory_controls);
	if (!ip->dir_buttons)
		ip->dir_buttons = faxtool_directory_popup_dir_buttons_create(ip, ip->directory_controls);
	if (!ip->dir_list_objects)
		ip->dir_list_objects = faxtool_directory_popup_dir_list_objects_create(ip, ip->directory_controls);
	if (!ip->dir_name)
		ip->dir_name = faxtool_directory_popup_dir_name_create(ip, ip->directory_controls);
	if (!ip->dir_company)
		ip->dir_company = faxtool_directory_popup_dir_company_create(ip, ip->directory_controls);
	if (!ip->dir_fax)
		ip->dir_fax = faxtool_directory_popup_dir_fax_create(ip, ip->directory_controls);
	if (!ip->dir_fields)
		ip->dir_fields = faxtool_directory_popup_dir_fields_create(ip, ip->directory_controls);
	if (!ip->dir_select_button)
		ip->dir_select_button = faxtool_directory_popup_dir_select_button_create(ip, ip->directory_controls);
	if (!ip->dir_save_button)
		ip->dir_save_button = faxtool_directory_popup_dir_save_button_create(ip, ip->directory_controls);
	if (!ip->dir_lower_left_buttons)
		ip->dir_lower_left_buttons = faxtool_directory_popup_dir_lower_left_buttons_create(ip, ip->directory_controls);
	if (!ip->dir_clear_button)
		ip->dir_clear_button = faxtool_directory_popup_dir_clear_button_create(ip, ip->directory_controls);
	if (!ip->dir_reset_button)
		ip->dir_reset_button = faxtool_directory_popup_dir_reset_button_create(ip, ip->directory_controls);
	if (!ip->dir_lower_right_buttons)
		ip->dir_lower_right_buttons = faxtool_directory_popup_dir_lower_right_buttons_create(ip, ip->directory_controls);
	if (!ip->dir_lower_buttons)
		ip->dir_lower_buttons = faxtool_directory_popup_dir_lower_buttons_create(ip, ip->directory_controls);
	if (!ip->dir_objects)
		ip->dir_objects = faxtool_directory_popup_dir_objects_create(ip, ip->directory_controls);
	window_fit(ip->directory_controls);
	
	window_fit(ip->directory_popup);
	
	xv_set(ip->directory_controls,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `directory_popup' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_directory_popup_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	extern Notify_value	faxtool_directory_popup_event_callback(Xv_window, Event *, Notify_arg, Notify_event_type);
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 508,
		XV_HEIGHT, 638,
		XV_LABEL, "Fax Tool -  Directory",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, TRUE,
		NULL);
	xv_set(obj, WIN_CONSUME_EVENTS,
		NULL, NULL);
	notify_interpose_event_func(obj,
		(Notify_func) faxtool_directory_popup_event_callback, NOTIFY_SAFE);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `directory_controls' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_directory_controls_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:directory_controls",
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, TRUE,
		NULL);
	gcm_initialize_colors(obj, NULL, NULL);
	return obj;
}

/*
 * Create object `directory_list' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_directory_list_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	extern int		directory_list_notify(Panel_item, char *, Xv_opaque, Panel_list_op, Event *, int);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:directory_list",
		XV_X, 32,
		XV_Y, 31,
		PANEL_LIST_WIDTH, 425,
		PANEL_LIST_DISPLAY_ROWS, 20,
		PANEL_LIST_TITLE, "Name                     Company                  Fax Number                    ",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		PANEL_NOTIFY_PROC, directory_list_notify,
		NULL);
	return obj;
}

/*
 * Create object `dir_add_button' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_add_button_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	extern void		dir_add_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_add_button",
		XV_X, 123,
		XV_Y, 445,
		PANEL_ITEM_COLOR, gcm_color_index("green"),
		PANEL_LABEL_STRING, "Add",
		PANEL_NOTIFY_PROC, dir_add_notify,
		NULL);
	return obj;
}

/*
 * Create object `dir_change_button' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_change_button_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	extern void		dir_change_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_change_button",
		XV_X, 215,
		XV_Y, 445,
		PANEL_ITEM_COLOR, gcm_color_index("Yellow"),
		PANEL_LABEL_STRING, "Change",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, dir_change_notify,
		NULL);
	return obj;
}

/*
 * Create object `dir_delete_button' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_delete_button_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	extern void		dir_delete_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_delete_button",
		XV_X, 329,
		XV_Y, 445,
		PANEL_ITEM_COLOR, gcm_color_index("Firebrick"),
		PANEL_LABEL_STRING, "Delete",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, dir_delete_notify,
		NULL);
	return obj;
}

/*
 * Create object `dir_buttons' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_buttons_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 123,
		XV_Y, 445,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->dir_add_button,
			ip->dir_change_button,
			ip->dir_delete_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 50,
		NULL);
	return obj;
}

/*
 * Create object `dir_list_objects' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_list_objects_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 32,
		XV_Y, 31,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->directory_list,
			ip->dir_buttons,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `dir_name' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_name_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_name",
		XV_X, 150,
		XV_Y, 494,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Name:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `dir_company' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_company_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_company",
		XV_X, 125,
		XV_Y, 519,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Company:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `dir_fax' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_fax_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_fax",
		XV_X, 108,
		XV_Y, 544,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 25,
		PANEL_LABEL_STRING, "Fax Number:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `dir_fields' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_fields_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 108,
		XV_Y, 494,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->dir_name,
			ip->dir_company,
			ip->dir_fax,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `dir_select_button' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_select_button_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	extern void		dir_select_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_select_button",
		XV_X, 41,
		XV_Y, 589,
		PANEL_ITEM_COLOR, gcm_color_index("Green"),
		PANEL_LABEL_STRING, "Select",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, dir_select_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `dir_save_button' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_save_button_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	extern void		dir_save_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_save_button",
		XV_X, 145,
		XV_Y, 589,
		PANEL_ITEM_COLOR, gcm_color_index("Green"),
		PANEL_LABEL_STRING, "Save",
		PANEL_NOTIFY_PROC, dir_save_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `dir_lower_left_buttons' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_lower_left_buttons_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 41,
		XV_Y, 589,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->dir_select_button,
			ip->dir_save_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 50,
		NULL);
	return obj;
}

/*
 * Create object `dir_clear_button' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_clear_button_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	extern void		dir_clear_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_clear_button",
		XV_X, 316,
		XV_Y, 589,
		PANEL_ITEM_COLOR, gcm_color_index("firebrick"),
		PANEL_LABEL_STRING, "Clear",
		PANEL_NOTIFY_PROC, dir_clear_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `dir_reset_button' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_reset_button_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	extern void		dir_reset_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:dir_reset_button",
		XV_X, 416,
		XV_Y, 589,
		PANEL_ITEM_COLOR, gcm_color_index("yellow"),
		PANEL_LABEL_STRING, "Reset",
		PANEL_NOTIFY_PROC, dir_reset_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `dir_lower_right_buttons' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_lower_right_buttons_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 316,
		XV_Y, 589,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->dir_clear_button,
			ip->dir_reset_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 50,
		NULL);
	return obj;
}

/*
 * Create object `dir_lower_buttons' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_lower_buttons_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 41,
		XV_Y, 589,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->dir_lower_left_buttons,
			ip->dir_lower_right_buttons,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 125,
		NULL);
	return obj;
}

/*
 * Create object `dir_objects' in the specified instance.
 */
Xv_opaque
faxtool_directory_popup_dir_objects_create(faxtool_directory_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 32,
		XV_Y, 31,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->dir_list_objects,
			ip->dir_fields,
			ip->dir_lower_buttons,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 30,
		GROUP_ANCHOR_OBJ, ip->directory_controls,
		GROUP_ANCHOR_POINT, GROUP_CENTER,
		GROUP_REFERENCE_POINT, GROUP_CENTER,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 0,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `prop_popup'.
 */
faxtool_prop_popup_objects *
faxtool_prop_popup_objects_initialize(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (faxtool_prop_popup_objects *) calloc(1, sizeof (faxtool_prop_popup_objects))))
		return (faxtool_prop_popup_objects *) NULL;
	if (!ip->prop_popup)
		ip->prop_popup = faxtool_prop_popup_prop_popup_create(ip, owner);
	if (!ip->prop_controls)
		ip->prop_controls = faxtool_prop_popup_prop_controls_create(ip, ip->prop_popup);
	if (!ip->fax_host)
		ip->fax_host = faxtool_prop_popup_fax_host_create(ip, ip->prop_controls);
	if (!ip->fax_dir)
		ip->fax_dir = faxtool_prop_popup_fax_dir_create(ip, ip->prop_controls);
	if (!ip->prop_upper_fields)
		ip->prop_upper_fields = faxtool_prop_popup_prop_upper_fields_create(ip, ip->prop_controls);
	if (!ip->view_cmd)
		ip->view_cmd = faxtool_prop_popup_view_cmd_create(ip, ip->prop_controls);
	if (!ip->print_cmd)
		ip->print_cmd = faxtool_prop_popup_print_cmd_create(ip, ip->prop_controls);
	if (!ip->preview_cmd)
		ip->preview_cmd = faxtool_prop_popup_preview_cmd_create(ip, ip->prop_controls);
	if (!ip->prop_lower_fields)
		ip->prop_lower_fields = faxtool_prop_popup_prop_lower_fields_create(ip, ip->prop_controls);
	if (!ip->prop_save_button)
		ip->prop_save_button = faxtool_prop_popup_prop_save_button_create(ip, ip->prop_controls);
	if (!ip->prop_apply_button)
		ip->prop_apply_button = faxtool_prop_popup_prop_apply_button_create(ip, ip->prop_controls);
	if (!ip->prop_left_buttons)
		ip->prop_left_buttons = faxtool_prop_popup_prop_left_buttons_create(ip, ip->prop_controls);
	if (!ip->prop_clear_button)
		ip->prop_clear_button = faxtool_prop_popup_prop_clear_button_create(ip, ip->prop_controls);
	if (!ip->prop_reset_button)
		ip->prop_reset_button = faxtool_prop_popup_prop_reset_button_create(ip, ip->prop_controls);
	if (!ip->prop_right_buttons)
		ip->prop_right_buttons = faxtool_prop_popup_prop_right_buttons_create(ip, ip->prop_controls);
	if (!ip->prop_lower_buttons)
		ip->prop_lower_buttons = faxtool_prop_popup_prop_lower_buttons_create(ip, ip->prop_controls);
	if (!ip->prop_objects)
		ip->prop_objects = faxtool_prop_popup_prop_objects_create(ip, ip->prop_controls);
	window_fit(ip->prop_controls);
	
	window_fit(ip->prop_popup);
	
	xv_set(ip->prop_controls,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `prop_popup' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_popup_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 402,
		XV_HEIGHT, 230,
		XV_LABEL, "Fax Tool - Properties",
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `prop_controls' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_controls_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:prop_controls",
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, TRUE,
		NULL);
	gcm_initialize_colors(obj, NULL, NULL);
	return obj;
}

/*
 * Create object `fax_host' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_fax_host_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:fax_host",
		XV_X, 115,
		XV_Y, 23,
		PANEL_VALUE_DISPLAY_LENGTH, 10,
		PANEL_VALUE_STORED_LENGTH, 40,
		PANEL_LABEL_STRING, "Fax Host:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `fax_dir' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_fax_dir_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:fax_dir",
		XV_X, 19,
		XV_Y, 48,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Fax Spooling Directory:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE, "/var/spool/fax",
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `prop_upper_fields' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_upper_fields_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 19,
		XV_Y, 23,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->fax_host,
			ip->fax_dir,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `view_cmd' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_view_cmd_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:view_cmd",
		XV_X, 70,
		XV_Y, 93,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "View Filter:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE, "pageview",
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `print_cmd' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_print_cmd_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:print_cmd",
		XV_X, 70,
		XV_Y, 118,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Print Filter:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE, "pl",
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `preview_cmd' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_preview_cmd_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:preview_cmd",
		XV_X, 49,
		XV_Y, 143,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Preview Filter:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_VALUE, "cmdtool gs -q",
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `prop_lower_fields' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_lower_fields_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 49,
		XV_Y, 93,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->view_cmd,
			ip->print_cmd,
			ip->preview_cmd,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `prop_save_button' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_save_button_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	extern void		dir_save_button_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:prop_save_button",
		XV_X, 21,
		XV_Y, 188,
		PANEL_ITEM_COLOR, gcm_color_index("Green"),
		PANEL_LABEL_STRING, "Save",
		PANEL_NOTIFY_PROC, dir_save_button_notify,
		NULL);
	return obj;
}

/*
 * Create object `prop_apply_button' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_apply_button_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	extern void		prop_apply_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:prop_apply_button",
		XV_X, 97,
		XV_Y, 188,
		PANEL_ITEM_COLOR, gcm_color_index("green"),
		PANEL_LABEL_STRING, "Apply",
		PANEL_NOTIFY_PROC, prop_apply_notify,
		NULL);
	return obj;
}

/*
 * Create object `prop_left_buttons' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_left_buttons_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 21,
		XV_Y, 188,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->prop_save_button,
			ip->prop_apply_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 30,
		NULL);
	return obj;
}

/*
 * Create object `prop_clear_button' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_clear_button_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	extern void		prop_clear_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:prop_clear_button",
		XV_X, 250,
		XV_Y, 188,
		PANEL_ITEM_COLOR, gcm_color_index("firebrick"),
		PANEL_LABEL_STRING, "Clear",
		PANEL_NOTIFY_PROC, prop_clear_notify,
		NULL);
	return obj;
}

/*
 * Create object `prop_reset_button' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_reset_button_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	extern void		prop_reset_notify(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "faxtool:prop_reset_button",
		XV_X, 330,
		XV_Y, 188,
		PANEL_ITEM_COLOR, gcm_color_index("yellow"),
		PANEL_LABEL_STRING, "Reset",
		PANEL_NOTIFY_PROC, prop_reset_notify,
		NULL);
	return obj;
}

/*
 * Create object `prop_right_buttons' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_right_buttons_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 250,
		XV_Y, 188,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->prop_clear_button,
			ip->prop_reset_button,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 30,
		NULL);
	return obj;
}

/*
 * Create object `prop_lower_buttons' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_lower_buttons_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 21,
		XV_Y, 188,
		GROUP_TYPE, GROUP_ROW,
		GROUP_MEMBERS,
			ip->prop_left_buttons,
			ip->prop_right_buttons,
			NULL,
		GROUP_ROW_ALIGNMENT, GROUP_HORIZONTAL_CENTERS,
		GROUP_HORIZONTAL_SPACING, 100,
		NULL);
	return obj;
}

/*
 * Create object `prop_objects' in the specified instance.
 */
Xv_opaque
faxtool_prop_popup_prop_objects_create(faxtool_prop_popup_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 19,
		XV_Y, 23,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->prop_upper_fields,
			ip->prop_lower_fields,
			ip->prop_lower_buttons,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 30,
		GROUP_ANCHOR_OBJ, ip->prop_controls,
		GROUP_ANCHOR_POINT, GROUP_CENTER,
		GROUP_REFERENCE_POINT, GROUP_CENTER,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 0,
		NULL);
	return obj;
}

