.TH FAXTOOL 1 
.DA dd month yyyy
.SH NAME
.B faxtool
\- X GUI interface to FlexFax (
.I sendfax
and friends)
.SH SYNOPSIS
.B faxtool
[-display host:display.screen] [XView-options]
.SH DESCRIPTION
This program is a GUI-based interface to the
.I sendfax
and
.I faxstat
programs.
.SH SEE ALSO
.I sendfax ,
.I faxstat
\- programs it uses.
.SH HISTORY
Thomas Corson wrote it. 
.SH BUGS
This is version 0.1.
.PP
See the README file in /usr/src/cmd/faxtool/README.
