/*
 * timer_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `timer.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "timer_ui.h"

/*
 * Initialize an instance of object `baseFrame'.
 */
timer_baseFrame_objects *
timer_baseFrame_objects_initialize(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (timer_baseFrame_objects *) calloc(1, sizeof (timer_baseFrame_objects))))
		return (timer_baseFrame_objects *) NULL;
	if (!ip->baseFrame)
		ip->baseFrame = timer_baseFrame_baseFrame_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = timer_baseFrame_controls1_create(ip, ip->baseFrame);
	if (!ip->topicList)
		ip->topicList = timer_baseFrame_topicList_create(ip, ip->controls1);
	if (!ip->startButton)
		ip->startButton = timer_baseFrame_startButton_create(ip, ip->controls1);
	if (!ip->stopButton)
		ip->stopButton = timer_baseFrame_stopButton_create(ip, ip->controls1);
	if (!ip->newTextfield)
		ip->newTextfield = timer_baseFrame_newTextfield_create(ip, ip->controls1);
	if (!ip->addButton)
		ip->addButton = timer_baseFrame_addButton_create(ip, ip->controls1);
	if (!ip->rereadButton)
		ip->rereadButton = timer_baseFrame_rereadButton_create(ip, ip->controls1);
	if (!ip->deleteButton)
		ip->deleteButton = timer_baseFrame_deleteButton_create(ip, ip->controls1);
	if (!ip->group1)
		ip->group1 = timer_baseFrame_group1_create(ip, ip->controls1);
	window_fit(ip->controls1);
	
	window_fit(ip->baseFrame);
	
	xv_set(ip->controls1,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `baseFrame' in the specified instance.
 */
Xv_opaque
timer_baseFrame_baseFrame_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 450,
		XV_HEIGHT, 450,
		XV_LABEL, "Time Usage Reporter",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
timer_baseFrame_controls1_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `topicList' in the specified instance.
 */
Xv_opaque
timer_baseFrame_topicList_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	extern int		timer_baseFrame_topicList_notify_callback();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 16,
		PANEL_LIST_WIDTH, 430,
		PANEL_LIST_DISPLAY_ROWS, 10,
		PANEL_LIST_TITLE, "Topic",
		PANEL_LAYOUT, PANEL_VERTICAL,
		PANEL_READ_ONLY, FALSE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		PANEL_NOTIFY_PROC, timer_baseFrame_topicList_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `startButton' in the specified instance.
 */
Xv_opaque
timer_baseFrame_startButton_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	extern void		startTopic();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "timer:startButton",
		XV_X, 16,
		XV_Y, 339,
		PANEL_LABEL_STRING, "Start",
		PANEL_NOTIFY_PROC, startTopic,
		NULL);
	return obj;
}

/*
 * Create object `stopButton' in the specified instance.
 */
Xv_opaque
timer_baseFrame_stopButton_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	extern void		stopTopic();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "timer:stopButton",
		XV_X, 354,
		XV_Y, 339,
		PANEL_LABEL_STRING, "Stop",
		PANEL_NOTIFY_PROC, stopTopic,
		NULL);
	return obj;
}

/*
 * Create object `newTextfield' in the specified instance.
 */
Xv_opaque
timer_baseFrame_newTextfield_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "timer:newTextfield",
		XV_X, 16,
		XV_Y, 370,
		PANEL_VALUE_DISPLAY_LENGTH, 20,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "New Topic:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `addButton' in the specified instance.
 */
Xv_opaque
timer_baseFrame_addButton_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	extern void		timer_baseFrame_addButton_notify_callback();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "timer:addButton",
		XV_X, 354,
		XV_Y, 370,
		PANEL_LABEL_STRING, "Add",
		PANEL_NOTIFY_PROC, timer_baseFrame_addButton_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `rereadButton' in the specified instance.
 */
Xv_opaque
timer_baseFrame_rereadButton_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	extern void		rereadTopics();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 401,
		PANEL_LABEL_STRING, "Re-read Topics",
		PANEL_NOTIFY_PROC, rereadTopics,
		NULL);
	return obj;
}

/*
 * Create object `deleteButton' in the specified instance.
 */
Xv_opaque
timer_baseFrame_deleteButton_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	extern void		timer_baseFrame_deleteButton_notify_callback();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "timer:deleteButton",
		XV_X, 354,
		XV_Y, 401,
		PANEL_LABEL_STRING, "Delete",
		PANEL_INACTIVE, TRUE,
		PANEL_NOTIFY_PROC, timer_baseFrame_deleteButton_notify_callback,
		NULL);
	return obj;
}

/*
 * Create object `group1' in the specified instance.
 */
Xv_opaque
timer_baseFrame_group1_create(ip, owner)
	timer_baseFrame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 16,
		XV_Y, 339,
		GROUP_TYPE, GROUP_ROWCOLUMN,
		GROUP_MEMBERS,
			ip->startButton,
			ip->stopButton,
			ip->newTextfield,
			ip->addButton,
			ip->rereadButton,
			ip->deleteButton,
			NULL,
		GROUP_ROWS, 3,
		GROUP_ROW_ALIGNMENT, GROUP_TOP_EDGES,
		GROUP_COLUMN_ALIGNMENT, GROUP_LEFT_EDGES,
		GROUP_HORIZONTAL_SPACING, 10,
		GROUP_VERTICAL_SPACING, 10,
		GROUP_ANCHOR_OBJ, ip->topicList,
		GROUP_ANCHOR_POINT, GROUP_SOUTHWEST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 10,
		NULL);
	return obj;
}

