.TH TIMEKEEPER 1 local SoftQuad
.DA 01 December 1991
.\" $Id: timekeeper.1,v 1.5 92/06/03 14:28:34 ian Exp $
.SH NAME
timekeeper \- record your time usage
.SH SYNOPSIS \- X Window System
.B timekeeper
[
.B -display
.I Xdisplay
] [
.I xview-args
] &
.SH "SYNOPSIS \- UNIX Command line
.B tk
task
.br
.B tk
end
.br
.B tk
[-e][-f hh:mm][-p][-l][-a task][-h]
.SH DESCRIPTION
The
.I timekeeper
or
.I tk
program keeps track of your project hours.
The first program runs under X Windows,
while the second is UNIX-command-line oriented.
.PP
.I Timekeeper
presents you with a scrolling list of tasks.
You select a task and click the START
button when you begin working on that task.
Click STOP when you are done, or, when you start
working on another task, select it and click START.
.PP
Regular X users should start this program from their 
.I .xinitrc
or 
.I .xsession
files.
An example startup might be:
.sp
timekeeper -display $DISPLAY -geometry -0-0 -WP 200 0 -Wi &
.sp
This would start the program on the given display, 
with the open window in the lower right corner,
with the icon window at (200,0), and initially iconified.
If you run a virtual window manager or have a large screen,
leave off the
.B -Wi .
.PP
The non-X version of this program, 
.I tk ,
will normally take its first argument to be a substring
of the tasks you are starting work on.
It also
accepts several options, each of which affects either your
TIMELOG file or your TASKS file.
.B Tk
.B -h
will list the available options and their effects.
The most important are
.B -a
to add a task,
.B -p
to edit your tasks (projects),
and
.B -e to edit your 
.I .timelog
file.
.PP
There is also a
.B -f
.I hh:mm
option which lets you retroactively start a task, for use
when you forgot to tell tk you were starting a new task.
.PP
The
.B -s
option is used to summarize your TIMELOG file.
.PP
Your files will (someday, ha ha) be consolidated and reported automatically.
.SH FILES
$HOME/.tasks \- a list of projects and activities that you spend time on.
This can be changed by setting the environment variable TASKFILE
to the full path of a file.
You can edit this file at any time with any editor, but 
users of the X version must click
the SELECT (left) mouse button on the "Re-read Topics" button if you do.
.sp
$HOME/.timelog \- the file where your records are kept.
You may wish to set its permissions to be user-read-write,
group and others none (chmod 600 $HOME/.timelog).
The location of this file cannot be changed, as the time recording
software assumes this name, and won't read your 
.I .profile/.login
to try to figure it out.
This file is reopened whenever it's to be written, so it is safe
to edit this file while the program is running.
.SH SEE ALSO
XView(1) lists the standard XView client command line arguments.
.PP
The shell script 
.I tk
is the final arbiter of what command options are really accepted
at any given time.
.SH HISTORY
Written at SoftQuad Inc by Ian Darwin, late 1991 and early 1992,
to satisfy our own reporting requirements as well as those of various
clients.
Initial X version built using SunSoft's devGUIde GUI builder for X Windows.
.SH BUGS
The default list of tasks, used before you have a 
.I .tasks
file, is rather silly.
.sp
The 
.I "Delete Topic
function isn't written yet.
.PP
The batch version does not ignore interrupts around the editor with -e or -p;
this should be harmless.
