;GIL-3
(
(
	:type                   :base-window
	:name                   baseFrame
	:owner                  nil
	:width                  549
	:height                 293
	:background-color       ""
	:foreground-color       ""
	:label                  "Tickler/Database for X"
	:label-type             :string
	:initial-state          :open
	:show-footer            t
	:resizable              t
	:icon-file              ""
	:icon-label             ""
	:icon-mask-file         ""
	:event-handler          nil
	:user-data              ()
	:actions                ()
)
(
	:type                   :control-area
	:name                   controls1
	:owner                  baseFrame
	:help                   ""
	:x                      0
	:y                      0
	:width                  549
	:height                 293
	:background-color       ""
	:foreground-color       ""
	:initial-state          :visible
	:show-border            nil
	:menu                   nil
	:event-handler          nil
	:user-data              ()
	:actions                ()
)
(
	:type                   :button
	:name                   button1
	:owner                  controls1
	:help                   ""
	:x                      24
	:y                      16
	:width                  58
	:height                 20
	:constant-width         nil
	:button-type            :normal
	:foreground-color       ""
	:label                  "Button"
	:label-type             :string
	:initial-state          :active
	:menu                   nil
	:notify-handler         nil
	:event-handler          nil
	:user-data              ()
	:actions                ()
)
(
	:type                   :button
	:name                   button2
	:owner                  controls1
	:help                   ""
	:x                      104
	:y                      16
	:width                  58
	:height                 20
	:constant-width         nil
	:button-type            :normal
	:foreground-color       ""
	:label                  "Button"
	:label-type             :string
	:initial-state          :active
	:menu                   nil
	:notify-handler         nil
	:event-handler          nil
	:user-data              ()
	:actions                ()
)
(
	:type                   :button
	:name                   button3
	:owner                  controls1
	:help                   ""
	:x                      184
	:y                      16
	:width                  58
	:height                 20
	:constant-width         nil
	:button-type            :normal
	:foreground-color       ""
	:label                  "Button"
	:label-type             :string
	:initial-state          :active
	:menu                   nil
	:notify-handler         nil
	:event-handler          nil
	:user-data              ()
	:actions                ()
)
(
	:type                   :scrolling-list
	:name                   list1
	:owner                  controls1
	:help                   ""
	:x                      16
	:y                      48
	:width                  500
	:height                 200
	:value-x                16
	:value-y                48
	:rows                   10
	:foreground-color       ""
	:label                  ""
	:title                  ""
	:label-type             :string
	:layout-type            :horizontal
	:read-only              nil
	:multiple-selections    nil
	:selection-required     nil
	:initial-state          :active
	:droppable              nil
	:default-drop-site      nil
	:menu                   nil
	:notify-handler         nil
	:event-handler          nil
	:initial-list-values    ()
	:initial-list-glyphs    ()
	:initial-selections     ()
	:user-data              ()
	:actions                ()
)
)
