.TH XVNEWS 1 "July 1994"
.SH NAME
xvnews \- an OPEN LOOK news reader

.SH SYNOPSIS
.B xvnews
[
.I generic-tool-options
]

.SH AVAILABILITY
.B xvnews
is available for reading news using the intuitive OPEN LOOK interface.
Regular updates of 
.B xvnews 
are available via FTP from either
.IR ftp.twi.tudelft.nl:/pub/news
or from 
.IR ftp.uu.net:/networking/news/readers/xvnews
.

.SH SYNOPSIS
.B xvnews
[
.BI \-s newsgroupname
]
[
.BI \-u
]

.SH DESCRIPTION
.B xvnews 2.3
is an OpenLook interface for reading Usenet news. It provides a
menu-driven facility for reading, storing and sending news
articles. It also provides mail functionality to reply to or forward
news articles. Scrollable windows allow easy access to newsgroups and
articles.

The full editing capabilities of 
.BR textedit (1)
are available for modifying and composing news articles. 

.SH OPTIONS
.TP
.B \-s newsgroup
Start xvnews with the given
.I newsgroup
, and only allows reading this
particular group.
.TP
.B \-u
Pop up the Undelete window whenever there are killed articles in a
group. The default is to just display a message in the footer of the
article window. Previous versions of
.B xvnews
would always show the
Undelete window.

.SH USAGE
.B xvnews
operates through the use of a set of command panel buttons, windows,
menus and other components that conform to the OPEN LOOK 
.IR "Graphical User Interface Functional Specification" .
News articles are edited using the menus and commands of the 
.B textedit 
program.

For more information about the general usage of OPEN LOOK software
applications, see the 
.IR "OpenWindows User's Guide" . 

An optional argument -s followed by a newsgroup name can be given. If
this argument is present, xvnews will only read this particular group,
and it will create a file .newsgroupname to store the article numbering.

In the following sections the different panels containing buttons will
be shown. Each panel is associated with a different type of operation.

.SS Subscribed Groups Panel Buttons
The 
.B xvnews 
group panel is shown when all the subscribed groups that have unread articles
are shown.

.TP 12
.B Quit
Used to update the users 
.B .newsrc 
file and exit
.BR xvnews .

.TP 12
.B Rescan
Rescan the news server for new groups and if none are found, search for new 
articles in the user's subscribed groups.

.TP 12
.B Catchup
Used to mark all articles in the selected newsgroup read. Confirmation is asked
if you are in 
.IR "group mode" .

.TP 12
.B Unsubscribe
Unsubscribes the user from the group that is currently selected.

.TP 12
.B Update
Update the user's 
.B .newsrc
file.

.TP 12
.B Read Group
Open the currently selected newsgroup and start reading unread articles.

.TP 12
.B View Groups >
.RS
.TP 12
.B All Groups
Obtain a list of all newsgroups available from the news server. 
.TP 12
.B All Subscribed
Obtain a list of all the newsgroups the user is subscribed to.
.TP 12
.B All Unsubscribed
Obtain a list of all the newsgroups the user is not subscribed to.
.TP 12
.B All Matching groups
Obtain a list of all the newsgroups that match the regular expression.
.RE
.TP 12
.B Properties
Allows the user to modify the resources associated with 
.BR xvnews .

.TP 12
.B Post
Brings up an article compose window and allows the user to post a new article.
If the resource XVnews.postEditor is set to an alternate editor, this will be
used for posting.

.SS Articles Panel Buttons
The 
.B xvnews 
articles panel is shown when a group is entered and there are unread
articles. Drag and drop of articles is supported from the list of articles. 
To enable drag and drop, select a group and while holding down the select
button, drag the article to another application that supports drops.
The article display may be sorted in alphabetical order or message order (default)
by setting the resource XVnews.sortSubjects available in the properties window, or
by using the 'S' keyboard accelerator.

.TP 12
.B Done
Returns to subscribed groups with unread articles. Updates 
.B .newsrc
file by adding articles that were read to the list of articles.

.TP 12
.B Prev Art >
The menu under prev art allows the user to select options for viewing previous 
articles to the one currently being read. A default for this menu can be 
selected by using the CTRL-right mouse button action. This default will be
stored as the resource
.B  XVnews.PrevDefault 
when the 
.I apply 
button is used from the properties popup. 
.RS
.TP 12
.B Prev article
Reads the article previous to the one currently selected. If the user is at
the top of the scrolling list, a previously read article will be read
in and displayed.
.TP 12
.B Prev subject
Finds an article with a subject that matches the current article being read. 
Confirmation will be asked before previously read articles are searched.
.TP 12
.B Prev author
Finds an article written by the same author as the article currently being 
read.
Confirmation will be asked before previously read articles are searched.
.RE

.TP 12
.B Catchup >
Allows the user to mark blocks of articles as read. Both options leave
articles marked as unread alone. Both options also update the 
.B .newsrc
and exit the newsgroup. This option is unavailable if 
.I goto group
was selected.
.RS
.TP 12
.B All Articles
Marks all articles as read.
.TP 12
.B Up to Article
Marks articles up to current article as read.
.RE
.TP 12
.B Unsubscribe
Unsubscribes the user from the group currently being read and returns
to the list of subscribed groups with unread articles.
.TP 12
.B Kill >
Allows user to delete articles that are from annoying authors or redundant 
subjects.
Removes articles for this session only, unless the kill file is edited. If all 
articles are killed, 
.B xvnews 
returns to the group listing, marking all articles as read.
.RS
.TP 12
.B Subject
Removes all articles having the same subject.
.TP 12
.B Author
Removes all articles having the same author.
.TP 12
.B Kill File
Brings up the 
.I kill 
popup and allows editing of the kill files.
.TP 12
.B Undelete
Brings up the 
.I undelete 
popup if there were any articles killed in this group.
.RE

.TP 12
.B Search >
Provides a mechanism for searching for articles that match the current article 
being read. A default menu item can be selected for this menu by using the
CTRL-right mouse button and then hitting apply button in the properties popup.
This default will be stored as the resource 
.BR XVnews.SearchDefault .
.RS
.TP 12
.B Subject Next
Searches for the next article whose subject matches the one that is
currently being read.
.TP 12
.B Subject Previous
Searches for an article previous to the one that is currently being read with
a  subject that matches. If no matches are found that are unread, previously
read articles will be checked as well.
.TP 12
.B Author Next
Searches for the next article written by the same author as the currently read 
article.
.TP 12
.B Author Previous
Searches for an article previous to the one that is currently being read that
was written by the same author. If no matches are found that are unread, 
previously read articles will be checked as well.
.TP 12
.B Search
Brings up the search window and allows article headers to be searched using
regular expressions similar to 
.BR ed (1).
.RE
.TP 12
.B Save >
Provides a way to save articles edited or unedited from the text window.
.RS
.TP 12
.B Save
Saves the article, as it resides in the text window, to either the users
.I SAVEDIR 
directory, or if the file saver is active, the filename specified
there.
.TP 12
.B Filter
Opens a pipe to the command defined by the resource 
.B XVnews.saveFilter
and prints the edited article through this command.
.TP 12
.B File
Brings up the file saver and allows the user to save an article, as it resides
in the text window, to a filename.
.RE

.TP 12
.B Next Art >
The menu under next art allows the user to select options for viewing articles
that appear after the article currently being read. A default item for this
menu can be selected by using the CTRL-right mouse button. This default will
then be stored as the resource 
.B XVnews.NextDefault 
when the apply button is used from the properties popup.
.RS
.TP 12
.B Next article
Reads the next available article. If no more articles are available, 
.B xvnews
exits the current group.
.TP 12
.B Next unread
Finds the next unread article. If no more articles are available, 
.B xvnews 
exits the current group.
.TP 12
.B Next subject
Finds the next article that has a subject that matches the article currently
being read. If no matches are found, the next unread article is retrieved.
.TP 12
.B Next author
Finds the next article that has an author that matches the article currently 
being read. If no matches are found, the next unread article is retrieved.
.RE
.TP 12
.B All Articles
Retrieves all of the articles available in the current group.
.TP 12
.B Print
Prints the article as it resides in the text window, to the command
specified in the properties popup.
.TP 12
.B Mark Unread
Marks the article currently selected as unread. Article will show up next time
group is selected. When using 
.IR "goto group" , 
this will add this article back to to
unread list as well.
.TP 12
.B Post/Email >
Provides the user with the functionality to post, followup, reply to, or
forward an article. Drag and drop is supported into the window with an option 
of uuencoding and compressing. If the article is included, it will be prefixed
by the indent string specified in the properties window. The load file option
brings up a popup window similar to the file saver and allows the user to
include files into the article. You will be prompted if you would like to 
included the file as text or compressed and uuencoded. You will also be 
informed of how many lines were included from this file. If the resource
XVnews.postEditor is set to an alternate editor (eg 'shelltool vi'), this
editor will be used instead of the standard xvnews posting window.
.RS
.TP 12
.B Post to group
Brings up a post window and allows the user to compose a news article.
.TP 12
.B Post followup
Brings up a followup window and allows posting to current newsgroup.
.TP 12
.B Reply to Sender
Brings up an e-mail reply window and allows replying to the author of the 
article.
.TP 12
.B Forward article
Allows the user to forward an article via e-mail. The current article will be
included. 
.RE

.SS News Groups/View Groups Panel
The news groups/view groups panel is shown when either new newsgroups are 
available from the news server or when the user selects an option under view 
newsgroups. When a user selects a group, if there is a description available 
from the news server of that group, the description and total number of 
available articles will be displayed. The user can select multiple newsgroups 
to subscribe/unsubscribe, but only one group may be selected to goto.

.TP 12
.B Done
Returns the user to the subscribed newsgroups listing.
.TP 12
.B Sort Newsrc
Sorts the 
.B .newsrc 
file in alphabetical order.
.TP 12
.B Unsubscribe
Unsubscibes a user to the selected newsgroups. Multiple newsgroups may be 
selected. If the user is already unsubscribed, no change is made to that group.
.TP 12
.B Goto group
Retrieves all available articles for the selected group. This button will be 
inactive if multiple newsgroups are selected. Kill entries are not processed 
when a group is entered by using goto. The 
.B .newsrc 
file will not be updated with changes from this session unless mark unread is
used. In effect, goto is a read-only browse feature.
.TP 12
.B Subscribe
Subscibes a user to the selected newsgroups. Multiple newsgroups may be 
selected. If the user is already subscribed, no change is made to that group.
.TP 12
.B Properties
Allows the user to modify the resources associated with
.BR xvnews .

.SS Miscellaneous Windows
.TP 12
.B The File Saver
The file saver window allows the user to save an article to a specified file. 
If the file exists, the article will be appended to the existing file. The 
article is saved in it's edited or unedited mode from the article window. 
Unedited the article will save in mail format. Article are saved when a file is
entered in the Name line or a file is double clicked on.
.TP 12
.B The Post/Email window
The post/email window allows the user to either post a new article to a 
newsgroup, post a followup article to a newsgroup, reply to the author of an 
article, or forward an article. Drag and drop is supported into the window and 
the user will be prompted if he would like the drop uuencoded and compressed, 
or loaded as plain text. If the user is posting or forwarding an article, 
there will be a menu available to select a distribution for this article. 
Distributions vary from news server to news server and determine where the 
posted article will be transmitted. A brief description of the distribution 
will also be given. The option of including the article is available with 
followup and reply to sender, article is automatically included with the 
forward option. Be defining the resource 
.BR XVnews.logFile , 
you can save outgoing postings to this file in mail format.
.TP 12
.B The Search Window
The search window allows the user to search any single line of the header for 
a regular expression which the user enters. Searching will be done on all 
available article previous or after the current article that is selected. If 
an error occurs decoding the regular expression, a message will be printed 
describing the error. 
.B xvnews 
supports a limited form of regular-expression notation similar to that of 
.BR ed (1). 
Support is included for searching the entire article text for a regular 
expression, select or insert "article text". Support is also included for 
searching the entire header, select or insert "entire header".
.TP 12
.B The Properties Window
The properties window allows the user to set and store the resources 
associated with 
.BR xvnews . 
.TP 12
.B The Kill File Editor
The kill file editior popup allows the user to edit the kill file for either
this group, or the global kill file. By default, the kill files are stored in 
.BR $SAVEDIR/group/name . 
The global kill file is 
.BR $SAVEDIR/KILL . 
There is a menu available for kill string that allows the user to choose to
kill a subject or author that match the current article. There is also a 
crossposts option that allows the user to kill all articles posted to multiple
groups, or crossposted to a certain group.

To add this regular expression to a kill file, push either the 
.IR "add group kill" , 
or the 
.I add global kill
button. The difference is that adding an entry to the group kill file only operates on those articles that match this string in this group. Adding an entry to the global kill file operates on those articles that match this string in every group that is read. See the kill file section for a more in-depth description of kill file entries. By having the process kill entry for this session checked, the kill entry that you added will process the articles shown in this group.

Another part of the kill file editor is the scrolling list that actually
allows editing of kill files. To edit either the group kill file or the global 
kill file, select either from the edit menu and if the file is found, it will 
be loaded into the scrolling list. To delete an entry, select one or more 
entries from the list and hit the delete button. Deletes are pending until the
save button is selected. Commented lines start with #.
.TP 12
.B The Undelete Popup
The undelete popup allows the user to bring back articles that have been 
killed. This window is only available if articles were killed in this session.
To undelete an article, just select an article from the list and hit the 
undelete button. Multiple articles may be chosen to undelete.

.SH KEYBOARD ACCELERATORS
Keyboard accelerators are available for certain functions. Make sure that
keyboard focus is in the center button panel and accelerators can be used for:
.TP 5
.B Subscribed Groups:
.RS
.TP 6
.B n
next group
.TP 6
.B p
previous group
.TP 6
.B L3
Properties popup
.RE
.TP 6
.B Unread Articles:
.RS
.TP 6
.B n
next article
.TP 6
.I space
scroll/next article/next group
.TP 6
.B p
previous article
.TP 6
.B f
scroll text one page forward/next article
.TP 6
.B b
scroll text one page backward
.TP 6
.B h
toggle header for this article only
.TP 6
.B s
save current article
.TP 6
.B k
kill the current subject
.TP 6
.B q
update newsrc, exit this group
.TP 6
.B S
toggle the sort subjects option for this group
.TP 6
.B L3
Properties popup
.TP 6
.B L9
Find next subject
.RE

.SH KILL FILES
In 
.BR xvnews ,
there is a useful feature called the KILL file, which allows you to kill (skip 
over) articles that you don't want to see. KILL files come in two forms:

.TP 12
Global
In your 
.B $SAVEDIR 
directory, you will have the file 
.BR KILL .
.TP 12
Local
In your 
.B $SAVEDIR 
directory, the kill file for group 
.I foo.bar 
is
.BR foo/bar/KILL .

.LP
The difference between the two is that there can be one kill file for each 
group (the local kill file), and that kill file affects only the particular 
newsgroup
.RB ( foo/bar/KILL
affects only 
.IR foo.bar ).
The global kill file affects all newsgroups. If there is both a global and 
local kill file, the global file is processed first, and then the local file.

The general style for building a kill entry is:
.RS 12
.I /regular expression/modifiers:command
.RE
.TP 6
.B Modifiers:
.RS
.TP 6
.B c
Ignore case during regular expression matching.
.TP 6
.B h
Look through the entire header of the article for the expression. If no 
modifier appears before the colon, only the subject line of the article is
searched.
.RE

Note: 
.B xvnews
does not support 'a' as a valid modifier. Some readers use 'a' as a modifier 
to search the entire article, which is very slow.

.TP 6
.B Commands:
.RS
.TP 6
.B j
Mark article as read.
.TP 6
.B m
Mark article as unread.
.RE

To kill a general subject, put in the entry:
.RS 6
.I /foo/:j
.RE

If you decided that you wanted to read all article written by 
.IR joe@schmo , 
even if the subject was foo, you could put:
.RS 6
.I /foo/:j

.I /^From: joe@schmo/h:m
.RE

Note that the order of these entries is important. First, we kill all subjects 
that match foo. Then we mark unread all articles written by 
.IR joe@schmo .

Finally, an example of an entry which works with the case-insensitive flag,
which would kill all articles about version 4.x.x of SunOS:
.RS 6
.I /SunOS 4\.1\.[123]/c:j
.RE

Also take note that the relationship between the global kill file and the 
local kill file is important. The global kill file is processed first, then 
the local kill file. If an article is marked unread in the global file, but 
marked as read in the local file, the local file takes precedence and the 
article is marked as read.

The regular expression routines that xvnews uses are case sensitive by
default, unlike some other news programs.

For a further discussion of regular expressions, see the man page for 
.BR ed (1).

Articles that are read will automatically have the cross posted article (if one exists)
killed. This is only when the article is read and not when catchup is used.

.SH RESOURCES
The resources for
.B  xvnews
are stored in the user's
.BR ~/.Xdefaults .

.TP 12
.B XVnews.background
Specifies the background color for
.BR xvnews .
Default is NULL.
.TP 12
.B XVnews.textcolor
Specifies the color of the text in 
.BR xvnews .
Default is NULL.
.TP 12
.B XVnews.textback
Specifies the color of the background of the text window for
.BR xvnews .
Default is NULL.
.TP 12
.B XVnews.highlight
Specifies the color of the scrolling list for 
.BR xvnews .
Default is NULL.
.TP 12
.B XVnews.textfont
Specifies the font for 
.BR xvnews . 
Default is NULL.
.TP 12
.B XVnews.textfontsize
Specifies the size of the font used for 
.BR xvnews. 
Default is NULL.
.TP 12
.B XVnews.Indent
Specifies the string to be used by 
.B xvnews 
when articles are included in a post or e-mail window. Default is "> ".
.TP 12
.B XVnews.displaysize
Specifies the number of rows to be used by 
.B xvnews 
for the scrolling list. Default is 9.
.TP 12
.B XVnews.Print
Specifies the command to print articles through. Default is 
.BR "$OPENWINHOME/bin/mp | lpr" .
.TP 12
.B XVnews.saveFilter
Specifies the filter to pipe an article through. Default is NULL.
.TP 12
.B XVnews.logFile
Defines the file that outgoing postings should be logged to. Defaults to
.BR $SAVEDIR/news.record .
.TP 12
.B XVnews.Rescan
Specifies the time in minutes, 5-60, between rescans for unread articles. 
Default is 15. Most NNTP servers are set to timeout after 2 hours of socket 
inactivity.
.TP 12
.B XVnews.Header
Specifies if article headers should be shown in 
.I full 
or 
.IR abbreviated. 
Default is 
.IR abbreviated .
.TP 12
.B XVnews.SearchDefault
Sets the menu default item for the 
.I search 
button. Default is 2.
.TP 12
.B XVnews.NextDefault
Sets the menu default item for the 
.I next article 
button. Default is 2.
.TP 12
.B XVnews.PrevDefault
Sets the menu default item for the 
.I prev article 
button. Default is 2.
.TP 12
.B XVnews.sortSubjects
Whether to automatically sort the subjects for a group in alphabetical order or not.
Default is to sort in message order.
.TP 12
.B XVnews.postEditor
Name of an editor to use for posting/email, eg 'shelltool vi'. Default is xvnews
internal posting window.

.SH ENVIRONMENT VARIABLES
.B xvnews 
makes use of certain environment varibiables similar to other news readers.

The 
.B NNTPSERVER 
variable needs to be set to a valid NNTP news server for 
.B xvnews 
to run. Consult your local system administrator if you have any questions on 
valid news servers.

The 
.B DOMAIN 
variable may be set to the default domain of the system you are on. This is 
used for your the domain for the post/e-mail window. If
.B  DOMAIN 
is not set, 
.B xvnews 
makes a programmatic assumption of your domain.

The 
.B ORGANIZATION 
variable may be set to your company name. If it is unset, 
.B xvnews 
uses the default which is determined at installation time.

The 
.B NAME 
variable can be set to your real name that will appear in parentheses after 
.IR user@systemname . 
If unset, 
.B xvnews 
uses the value from the 
.I passwd 
file.

The
.B MAIL_ALIAS
variable can be set to the portion of your e-mail address that is
placed before the @ in
.IR user@systemname .
Setting this variable will result in an address like
.IR $MAIL_ALIAS@systemname instead.
If unser,
.B xvnews
uses the username.

The 
.B DOTDIR 
variable specifies what directory your 
.B .newsrc 
resides in. If this is unset, 
.B xvnews 
defaults to 
.BR $HOME . 
The ability to have different 
.B .newsrc 
files for different servers is built into
.BR xvnews . 
.B xvnews 
looks for 
.B .newsrc-$NNTPSERVER 
first, and if this file is not present, defaults to 
.BR .newsrc .

The variable 
.B SAVEDIR 
is for specifying the default directory for 
.B xvnews
to save article as well as look for an save 
.B KILL 
files. Default is 
.BR ~/News .

.SH FILES
.B xvnews
uses 
.I /tmp/.xvnews.file.getpid()
as a temorary storing place for articles, one at a time, as they are being 
read.

.B xvnews
uses the 
.B .signature 
file to place the users signature at the bottom of posts and email.
.B  xvnews
looks for a
.B ~/.signature
file after it searches the 
.B $SAVEDIR/group/name
directory for a 
.BR .signature .
This is handy if you want to have different 
.BR .signature s
for different news groups. If I wanted a different 
.B .signature
for 
.I sci.military
than every other group, I could put a 
.I .signature file 
in 
.B $SAVEDIR/sci/military
and 
.B xvnews 
would read this instead of the default 
.BR ~/.signature .

.SH SEE ALSO
.BR textedit (1),
.BR ed (1),
.I OpenWindows User's Guide

.SH AVAILABILITY
.B xvnews
is available for Sun-4 machines running either SunOS 4.x or SunOS 5.x,
and Linux. It should be portable to any Unix system with the XView libraries.

.SH BUGS
.B xvnews
currently contains a small number of bugs, as listed on top of the
.B TODO
file in the distribution. These bugs will be fixed in subsequent releases.


