.TH RESIZE 1 "Release 6" "X Version 11"
.SH NAME
hzimpath \- utility to switch current input method
and set input method searching path
.SH SYNOPSIS
.B hzimpath
[input_method | -d hzinputdir]
.SH DESCRIPTION
Without option \fB\-d\fP,
.I hzimpath
treats the argument as the name of a Chinese input method
and switches the current input method to that specified one. 
With option \fB\-d\fP,
.I hzimpath
sets the search path
for the directory containing the Chinese input methods
to be the following argument.
Alternative directory names separated by a colon ``:''
can be also put into the search path.
The search path is usually defined in the environment variable
HZINPUTDIR when \fIcxterm\fP is started,
or is given in \fIcxterm\fP option "\-hid".
.I Hzimpath
uses cxterm escape sequences to make the changing in run-time. 
(See the
.I "Xterm Control Sequences"
document.)
.SH "SEE ALSO"
cxterm(1)
.SH AUTHORS
Yongguang Zhang (Purdue University)
.br
See
.IR X (1)
for a complete copyright notice.
