.TH CROCK 5
.SH NAME
config.crock \- master configuration file for crock
.SH SYNOPSIS
.B config.crock
.SH DESCRIPTION
The 
.B config.crock
file contains entries that specify certain global game parameters, 
the locations of bitmaps and sound files and the locations of the
player-specific config files (see also 
.BR player.config(5)
).
.LP
There are four types of commands:
.I set, background, sound,
and
.I player.
Each command is terminated by a newline.
Lines that begin with a hash sign
.RB ( # )
are interpreted as comments and are ignored, as are blank linkes.
Set entries have the following form:
.IP
.I
set\ \ \ variable\ \ \ value 
.LP
.TP 10
.I
variable
can be one of the following:
.RS
.PD 0
.TP 8
.B width
to set the global width of the screen
.TP
.B height
to set the global height of the screen
.LP
.RE
.TP 10
.I
value
is a numeric value.
.PD 2
.LP
.TP 10
Background entries have the following form:
.IP
.I
background\ \ \ filename\ \ \ xoffset\ \ \ yoffset\ \ \ level_name 
.PD 2
.LP
.TP 10
.I
filename
is the full path to the X bitmap file for that background.
.TP
.I
xoffset
and 
.I
yoffset
are numeric offsets for the image in pixels.  If zero, the bottom, left
corner of the image is anchored to the bottom, left side of the window.
.TP
.I
level_name
is the name of the level.  It is a string that is terminated by the
end of a line, hence are legal characters to use.
Note that this name might be used in
.B crock
itself, for certain properties that are specific to a particular level.
.LP
Note that there can be as many 
.I background
lines as desired.  If not cached,
.B crock
will load in the image at the beginning of the match.
.LP
.TP 10
Sound entries have the following form:
.IP
.I
sound_keyword\ \ \ filename
.LP
.TP 10
.I
sound_keyword
tells 
.B crock
which sound to load.  Legal values are:
.RS
.RS
.PD 0
.TP 8
.B 
fight
for the word "fight", spoken at the start of a round.
.TP
.B finish
for the phrase "finish him", spoken at the end of a match
when a finishing move can be performed.  Since there are no female
fighters currently, a "finish her" sound has not been implemented.
.TP
.B flawless
for the phrase "flawless victory", spoken when the winner has
received no damage during a match.  There is no text displayed simultaneously
for this.
.TP
.B fatality
for the phrase "fatality", spoken after a fatality has been performed.
.TP
.B startfatal
for the sound effect at the beginning of a fatality move.  
.TP
.B player1wins
for the phrase "player one wins", spoken at the end of a round that
is won by player one.
.TP
.B player2wins
for the phrase "player two wins", spoken at the end of a round that
is won by player two.
.PD
.RE
.RE
.PD
.TP 
.I
filename
is the full path to the sound file.  It can be in any format that
.B netaudio
accepts.
.PD 2
.LP
.TP 10
Player entries have the following form:
.IP
.I
player\ \ \ filename
.PD 2
.LP
.TP 10
.I
filename
is the full path to the config file for that player.  For details
on the format of the player's config file, refer to
.BR  player.config (5).
.SH EXAMPLES
.LP
Here is a trimmed down version of the config file currently used by crock.
Note that the only difference is that the real version has more backgrounds
it uses.
.LP
.nf
set height 350
#set width 780
set width 550

#set the background image
background /n/weather/0/frank/frames/backgrounds/battlefield2.xbm 0 0 Fire Sword Shrine
background /n/weather/0/frank/frames/backgrounds/graffiti.xbm 0 0 The Playground 
background /n/weather/0/frank/frames/backgrounds/battlefield7.xbm 0 0 The Graveyard
background /n/weather/0/frank/frames/backgrounds/battlefield4.xbm 0 -25 Country Estate

#set the "fight" sound
fight /n/monster/1/remcon/frank/sounds/fight.wav

#set the "finish him" sound
finish /n/monster/1/remcon/frank/sounds/finish.wav

#set the "flawless victory" sound
flawless /n/monster/1/remcon/frank/sounds/flawless.wav

#set the "fatality" sound
fatality /n/monster/1/remcon/frank/sounds/fatality.wav

#set the start of fatality sound
startfatal /n/monster/1/remcon/frank/sounds/uh-oh.wav

#set the "player 1 wins" sound
player1wins /n/monster/1/remcon/frank/sounds/player1wins.wav

#set the "player 2 wins" sound
player2wins /n/monster/1/remcon/frank/sounds/player2wins.wav

# set up the player config files
#player /n/weather/0/frank/bin/g.load
#player /n/weather/0/frank/bin/f.load
#player /n/weather/0/frank/bin/leftg.load
#player /n/weather/0/frank/bin/rightgecko.load
player /n/weather/0/frank/bin/tb.load
player /n/weather/0/frank/bin/gecko.load
.fi
.LP
.SH FILES
.PD 0
.TP 20
.B config.crock
.TP
.B player1.config
.TP
.B player2.config
.PD
.SH SEE ALSO
.BR crock (1),
.BR player.config (5),
.BR netaudio,
.SH AUTHOR
     Copyright (c) 1994    Frank Adelstein

.\"  The X Consortium, and any party obtaining a copy of these files from
.\"  the X Consortium, directly or indirectly, is granted, free of charge, a
.\"  full and unrestricted irrevocable, world-wide, paid up, royalty-free,
.\"  nonexclusive right and license to deal in this software and
.\"  documentation files (the "Software"), including without limitation the
.\"  rights to use, copy, modify, merge, publish, distribute, sublicense,
.\"  and/or sell copies of the Software, and to permit persons who receive
.\"  copies from any such party to do so.  This license includes without
.\"  limitation a license to do the foregoing actions under any patents of
.\"  the party supplying this software to the X Consortium.
