.TH zot 1 "09 October 1993"
.SH NAME
zot - pixrect-based screen manipulation package for Suns
.SH SYNOPSIS
.B zot
.I options
.SH DESCRIPTION
.LP
.I Zot
allows you to manipulate the pixels of your (or another user's) screen
in several interesting, clever, and highly annoying ways.
Amaze your friends!
Bother your neighbors!
Enrage your sysadmins!
All this in one neat little package.
.SH OPTIONS
.TP
.B -block
Swaps blocks of pixels around the screen.
.TP
.B -flip
Flip and mirror your screen in half.
.TP
.B -melt
Slides the screen off in a melting fashion.
.TP
.B -negative
Gives a photo-negative of the screen.
.TP
.B -slide
Creates a worm that wanders the screen.
.TP
.B -snow
Snow falls down from the top of the screen.
.TP
.B -static
Another type of snow, like on your TV.
.TP
.B -vh
Vertical hold problems (like on your TV).
.TP
.B -weasel
Weasely critters burrow across the screen.
.TP
.B -zigzag
Draws random connected vectors.
.LP
For a list of modes, try typing "zot" (or "zot -help").
Options for each mode are specified with: "zot -<mode> [options]".
Also, "zot -<mode> -help" will give you the options for that particular mode.
.SH "SEE ALSO"
crumble(1)
.SH AUTHORS
Mark "Crimson" Friedman, John "Rawhide" Wile
