#!/bin/sh
LPS_LIBRARIES=/usr/local/lib/lps
LISP_DIALECT=scheme ${LPS_LIBRARIES}/lps-main $1
cps $1_h.cps
cat ${LPS_LIBRARIES}/c-suffix >> $1.c
cc -c -I$NEWSHOME/include $1.c
cat ${LPS_LIBRARIES}/scm-suffix >> $1_h.scm
#rm -f $1.c $1_h.h $1_h.cps

