/*
 * oldemo_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `oldemo.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include "oldemo_ui.h"
#include <xview/dragdrop.h>
#include <xview/cursor.h>
#include <gdd.h>
#include <group.h>


/*
 * Global object definitions.
 */
oldemo_window1_objects	*Oldemo_window1;

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(argc, argv)
	int	argc;
	char	**argv;
{
	/*
	 * Initialize XView.
	 */
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, NULL);
	INSTANCE = xv_unique_key();
	
	/*
	 * Initialize user interface components.
	 * Do NOT edit the object initializations by hand.
	 */
	Oldemo_window1 = oldemo_window1_objects_initialize(NULL, NULL);
	
	
	/*
	 * Turn control over to XView.
	 */
	gdd_init_dragdrop(Oldemo_window1->window1);
	xv_main_loop(Oldemo_window1->window1);
	exit(0);
}

#endif


/*
 * Menu handler for `fileMenu (Exit)'.
 */
Menu_item
oldemo_fileMenu_item3_callback(item, op)
	Menu_item	item;
	Menu_generate	op;
{
	oldemo_window1_objects * ip = (oldemo_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	switch (op) {
	case MENU_DISPLAY:
		break;

	case MENU_DISPLAY_DONE:
		break;

	case MENU_NOTIFY:
		fputs("oldemo: oldemo_fileMenu_item3_callback: MENU_NOTIFY\n", stderr);
		
		/* gxv_start_connections DO NOT EDIT THIS SECTION */

		{
				exit(0);	/* do it the hard way */
		}
		
		/* gxv_end_connections */

		break;

	case MENU_NOTIFY_DONE:
		break;
	}
	return item;
}

/*
 * Notify callback function for `uiSetting'.
 */
void
oldemo_window1_uiSetting_notify_callback(item, value, event)
	Panel_item	item;
	int		value;
	Event		*event;
{
	oldemo_window1_objects *ip = (oldemo_window1_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (value == 2)
	{
			puts("You draw");
	}
	
	if (value == 0)
	{
			puts("You win");
	}
	
	if (value == 1)
	{
			puts("You lose");
	}
	
	/* gxv_end_connections */

}
