/*
 * oldemo_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `oldemo.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <xview/dragdrop.h>
#include <xview/cursor.h>
#include <gdd.h>
#include <gcm.h>
#include <group.h>
#include "oldemo_ui.h"

/*
 * Create object `fileMenu' in the specified instance.
 */
Xv_opaque
oldemo_fileMenu_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	extern Menu_item	oldemo_fileMenu_item3_callback();
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Load",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Save",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Wipe out Motif",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Exit",
			MENU_GEN_PROC, oldemo_fileMenu_item3_callback,
			NULL,
		MENU_GEN_PIN_WINDOW, owner, "",
		NULL);
	return obj;
}

/*
 * Create object `editmenu' in the specified instance.
 */
Xv_opaque
oldemo_editmenu_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Cut",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Copy",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Paste",
			NULL,
		MENU_GEN_PIN_WINDOW, owner, "",
		NULL);
	return obj;
}

/*
 * Create object `viewMenu' in the specified instance.
 */
Xv_opaque
oldemo_viewMenu_create(ip, owner)
	caddr_t		ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(XV_NULL, MENU_COMMAND_MENU,
		XV_KEY_DATA, INSTANCE, ip,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Graphic...",
			NULL,
		MENU_ITEM,
			XV_KEY_DATA, INSTANCE, ip,
			MENU_STRING, "Properties...",
			NULL,
		MENU_GEN_PIN_WINDOW, owner, "",
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `window1'.
 */
oldemo_window1_objects *
oldemo_window1_objects_initialize(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (oldemo_window1_objects *) calloc(1, sizeof (oldemo_window1_objects))))
		return (oldemo_window1_objects *) NULL;
	if (!ip->window1)
		ip->window1 = oldemo_window1_window1_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = oldemo_window1_controls1_create(ip, ip->window1);
	if (!ip->drop_target1)
		ip->drop_target1 = oldemo_window1_drop_target1_create(ip, ip->controls1);
	if (!ip->fileButton)
		ip->fileButton = oldemo_window1_fileButton_create(ip, ip->controls1);
	if (!ip->viewButton2)
		ip->viewButton2 = oldemo_window1_viewButton2_create(ip, ip->controls1);
	if (!ip->editButton)
		ip->editButton = oldemo_window1_editButton_create(ip, ip->controls1);
	if (!ip->group1)
		ip->group1 = oldemo_window1_group1_create(ip, ip->controls1);
	window_fit(ip->controls1);
	
	if (!ip->canvas1)
		ip->canvas1 = oldemo_window1_canvas1_create(ip, ip->window1);
	if (!ip->controls2)
		ip->controls2 = oldemo_window1_controls2_create(ip, ip->window1);
	if (!ip->uiSetting)
		ip->uiSetting = oldemo_window1_uiSetting_create(ip, ip->controls2);
	if (!ip->tempGauge)
		ip->tempGauge = oldemo_window1_tempGauge_create(ip, ip->controls2);
	window_fit(ip->window1);
	
	xv_set(ip->controls1, XV_WIDTH, WIN_EXTEND_TO_EDGE, NULL);
	xv_set(ip->canvas1, XV_WIDTH, WIN_EXTEND_TO_EDGE, NULL);
	xv_set(ip->controls2,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `window1' in the specified instance.
 */
Xv_opaque
oldemo_window1_window1_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Xv_opaque		window1_image;
	static unsigned short	window1_bits[] = {
#include "Book_glyph.icon"
	};
	
	window1_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, window1_bits,
		XV_WIDTH, 32,
		XV_HEIGHT, 32,
		NULL);
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 520,
		XV_HEIGHT, 230,
		XV_LABEL, "OPEN LOOK Application",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_ICON, xv_create(XV_NULL, ICON,
			ICON_IMAGE, window1_image,
			NULL),
		NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
oldemo_window1_controls1_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 50,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `drop_target1' in the specified instance.
 */
Xv_opaque
oldemo_window1_drop_target1_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	Drag_drop	dnd;
	Selection_item	sel_item;
	Xv_opaque		drop_target1_normal_image;
	static unsigned short	drop_target1_normal_bits[] = {
#include "Book_glyph.icon"
	};
	
	drop_target1_normal_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, drop_target1_normal_bits,
		XV_WIDTH, 32,
		XV_HEIGHT, 32,
		NULL);
	obj = xv_create(owner, PANEL_DROP_TARGET,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 438,
		XV_Y, 5,
		PANEL_DROP_GLYPH, drop_target1_normal_image,
		NULL);
	
	dnd = xv_create(owner, DRAGDROP,
		NULL);
		
	sel_item = xv_create(dnd, SELECTION_ITEM, NULL);
	return obj;
}

/*
 * Create object `fileButton' in the specified instance.
 */
Xv_opaque
oldemo_window1_fileButton_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 15,
		XV_Y, 11,
		PANEL_LABEL_STRING, "File",
		PANEL_ITEM_MENU, oldemo_fileMenu_create((caddr_t) ip, ip->window1),
		NULL);
	return obj;
}

/*
 * Create object `viewButton2' in the specified instance.
 */
Xv_opaque
oldemo_window1_viewButton2_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 102,
		XV_Y, 12,
		PANEL_LABEL_STRING, "View",
		PANEL_ITEM_MENU, oldemo_viewMenu_create((caddr_t) ip, ip->window1),
		NULL);
	return obj;
}

/*
 * Create object `editButton' in the specified instance.
 */
Xv_opaque
oldemo_window1_editButton_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 195,
		XV_Y, 13,
		PANEL_LABEL_STRING, "Edit",
		PANEL_ITEM_MENU, oldemo_editmenu_create((caddr_t) ip, ip->window1),
		NULL);
	return obj;
}

/*
 * Create object `group1' in the specified instance.
 */
Xv_opaque
oldemo_window1_group1_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 15,
		XV_Y, 11,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->fileButton,
			ip->viewButton2,
			ip->editButton,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `canvas1' in the specified instance.
 */
Xv_opaque
oldemo_window1_canvas1_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, CANVAS,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 48,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, 88,
		NULL);
	gcm_initialize_colors(obj, "BG1", "Black");
	/*
	 * This line is here for backwards compatibility. It will be
	 * removed for the next release.
	 */
	xv_set(canvas_paint_window(obj), XV_KEY_DATA, INSTANCE, ip, NULL);
	return obj;
}

/*
 * Create object `controls2' in the specified instance.
 */
Xv_opaque
oldemo_window1_controls2_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 134,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `uiSetting' in the specified instance.
 */
Xv_opaque
oldemo_window1_uiSetting_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	extern void		oldemo_window1_uiSetting_notify_callback();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 22,
		XV_Y, 17,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_LABEL_STRING, "Preferred Interface:",
		PANEL_NOTIFY_PROC, oldemo_window1_uiSetting_notify_callback,
		PANEL_CHOICE_STRINGS,
			"OPEN LOOK",
			"Motif",
			"Other",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `tempGauge' in the specified instance.
 */
Xv_opaque
oldemo_window1_tempGauge_create(ip, owner)
	oldemo_window1_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_GAUGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 21,
		XV_Y, 55,
		PANEL_GAUGE_WIDTH, 100,
		PANEL_TICKS, 0,
		PANEL_LABEL_STRING, "GUI War Temperature:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_MIN_VALUE, 0,
		PANEL_MAX_VALUE, 100,
		PANEL_VALUE, 90,
		NULL);
	return obj;
}

