.TH openwin 1 "04 Aug 1993"
.SH NAME
openwin - startup of the X Window System in XView setup
.SH SYNOPSIS
.LP
.B openwin
.SH DESCRIPTION
.B openwin
is a frontend script for starting the XFree86 Windowing System on the
Linux operating system. The script initializes environment variables
and sets paths expected by
.B xview
applications and the
.B olwm
window manager.
.LP
If the user has a file called
.B .openwin-init
in his home directory, it will be executed to start the default client
applications. This file is created using the
.B owplaces
command, which is typically executed from the "Utilities/Save Workspace"
item in the root menu.
.SH "DESIGNER"
Kenneth Osterberg <lmfken@lmf.ericsson.se>
.SH "AVAILABILITY"
.B openwin
is part of the Linux port of XView. Get it from
.B tsx-11.mit.edu:/pub/linux/binaries/usr.bin.X11/xview3L*
.SH "BUGS"
.B openwin
execs
.B $HOME/.xinitrc
if it exists. There is a risk of unwanted side effects unless
this file is setup properly for use both with
.B openwin
and
.B startx
.SH "SEE ALSO"
.BR startx (1)
.BR olwm (1)
.BR olvwm (1)
.BR xview (1)
.BR owplaces (1)
