h01884
s 00004/00003/00125
d D 1.5 93/06/27 23:49:53 corson 5 4
c [twc 6/27/93] Added "debug" target.
e
s 00002/00002/00126
d D 1.4 93/06/14 11:24:10 corson 4 3
c [twc 6/14/93] Added new target "dist" for making distribution.
e
s 00027/00000/00101
d D 1.3 93/06/08 11:03:04 corson 3 2
c [twc 6/7/93] Added "dist" target for making distribution.
c Added copyright notice.
e
s 00017/00011/00084
d D 1.2 93/05/29 18:16:53 corson 2 1
c [twc 5/29/93]
c 
c Added a Fax Directory popup for maintaining and selecting
c Names and Fax Numbers.
c 
c Added a Properties popup for specifing Fax Host, Spool
c Directory, and filters for Viewing, Printing, and Previewing faxes.
c 
c Added fax id (filename) to Receive Queue display.
c 
c Added capability to View, Print and Delete received faxes.
c 
c All panels with scrolling lists are now resizeable and the
c scrolling lists expand/contract accordingly.  Similarly,
c FaxTool now lays out properly when invoked using the -scale
c Xview command line option.
c 
c Misc. bug fixes.
e
s 00095/00000/00000
d D 1.1 93/05/02 22:52:53 corson 1 0
c [twc 5/2/93] Initial Release (Alpha 1.0)
e
u
U
f e 0
t
T
I 3
#
#  Copyright (c) 1993 Thomas W. Corson
#  Copyright (c) 1993 VetMark Systems, Inc. d.b.a Information Dynamics
# 
#  Permission to use, copy, modify, distribute, and sell this software and 
#  its documentation for any purpose is hereby granted without fee, provided
#  that (i) the above copyright notices and this permission notice appear in
#  all copies of the software and related documentation, and (ii) the names of
#  Thomas W. Corson, VetMark Systems, or Information Dynamics may not be used 
#  in any advertising or publicity relating to the software without the 
#  specific, prior written permission of Thomas W. Corson and VetMark Systems.
#  
#  THE SOFTWARE IS PROVIDED "AS-IS" AND WITHOUT WARRANTY OF ANY KIND, 
#  EXPRESS, IMPLIED OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY 
#  WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  
#  
#  IN NO EVENT SHALL THOMAS W. CORSON OR VETMARK SYSTEMS, INC. BE LIABLE FOR
#  ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND,
#  OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
#  WHETHER OR NOT ADVISED OF THE POSSIBILITY OF DAMAGE, AND ON ANY THEORY OF 
#  LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE 
#  OF THIS SOFTWARE.
#
E 3
I 1
# This file was generated by `gxv' from `faxtool.G'.

# Parameters.

PROGRAM = faxtool
SOURCES.c = faxtool.c
SOURCES.h = faxtool.h
SOURCES.G = faxtool.G
STUBS.G = faxtool.G

# Derived parameters.

SOURCES = \
	$(SOURCES.G) \
	$(SOURCES.h) \
	$(SOURCES.l) \
	$(SOURCES.y) \
	$(SOURCES.cps) \
	$(SOURCES.c)

TARGETS.c = \
	$(SOURCES.G:%.G=%_ui.c) \
	$(STUBS.G:%.G=%_stubs.c)

TARGETS.h = \
	$(SOURCES.G:%.G=%_ui.h) \
	$(SOURCES.l:%.l=%.h) \
	$(SOURCES.y:%.y=%.h) \
	$(SOURCES.cps:%.cps=%.h)

TARGETS.other = \
	$(SOURCES.G:%.G=%.info)

TARGETS = \
	$(TARGETS.other) \
	$(TARGETS.h) \
	$(TARGETS.c)

OBJECTS = \
	$(SOURCES.c:%.c=%.o) \
	$(TARGETS.c:%.c=%.o)

# Compiler flags.

.KEEP_STATE:

CC = acc
GXVFLAGS += -ansi
D 5
#CFLAGS += -sb -g -DTRACE
E 5
CFLAGS += -sb -fast
D 2
CPPFLAGS += -I$(GUIDEHOME)/include -I$(OPENWINHOME)/include -DMAIN
LDFLAGS += -L$(GUIDEHOME)/lib -L$(OPENWINHOME)/lib
E 2
I 2
GUIDE_DIR:sh = if [ "$GUIDEHOME" ]; then echo $GUIDEHOME; else echo . ; fi
CPPFLAGS += -I$(GUIDE_DIR)/include -I$(OPENWINHOME)/include -DMAIN
LDFLAGS += -L$(GUIDE_DIR)/lib -L$(OPENWINHOME)/lib
E 2
LDLIBS += -lguidexv -lguide -lxview -lolgx -lX11

I 5
debug := CFLAGS = -sb -g -DTRACE

E 5
# Standard targets.

all:	 $(TARGETS.other) $(PROGRAM)
objects: $(SOURCES.c) $(TARGETS.c) $(TARGETS.h) $(OBJECTS)
sources: $(SOURCES)
targets: $(SOURCES) $(TARGETS)

D 5
$(PROGRAM): $(SOURCES.c) $(TARGETS.c) $(TARGETS.h) $(OBJECTS)
	$(LINK.c) -o $@ $(OBJECTS) $(LDLIBS)
E 5
I 5
$(PROGRAM) debug: $(SOURCES.c) $(TARGETS.c) $(TARGETS.h) $(OBJECTS)
	$(LINK.c) -o $(PROGRAM) $(OBJECTS) $(LDLIBS)
E 5
I 3

dist:	$(SOURCES.c) $(SOURCES.h) $(SOURCES.G) $(STUBS.G)
D 4
	tar cf faxtool.tar SCCS include lib *.icon faxtool.G faxtool.c \
			   faxtool_stubs.c faxtool.h README Makefile
E 4
I 4
	tar cf faxtool.tar SCCS include lib *.icon faxtool.G *.c \
			   *.h *.info README Makefile
E 4
E 3

# Targets to be used by Saber-C.

saber_src:
	#load $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) $(TARGET_ARCH) \
		$(SOURCES.c) $(TARGETS.c) $(LDLIBS)

saber_obj:
	#load $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) $(TARGET_ARCH) $(OBJECTS) $(LDLIBS)

clean:
D 2
	$(RM) $(SOURCES.G:%.G=%_ui.c) $(TARGETS.other) $(TARGETS.h) $(OBJECTS) *.BAK *.delta core

%_ui.c: %.G
	@if [ -f $*_stubs.c -a ! -w $*_stubs.c ]; then \
		$(RM) $*_stubs.c; \
		sccs edit -s $*_stubs.c; \
		$(GUIDEHOME)/bin/gxv $(GXVFLAGS) $*; \
		sccs delget -s -y"Generated by gxv" $*_stubs.c; \
E 2
I 2
	@if [ "$(GUIDEHOME)" ]; then \
		$(RM) $(SOURCES.G:%.G=%_ui.c) $(TARGETS.other) $(TARGETS.h) $(OBJECTS) *.BAK *.delta core; \
E 2
	else \
D 2
		$(GUIDEHOME)/bin/gxv $(GXVFLAGS) $*; \
E 2
I 2
		$(RM) $(OBJECTS) *.BAK *.delta core; \
E 2
	fi

I 2
%_ui.c: %.G
	@if [ "$(GUIDEHOME)" ]; then \
		if [ -f $*_stubs.c -a ! -w $*_stubs.c ]; then \
			$(RM) $*_stubs.c; \
			sccs edit -s $*_stubs.c; \
			$(GUIDEHOME)/bin/gxv $(GXVFLAGS) $*; \
			sccs delget -s -y"Generated by gxv" $*_stubs.c; \
		else \
			$(GUIDEHOME)/bin/gxv $(GXVFLAGS) $*; \
		fi \
	fi
E 2

%_ui.h: %_ui.c
	@touch $@

%_stubs.c: %_ui.c
	@touch $@

%.info: %_ui.c
	@touch $@
E 1
