#
# makefile for example program tree
#

WIN_HOME = /usr/openwin

PROGRAM = tree

SOURCES = tree.c tree_ui.c

OBJECTS = tree.o tree_ui.o

CC = gcc

CFLAGS = -g

CPPFLAGS = -I$(GUIDEHOME)/include -I$(WIN_HOME)/include -DMAIN

all: $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	$(CC) -L$(GUIDEHOME)/lib -L$(WIN_HOME)/lib $(OBJECTS) -lguidexv\
		-lguide -lxview -lolgx -lX11 -lm -o $(PROGRAM)

clean:
	/bin/rm -f $(OBJECTS) core