.TH aecho 1 "Release 1"  "AF Version 3"
.SH NAME
aecho - An AF play/record client.
.SH SYNOPSIS
.B
aecho 
[\fB\-d\fP \fIdevice\fP] 
.SH DESCRIPTION
\fIaecho\fP reads samples from stdin 
and sends the sound data to the 
audio server for playback.  
It simultaneously records, with the record data sent to stdout.  The play
and record operations are synchronized (i.e. the audio time of the 
first playback sample is the audio time of the first record sample).

\fIaecho\fP is useful for experimenting with room acoustics, 
and debugging audio hardware.
.SH OPTIONS
.TP
.B \-d \fIdevice\fP
.IP 
Specifies which audio device to use for playback and recording.
If \fIdevice\fP is not specified, \fIaecho\fP 
defaults to the first device that isn't connected to the telephone.
.SH ENVIRONMENT
.TP 15
.B AUDIOFILE
specifies the host and server to use.
.SH BUGS
There is no way to play back a file in preempt mode.
.PP
If you encounter a \fBreproducible\fP bug, please submit a problem report to
(af-bugs@crl.dec.com).
.SH "SEE ALSO"
AF(1), aplay(1), arecord(1)
.SH COPYRIGHT
Copyright 1992-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Andrew Payne, Digital Cambridge Research Lab, (payne@crl.dec.com)
