.TH FXCREATE 1 "November 2, 1990"
.SH NAME
fxcreate \- create a file exchange
.SH SYNOPSIS
fxcreate [ options ] name [ user ... ]
.SH DESCRIPTION
A file exchange is created with the name given.  The user who ran
fxcreate will be given grader and maintainer access to the new file
exchange, as will any users named on the command line.

Not all users are authorized to create file exchanges.
.SH OPTIONS
All options are recognized by their first letter.  For example,
-course is usually abbreviated -c, but -class or -co would also be
recognized, because each starts with the letter c.
.TP
.B -course \fIcourse\ name\fR
Deal with access control lists
for this course until the end of the command line or until another -c
option is found.  For compatibility with
.I fxblanche,
the -c may be omitted.
.TP
.B -quiet
Turns off printing of status information.
.TP
.B -verbose
Turns on printing of status information.  This is the default.
.SH EXAMPLE

.nf
fxcreate 1.00 lerman
.fi

In this example, a file exchange is named 1.00, and lerman is given
grader and maintainer access, along with the user who typed the
command.
.SH DIAGNOSTICS
If you expect to see a full name and instead see ``(no hesiod info)'',
then you have probably mistyped a username.
.SH SEE ALSO
fxblanche(1), fxdestroy(1)
.SH AUTHOR
Bruce R. Lewis (brlewis@ATHENA.MIT.EDU)
