.TH FXDESTROY 1 "September 23, 1990"
.SH NAME
fxdestroy \- destroy a file exchange
.SH SYNOPSIS
fxdestroy coursename
.SH DESCRIPTION
The file exchange for the name given is removed from the server.
No confirmation is asked for.  No trace of the file exchange or any of
the files therein is left anywhere.

Use with caution.
.SH SEE ALSO
fxcreate(1)
.SH AUTHOR
Bruce R. Lewis (brlewis@ATHENA.MIT.EDU)
