/*
 * category_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `category.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "category_ui.h"

/*
 * Initialize an instance of object `category_base'.
 */
category_category_base_objects *
category_category_base_objects_initialize(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (category_category_base_objects *) calloc(1, sizeof (category_category_base_objects))))
		return (category_category_base_objects *) NULL;
	if (!ip->category_base)
		ip->category_base = category_category_base_category_base_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = category_category_base_controls1_create(ip, ip->category_base);
	if (!ip->cat_insert_pos)
		ip->cat_insert_pos = category_category_base_cat_insert_pos_create(ip, ip->controls1);
	if (!ip->cat_insert_location)
		ip->cat_insert_location = category_category_base_cat_insert_location_create(ip, ip->controls1);
	if (!ip->cat_insert_location_name)
		ip->cat_insert_location_name = category_category_base_cat_insert_location_name_create(ip, ip->controls1);
	if (!ip->cat_name)
		ip->cat_name = category_category_base_cat_name_create(ip, ip->controls1);
	if (!ip->cat_load_from_file)
		ip->cat_load_from_file = category_category_base_cat_load_from_file_create(ip, ip->controls1);
	if (!ip->cat_cancel)
		ip->cat_cancel = category_category_base_cat_cancel_create(ip, ip->controls1);
	if (!ip->cat_done)
		ip->cat_done = category_category_base_cat_done_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `category_base' in the specified instance.
 */
Xv_opaque
category_category_base_category_base_create(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 428,
		XV_HEIGHT, 121,
		XV_LABEL, "Category Editor",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
category_category_base_controls1_create(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `cat_insert_pos' in the specified instance.
 */
Xv_opaque
category_category_base_cat_insert_pos_create(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "category:cat_insert_pos",
		XV_X, 13,
		XV_Y, 11,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_CHOICE_STRINGS,
			"Insert After",
			"Subcategory",
			NULL,
		PANEL_VALUE, 1,
		NULL);
	return obj;
}

/*
 * Create object `cat_insert_location' in the specified instance.
 */
Xv_opaque
category_category_base_cat_insert_location_create(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_ABBREV_MENU_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "category:cat_insert_location",
		XV_X, 203,
		XV_Y, 14,
		NULL);
	return obj;
}

/*
 * Create object `cat_insert_location_name' in the specified instance.
 */
Xv_opaque
category_category_base_cat_insert_location_name_create(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 230,
		XV_Y, 15,
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `cat_name' in the specified instance.
 */
Xv_opaque
category_category_base_cat_name_create(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "category:cat_name",
		XV_X, 39,
		XV_Y, 50,
		PANEL_VALUE_DISPLAY_LENGTH, 25,
		PANEL_VALUE_STORED_LENGTH, 30,
		PANEL_LABEL_STRING, "Category Name:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `cat_load_from_file' in the specified instance.
 */
Xv_opaque
category_category_base_cat_load_from_file_create(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	extern void		load_cat_from_file();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 38,
		XV_Y, 89,
		PANEL_LABEL_STRING, "Load Contents...",
		XV_SHOW, FALSE,
		PANEL_NOTIFY_PROC, load_cat_from_file,
		NULL);
	return obj;
}

/*
 * Create object `cat_cancel' in the specified instance.
 */
Xv_opaque
category_category_base_cat_cancel_create(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "category:cat_cancel",
		XV_X, 282,
		XV_Y, 89,
		PANEL_LABEL_STRING, "Cancel",
		NULL);
	return obj;
}

/*
 * Create object `cat_done' in the specified instance.
 */
Xv_opaque
category_category_base_cat_done_create(ip, owner)
	category_category_base_objects	*ip;
	Xv_opaque	owner;
{
	extern void		insert_category();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "category:cat_done",
		XV_X, 359,
		XV_Y, 89,
		PANEL_LABEL_STRING, "Done",
		PANEL_NOTIFY_PROC, insert_category,
		NULL);
	return obj;
}

