#ifndef	category_HEADER
#define	category_HEADER

/*
 * category_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `category.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	category_base;
	Xv_opaque	controls1;
	Xv_opaque	cat_insert_pos;
	Xv_opaque	cat_insert_location;
	Xv_opaque	cat_insert_location_name;
	Xv_opaque	cat_name;
	Xv_opaque	cat_load_from_file;
	Xv_opaque	cat_cancel;
	Xv_opaque	cat_done;
} category_category_base_objects;

extern category_category_base_objects	*category_category_base_objects_initialize();

extern Xv_opaque	category_category_base_category_base_create();
extern Xv_opaque	category_category_base_controls1_create();
extern Xv_opaque	category_category_base_cat_insert_pos_create();
extern Xv_opaque	category_category_base_cat_insert_location_create();
extern Xv_opaque	category_category_base_cat_insert_location_name_create();
extern Xv_opaque	category_category_base_cat_name_create();
extern Xv_opaque	category_category_base_cat_load_from_file_create();
extern Xv_opaque	category_category_base_cat_cancel_create();
extern Xv_opaque	category_category_base_cat_done_create();
#endif
