/*
 * entry_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `entry.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "entry_ui.h"

/*
 * Initialize an instance of object `entry_frame'.
 */
entry_entry_frame_objects *
entry_entry_frame_objects_initialize(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (entry_entry_frame_objects *) calloc(1, sizeof (entry_entry_frame_objects))))
		return (entry_entry_frame_objects *) NULL;
	if (!ip->entry_frame)
		ip->entry_frame = entry_entry_frame_entry_frame_create(ip, owner);
	if (!ip->entry_panel)
		ip->entry_panel = entry_entry_frame_entry_panel_create(ip, ip->entry_frame);
	if (!ip->entry_category)
		ip->entry_category = entry_entry_frame_entry_category_create(ip, ip->entry_panel);
	if (!ip->entry_category_name)
		ip->entry_category_name = entry_entry_frame_entry_category_name_create(ip, ip->entry_panel);
	if (!ip->entry_text)
		ip->entry_text = entry_entry_frame_entry_text_create(ip, ip->entry_panel);
	if (!ip->entry_priority)
		ip->entry_priority = entry_entry_frame_entry_priority_create(ip, ip->entry_panel);
	if (!ip->recurring)
		ip->recurring = entry_entry_frame_recurring_create(ip, ip->entry_panel);
	if (!ip->entry_deadline)
		ip->entry_deadline = entry_entry_frame_entry_deadline_create(ip, ip->entry_panel);
	if (!ip->entry_annotate)
		ip->entry_annotate = entry_entry_frame_entry_annotate_create(ip, ip->entry_panel);
	if (!ip->entry_cancel)
		ip->entry_cancel = entry_entry_frame_entry_cancel_create(ip, ip->entry_panel);
	if (!ip->entry_done)
		ip->entry_done = entry_entry_frame_entry_done_create(ip, ip->entry_panel);
	return ip;
}

/*
 * Create object `entry_frame' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_frame_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 459,
		XV_HEIGHT, 146,
		XV_LABEL, "Entry Editor",
		FRAME_SHOW_FOOTER, TRUE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `entry_panel' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_panel_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "entry:entry_panel",
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `entry_category' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_category_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_ABBREV_MENU_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "entry:entry_category",
		XV_X, 37,
		XV_Y, 16,
		PANEL_LABEL_STRING, "Category:",
		NULL);
	return obj;
}

/*
 * Create object `entry_category_name' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_category_name_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 138,
		XV_Y, 16,
		PANEL_LABEL_BOLD, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `entry_text' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_text_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "entry:entry_text",
		XV_X, 34,
		XV_Y, 49,
		PANEL_VALUE_DISPLAY_LENGTH, 40,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Text:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `entry_priority' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_priority_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_SLIDER,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "entry:entry_priority",
		XV_X, 34,
		XV_Y, 78,
		PANEL_SLIDER_WIDTH, 100,
		PANEL_TICKS, 0,
		PANEL_LABEL_STRING, "Priority:",
		PANEL_DIRECTION, PANEL_HORIZONTAL,
		PANEL_SLIDER_END_BOXES, FALSE,
		PANEL_SHOW_RANGE, TRUE,
		PANEL_SHOW_VALUE, TRUE,
		PANEL_MIN_VALUE, 1,
		PANEL_MAX_VALUE, 9,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `recurring' in the specified instance.
 */
Xv_opaque
entry_entry_frame_recurring_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	extern void		create_recurring();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "entry:recurring",
		XV_X, 11,
		XV_Y, 115,
		PANEL_LABEL_STRING, "Recurring...",
		PANEL_NOTIFY_PROC, create_recurring,
		NULL);
	return obj;
}

/*
 * Create object `entry_deadline' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_deadline_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	extern void		create_deadline();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "entry:entry_deadline",
		XV_X, 111,
		XV_Y, 115,
		PANEL_LABEL_STRING, "Deadline...",
		PANEL_NOTIFY_PROC, create_deadline,
		NULL);
	return obj;
}

/*
 * Create object `entry_annotate' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_annotate_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 210,
		XV_Y, 115,
		PANEL_LABEL_STRING, "Annotate...",
		XV_SHOW, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `entry_cancel' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_cancel_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	extern void		close_create();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "entry:entry_cancel",
		XV_X, 305,
		XV_Y, 115,
		PANEL_LABEL_STRING, "Cancel",
		PANEL_NOTIFY_PROC, close_create,
		NULL);
	return obj;
}

/*
 * Create object `entry_done' in the specified instance.
 */
Xv_opaque
entry_entry_frame_entry_done_create(ip, owner)
	entry_entry_frame_objects	*ip;
	Xv_opaque	owner;
{
	extern void		create_it();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "entry:entry_done",
		XV_X, 387,
		XV_Y, 115,
		PANEL_LABEL_STRING, "Done",
		PANEL_NOTIFY_PROC, create_it,
		NULL);
	return obj;
}

