#ifndef	logedit_HEADER
#define	logedit_HEADER

/*
 * logedit_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `logedit.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	log_edit;
	Xv_opaque	log_editor;
	Xv_opaque	controls1;
	Xv_opaque	log_editor_cancel;
	Xv_opaque	log_editor_done;
} logedit_log_edit_objects;

extern logedit_log_edit_objects	*logedit_log_edit_objects_initialize();

extern Xv_opaque	logedit_log_edit_log_edit_create();
extern Xv_opaque	logedit_log_edit_log_editor_create();
extern Xv_opaque	logedit_log_edit_controls1_create();
extern Xv_opaque	logedit_log_edit_log_editor_cancel_create();
extern Xv_opaque	logedit_log_edit_log_editor_done_create();
#endif
