/*
 * print_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `print.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include "print_ui.h"

/*
 * Initialize an instance of object `print_base'.
 */
print_print_base_objects *
print_print_base_objects_initialize(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	if (!ip && !(ip = (print_print_base_objects *) calloc(1, sizeof (print_print_base_objects))))
		return (print_print_base_objects *) NULL;
	if (!ip->print_base)
		ip->print_base = print_print_base_print_base_create(ip, owner);
	if (!ip->controls1)
		ip->controls1 = print_print_base_controls1_create(ip, ip->print_base);
	if (!ip->print_or_file)
		ip->print_or_file = print_print_base_print_or_file_create(ip, ip->controls1);
	if (!ip->postscript)
		ip->postscript = print_print_base_postscript_create(ip, ip->controls1);
	if (!ip->printer)
		ip->printer = print_print_base_printer_create(ip, ip->controls1);
	if (!ip->filename)
		ip->filename = print_print_base_filename_create(ip, ip->controls1);
	if (!ip->categories)
		ip->categories = print_print_base_categories_create(ip, ip->controls1);
	if (!ip->scale)
		ip->scale = print_print_base_scale_create(ip, ip->controls1);
	if (!ip->incl_checked_items)
		ip->incl_checked_items = print_print_base_incl_checked_items_create(ip, ip->controls1);
	if (!ip->cancel_print)
		ip->cancel_print = print_print_base_cancel_print_create(ip, ip->controls1);
	if (!ip->exec_print)
		ip->exec_print = print_print_base_exec_print_create(ip, ip->controls1);
	return ip;
}

/*
 * Create object `print_base' in the specified instance.
 */
Xv_opaque
print_print_base_print_base_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_WIDTH, 435,
		XV_HEIGHT, 169,
		XV_LABEL, "Print To Do List",
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, TRUE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `controls1' in the specified instance.
 */
Xv_opaque
print_print_base_controls1_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_X, 0,
		XV_Y, 0,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `print_or_file' in the specified instance.
 */
Xv_opaque
print_print_base_print_or_file_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	extern void		change_destination();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "print:print_or_file",
		XV_X, 24,
		XV_Y, 13,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_NOTIFY_PROC, change_destination,
		PANEL_CHOICE_STRINGS,
			"Send to Printer",
			"Send To a File",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `postscript' in the specified instance.
 */
Xv_opaque
print_print_base_postscript_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	extern void		change_printer_type();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "print:postscript",
		XV_X, 259,
		XV_Y, 13,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_CHOOSE_NONE, FALSE,
		PANEL_NOTIFY_PROC, change_printer_type,
		PANEL_CHOICE_STRINGS,
			"Normal",
			"Postscript",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `printer' in the specified instance.
 */
Xv_opaque
print_print_base_printer_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "print:printer",
		XV_X, 24,
		XV_Y, 50,
		PANEL_VALUE_DISPLAY_LENGTH, 8,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Printer:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `filename' in the specified instance.
 */
Xv_opaque
print_print_base_filename_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "print:filename",
		XV_X, 24,
		XV_Y, 50,
		PANEL_VALUE_DISPLAY_LENGTH, 30,
		PANEL_VALUE_STORED_LENGTH, 80,
		PANEL_LABEL_STRING, "Filename:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `categories' in the specified instance.
 */
Xv_opaque
print_print_base_categories_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "print:categories",
		XV_X, 223,
		XV_Y, 75,
		PANEL_CHOICE_NCOLS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, "Categories:",
		PANEL_CHOICE_STRINGS,
			"Current",
			"Category Tree",
			"All",
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `scale' in the specified instance.
 */
Xv_opaque
print_print_base_scale_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_NUMERIC_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "print:scale",
		XV_X, 23,
		XV_Y, 77,
		PANEL_VALUE_DISPLAY_LENGTH, 5,
		PANEL_VALUE_STORED_LENGTH, 5,
		PANEL_LABEL_STRING, "Scaling Factor:",
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_MAX_VALUE, 1000,
		PANEL_MIN_VALUE, 0,
		PANEL_VALUE, 0,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `incl_checked_items' in the specified instance.
 */
Xv_opaque
print_print_base_incl_checked_items_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	extern void		change_checked();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TOGGLE, PANEL_FEEDBACK, PANEL_MARKED,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "print:incl_checked_items",
		XV_X, 23,
		XV_Y, 102,
		PANEL_CHOICE_NROWS, 1,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, "Include Checked Items?",
		PANEL_NOTIFY_PROC, change_checked,
		PANEL_CHOICE_STRINGS,
			"Include",
			"Do Not Include",
			NULL,
		PANEL_VALUE, 0,
		NULL);
	return obj;
}

/*
 * Create object `cancel_print' in the specified instance.
 */
Xv_opaque
print_print_base_cancel_print_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	extern void		print_cancel();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "print:cancel_print",
		XV_X, 129,
		XV_Y, 136,
		PANEL_LABEL_STRING, "Cancel",
		PANEL_NOTIFY_PROC, print_cancel,
		NULL);
	return obj;
}

/*
 * Create object `exec_print' in the specified instance.
 */
Xv_opaque
print_print_base_exec_print_create(ip, owner)
	print_print_base_objects	*ip;
	Xv_opaque	owner;
{
	extern void		print_list();
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_HELP_DATA, "print:exec_print",
		XV_X, 248,
		XV_Y, 136,
		PANEL_LABEL_STRING, "Print",
		PANEL_NOTIFY_PROC, print_list,
		NULL);
	return obj;
}

