#!/bin/csh -f
#
# Shell script to convert the X11R3 fonts into NeWS fonts, using
# the "bdftofb" shell script.
#
# Instructions:
#
#   - Make a directory called "fonts", beneath the current directory.
#   - Point the XDIR variable in this shell script to your copy of the X11R3
#     source code distribution.
#   - Run this shell script, "makefonts".
#   - Sit back and relax for a while.
#   - Before you run NeWS, set the environment variable "FONTPATH" to
#     "/usr/NeWS/fonts:<wherever>/fonts". (Oh wtf, just merge the two
#     directories!)
#
# Note: The size of the FontDirectory dictionary in NeWS 1.1 is only 100.
# (It's hard wired.) However, you can fix this in init.ps by inserting
# the line "500 FontDirectory extend pop" right before the line
# "FontDirectory begin". 
#
# Copyright (C) 1988 by Don Hopkins. (don@brillig.umd.edu)
# University of Maryland Human Computer Interaction Lab.
# Feel free to redistribute this. Please send my your improvements!
#

# Point XDIR to the home of your X11R3 source distribution
set XDIR = /usr/src/new/X11R3

# Where to find the bdf files.
set XBDFDIR = $XDIR/fonts/bdf
set XCONTRIBDIR = $XDIR/contrib/fonts/bdf

# Include the new X11 fonts that work nicely with NeWS.
# (Charter and NewCenturySchlbk)
set X11FONTS = ($XBDFDIR/75dpi/{char,ncen}*.bdf)

# Include all the Mac fonts -- they're a blast!
set MACFONTS = ($XCONTRIBDIR/info-mac/*.bdf $XCONTRIBDIR/bmug/*.bdf)

# You could also include the X10 and old X11 fonts but they're pretty icky.

# Convert the mess:
bdftofb $X11FONTS
bdftofb $MACFONTS

# Group the font files into families for NeWS (by making .ff files).
bldfamily -dfonts
