.TH CTALK 1 "%Q"
.UC 5
.SH NAME
ctalk \- talk to another user in Chinese
.SH SYNOPSIS
.B ctalk
person [ ttyname ]
.SH DESCRIPTION
\fITalk\fP is a visual communication program which copies lines from your
terminal to that of another user.  \fICtalk\fP is a Chinese version of
\fItalk\fP.  \fICtalk\fP uses the same protocol as \fItalk\fP and behaves
exactly like \fItalk\fP, except that it is 8-bit clean.  Line wrapping
condition of Chinese characters are also considered.
.PP 
\fICtalk\fP should run on top of some Chinese terminal or Chinese system,
such as \fIcxterm\fP in X11 window system.
.PP
When first called, \fIctalk\fP sends the message
.PP
     Message from TalkDaemon@his_machine...
     talk: connection requested by your_name@your_machine.
     talk: respond with: talk your_name@your_machine
.PP
to the user you wish to talk to. At this point, the recipient
of the message can reply by typing
.PP
     ctalk \ your_name@your_machine
.PP
This is no distinction between \fItalk\fP and \fIctalk\fP on the
invitation message.  Usually the recipient of the above message
won't know which one it is supposed to be, \fItalk\fP or \fIctalk\fP,
but either one can be used to reply.  An automatic message 
.PP
     <<< I am using ctalk >>>
.PP
will show up in the lower window if \fIctalk\fP is used in the other end.
.SH "SEE ALSO"
talk(1), cxterm(1)
.SH BUGS
This version of \fIctalk\fP is based on 4.3BSD \fItalk\fP, which
uses a protocol that is incompatible with 4.2BSD \fItalk\fP.
\fICtalk\fP will try to contact ``ntalk'' service (usually provided
by daemon program ``ntalkd'') at UDP port 518.
It's quite possible that one can use \fItalk\fP but not \fIctalk\fP
in the same machine.
.SH AUTHOR
Yongguang Zhang  (Purdue University)
.br
E-mail: ygz@cs.purdue.edu
.PP
This version of \fIctalk\fP is hacked from the 4.3BSD reno release
of \fItalk\fP source code, which is copyrighted by the regents of
the University of California.  Please see each individual file for
the complete redistribution term.
.PP
Redistribution and use of \fIctalk\fP in source and binary forms
are permitted under the same term of the original 4.3 BSD reno
distribution.
It is provided ``AS IS'' and without any warranties.
