# (C) Universitaet Passau, Michael Himsolt 1986-1991
#########################################################################
#									#
#			    GRAPHED MAKEFILE				#
#									#
#########################################################################


#
# Directories
#
GRAPHEDDIR = ../..

#
# Sourcefiles
#
CSOURCES = tree_layout.c tree_sf.c
HSOURCES = tree.h
MYFILES = $(HSOURCES) $(CSOURCES)

MODULE=tree
include ../makefile.template
include $(GRAPHEDDIR)/makefile.template


# DO NOT DELETE THIS LINE -- make depend depends on it.

tree_layout.o: /usr/openwin/include/xview/xview.h
tree_layout.o: /usr/openwin/include/xview/xview_xvin.h /usr/include/signal.h
tree_layout.o: /usr/include/sys/signal.h /usr/include/vm/faultcode.h
tree_layout.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
tree_layout.o: /usr/include/sys/sysmacros.h /usr/include/pixrect/pixrect.h
tree_layout.o: /usr/include/pixrect/pr_planegroups.h
tree_layout.o: /usr/include/pixrect/pr_util.h /usr/include/pixrect/memvar.h
tree_layout.o: /usr/include/pixrect/pixfont.h /usr/include/pixrect/traprop.h
tree_layout.o: /usr/include/pixrect/pr_line.h
tree_layout.o: /usr/openwin/include/xview/xv_c_types.h
tree_layout.o: /usr/openwin/include/xview/generic.h
tree_layout.o: /usr/openwin/include/xview/pkg_public.h
tree_layout.o: /usr/openwin/include/xview/pkg.h
tree_layout.o: /usr/openwin/include/xview/attr.h
tree_layout.o: /usr/openwin/include/xview/base.h /usr/include/string.h
tree_layout.o: /usr/include/malloc.h /usr/openwin/include/xview/notify.h
tree_layout.o: /usr/include/stdio.h /usr/include/sys/wait.h
tree_layout.o: /usr/include/sys/time.h /usr/include/sys/time.h
tree_layout.o: /usr/include/sys/resource.h /usr/include/varargs.h
tree_layout.o: /usr/openwin/include/xview/xv_error.h
tree_layout.o: /usr/openwin/include/xview/sun.h
tree_layout.o: /usr/openwin/include/xview/server.h
tree_layout.o: /usr/openwin/include/xview/screen.h
tree_layout.o: /usr/openwin/include/xview/pixwin.h
tree_layout.o: /usr/openwin/include/xview/rect.h
tree_layout.o: /usr/openwin/include/xview/rectlist.h
tree_layout.o: /usr/openwin/include/xview/win_input.h
tree_layout.o: /usr/openwin/include/X11/Xlib.h /usr/openwin/include/X11/X.h
tree_layout.o: /usr/openwin/include/xview/win_event.h
tree_layout.o: /usr/openwin/include/xview/xv_version.h
tree_layout.o: /usr/openwin/include/xview/icon.h
tree_layout.o: /usr/openwin/include/xview/window.h
tree_layout.o: /usr/openwin/include/xview/drawable.h
tree_layout.o: /usr/openwin/include/xview/attrol.h
tree_layout.o: /usr/openwin/include/xview/svrimage.h
tree_layout.o: /usr/openwin/include/xview/frame.h
tree_layout.o: /usr/openwin/include/xview/openmenu.h
tree_layout.o: /usr/openwin/include/xview/panel.h
tree_layout.o: /usr/openwin/include/xview/canvas.h
tree_layout.o: /usr/openwin/include/xview/openwin.h ../../sgraph/std.h
tree_layout.o: /usr/include/assert.h ../../sgraph/slist.h
tree_layout.o: ../../sgraph/sgraph.h ../../sgraph/graphed.h
tree_layout.o: ../../sgraph/graphed_structures.h
tree_layout.o: ../../sgraph/dispatch_commands.h
tree_layout.o: ../../sgraph/sgraph_interface.h
tree_layout.o: ../../sgraph/sgragra_interface.h tree.h
tree_sf.o: /usr/openwin/include/xview/xview.h
tree_sf.o: /usr/openwin/include/xview/xview_xvin.h /usr/include/signal.h
tree_sf.o: /usr/include/sys/signal.h /usr/include/vm/faultcode.h
tree_sf.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
tree_sf.o: /usr/include/sys/sysmacros.h /usr/include/pixrect/pixrect.h
tree_sf.o: /usr/include/pixrect/pr_planegroups.h
tree_sf.o: /usr/include/pixrect/pr_util.h /usr/include/pixrect/memvar.h
tree_sf.o: /usr/include/pixrect/pixfont.h /usr/include/pixrect/traprop.h
tree_sf.o: /usr/include/pixrect/pr_line.h
tree_sf.o: /usr/openwin/include/xview/xv_c_types.h
tree_sf.o: /usr/openwin/include/xview/generic.h
tree_sf.o: /usr/openwin/include/xview/pkg_public.h
tree_sf.o: /usr/openwin/include/xview/pkg.h /usr/openwin/include/xview/attr.h
tree_sf.o: /usr/openwin/include/xview/base.h /usr/include/string.h
tree_sf.o: /usr/include/malloc.h /usr/openwin/include/xview/notify.h
tree_sf.o: /usr/include/stdio.h /usr/include/sys/wait.h
tree_sf.o: /usr/include/sys/time.h /usr/include/sys/time.h
tree_sf.o: /usr/include/sys/resource.h /usr/include/varargs.h
tree_sf.o: /usr/openwin/include/xview/xv_error.h
tree_sf.o: /usr/openwin/include/xview/sun.h
tree_sf.o: /usr/openwin/include/xview/server.h
tree_sf.o: /usr/openwin/include/xview/screen.h
tree_sf.o: /usr/openwin/include/xview/pixwin.h
tree_sf.o: /usr/openwin/include/xview/rect.h
tree_sf.o: /usr/openwin/include/xview/rectlist.h
tree_sf.o: /usr/openwin/include/xview/win_input.h
tree_sf.o: /usr/openwin/include/X11/Xlib.h /usr/openwin/include/X11/X.h
tree_sf.o: /usr/openwin/include/xview/win_event.h
tree_sf.o: /usr/openwin/include/xview/xv_version.h
tree_sf.o: /usr/openwin/include/xview/icon.h
tree_sf.o: /usr/openwin/include/xview/window.h
tree_sf.o: /usr/openwin/include/xview/drawable.h
tree_sf.o: /usr/openwin/include/xview/attrol.h
tree_sf.o: /usr/openwin/include/xview/svrimage.h
tree_sf.o: /usr/openwin/include/xview/frame.h
tree_sf.o: /usr/openwin/include/xview/openmenu.h
tree_sf.o: /usr/openwin/include/xview/panel.h
tree_sf.o: /usr/openwin/include/xview/canvas.h
tree_sf.o: /usr/openwin/include/xview/openwin.h ../../sgraph/std.h
tree_sf.o: /usr/include/assert.h ../../sgraph/sgraph.h
tree_sf.o: ../../sgraph/algorithms.h tree.h ../../graphed/gridder.h
