.ds xL AFlib \- C Language AF Interface
.na
.de Ds
.nf
.\\$1D \\$2 \\$1
.ft 1
.\".ps \\n(PS
.\".if \\n(VS>=40 .vs \\n(VSu
.\".if \\n(VS<=39 .vs \\n(VSp
..
.de De
.ce 0
.if \\n(BD .DF
.nr BD 0
.in \\n(OIu
.if \\n(TM .ls 2
.sp \\n(DDu
.fi
..
.de FD
.LP
.KS
.TA .5i 3i
.ta .5i 3i
.nf
..
.de FN
.fi
.KE
.LP
..
.de IN		\" send an index entry to the stderr
.tm \\n%:\\$1:\\$2:\\$3
..
.de C{
.KS
.nf
.D
.\"
.\"	choose appropriate monospace font
.\"	the imagen conditional, 480,
.\"	may be changed to L if LB is too
.\"	heavy for your eyes...
.\"
.ie "\\*(.T"480" .ft L
.el .ie "\\*(.T"300" .ft L
.el .ie "\\*(.T"202" .ft PO
.el .ie "\\*(.T"aps" .ft CW
.el .ft R
.ps \\n(PS
.ie \\n(VS>40 .vs \\n(VSu
.el .vs \\n(VSp
..
.de C}
.DE
.R
..
.de Pn
.ie t \\$1\fB\^\\$2\^\fR\\$3
.el \\$1\fI\^\\$2\^\fP\\$3
..
.de PN
.ie t \fB\^\\$1\^\fR\\$2
.el \fI\^\\$1\^\fP\\$2
..
.de NT
.ne 7
.ds NO Note
.if \\n(.$>$1 .if !'\\$2'C' .ds NO \\$2
.if \\n(.$ .if !'\\$1'C' .ds NO \\$1
.ie n .sp
.el .sp 10p
.TB
.ce
\\*(NO
.ie n .sp
.el .sp 5p
.if '\\$1'C' .ce 99
.if '\\$2'C' .ce 99
.in +5n
.ll -5n
.R
..
.		\" Note End -- doug kraft 3/85
.de NE
.ce 0
.in -5n
.ll +5n
.ie n .sp
.el .sp 10p
..
.ny0
.TH libAFUtil 3 "Release 1" "AF Version 3" 
.SH NAME
\fBlibAFUtil.a\fI \- Utility AF Library
.SH Header Files
\fB#include <AF/AFUtils.h>\fP
.SH Gain Control
.LP
extern double \fBAFLintodB\fP(double \fIlin\fP);
.LP
extern double \fBAFdBtoLin\fP(double \fIdB\fP);
.LP
extern void \fBAFMakeGainTableU\fP(unsigned char \fI*table\fP, double \fIdBgain\fP);
.LP
extern void \fBAFMakeGainTableA\fP(unsigned char \fI*table\fP, double \fIdBgain\fP);
.SH Signal Generation
.LP
extern void \fBAFSilence\fP(AEncodeType \fIencoding\fP, void* \fIbuffer\fP, 
int \fInUnits\fP);
.LP
extern double \fBAFSingleTone\fP(double \fIfreq\fP, double \fIpeak\fP, 
.br
                                        double \fIphase\fP, 
.br
                                        float \fI*buffer\fP, int \fIlength\fP);
.LP
extern void \fBAFTonePair\fP(double \fIf1\fP, double \fIdBgain1\fP, 
.br
                                        double \fIf2\fP, double \fIdBgain2\fP, 
.br
                                        int \fIgainramp\fP, 
.br
                                        unsigned char \fI*buffer\fP, int \fIlength\fP);
.SH Miscellaneous
.LP
extern void \fBAoD\fP(int \fIbool\fP, char \fI*errmsg\fP, ...);
.SH Conversion Tables
.LP
extern unsigned char \fBAF_comp_u\fP[];
.LP
extern unsigned char \fBAF_comp_a\fP[];
.LP
extern short int \fBAF_exp_u\fP[];
.LP
extern short int \fBAF_exp_a\fP[];
.LP
extern short int \fBAF_cvt_u2s\fP[];
.LP
extern short int \fBAF_cvt_a2s\fP[];
.LP
extern float \fBAF_cvt_u2f\fP[];
.LP
extern float \fBAF_cvt_a2f\fP[];
.SH Mixing Tables
.LP
extern unsigned char \fBAF_mix_u\fP[];
.LP
extern unsigned char \fBAF_mix_a\fP[];
.SH Gain Tables
.LP
extern int AF_gain_min_u, AF_gain_max_u;
.LP
extern unsigned char *\fBAF_gain_table_u\fP[];
.LP
extern int AF_gain_min_a, AF_gain_max_a;
.LP
extern unsigned char *\fBAF_gain_table_a\fP[];
.SH Power Tables
extern float \fBAF_power_uf\fP[];
.LP
extern float \fBAF_power_af\fP[];
.SH Sine Wave Tables
.LP
extern int \fBAF_sine_int\fP[];
.LP
extern float \fBAF_sine_float\fP[];
.SH Encoding Information Tables
.LP
extern struct AFSampleTypes \fBAF_sample_sizes\fP[];
.LP
extern AEncodeType \fBAFFindEncodeType\fP(char \fI*type\fP);
.LP
extern void \fBAFPrintKnownEncodeTypes\fP(\fIvoid\fP);
.SH "SEE ALSO"
libAF(3), AF(1)
.br
AFLintodB(3), AFdBtoLin(3), AFMakeGainTableU(3),
.br
AFMakeGainTableA(3), AFSilence(3), AFSingleTone(3),
.br
AFTonePair(3), AoD(3), 
.br
AFFindEncodeType(3), AFPrintKnownEncodeTypes(3),
.br
AF_comp_u(3), AF_comp_a(3), AF_exp_u(3), AF_exp_a(3),
.br
AF_cvt_u2s(3), AF_cvt_a2s(3), AF_cvt_u2f(3),
.br
AF_cvt_a2f(3), AF_mix_u(3), AF_mix_a(3),
.br
AF_gain_table_u(3), AF_gain_table_a(3), AF_power_uf(3),
.br
AF_power_af(3), AF_sine_int(3), AF_sine_float(3),
.br
AF_sample_sizes(3), AF_gain_min_a(3), AF_gain_max_a(3),
.br
AF_gain_min_u(3), AF_gain_max_u(3)
.SH BUGS
If you encounter a \fBreproducible\fP bug, please 
submit a problem report to (af-bugs@crl.dec.com).
.SH COPYRIGHT
Copyright 1990-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Digital Cambridge Research Lab
