.TH screenload 1 "09 October 1993"
.SH NAME
screenload - screen loading program for Suns
.SH SYNOPSIS
.B screenload
.RB [ -black ]
.RB [ -white ]
.RB [ -index
.IR color ]
.RB [ -gray ]
.RB [ -hexfill
.I count word
.IR ... ]
.RB [ -random ]
.RB [ -nofill ]
.RB [ -tile ]
.RB [ -pause ]
.RB [ -sleep
.IR msec ]
.RB [ -fb
.IR framebuffer ]
.RI [ rasterfile
.IR ... ]
.SH DESCRIPTION
.LP
.I Screenload
is an almost upward-compatible replacement for Sun's old
.IR screenload .
It reads in one or more rasterfiles and displays them on the screen, with
a specified background.
If no rasterfiles are specified on the command line, it reads from stdin.
.SH OPTIONS
.TP
.B -black
If the rasterfile is smaller than the full screen, fill in the border
with black.
This is the default.
.TP
.B -white
Fill in the border with white.
.TP
.B -index
For color displays, use this number as the colormap index of the background.
.TP
.B -gray
Fill in the border with desktop gray.
.TP
.B -hexfill
Fill in the border with the specified pattern of
.I count
16-bit hexadecimal words.
A one bit is black and a zero bit is white, and
each word is one row in the 16-pixel-wide pattern.
.TP
.B -random
Fill in the background with a random 50% gray pattern.
.TP
.B -nofill
Don't do any background filling.
.TP
.B -tile
Replicate the rasterfile over the entire screen.
.TP
.B -pause
Wait for a newline to be typed on stdin before going on to the
next rasterfile or exiting.
.TP
.B -sleep
Wait for the specified number of milliseconds before displaying the
next rasterfile (it's actually fairly clever about keeping the
interval between rasterfiles constant regardless of their size).
.TP
.B -fb
Use an alternate frame buffer.
The default is /dev/fb.
.LP
All flags can be abbreviated to their shortest unique prefix.
.SH "SUMMARY OF DIFFERENCES"
.TP
o
Old
.I screenload
used single-character flags, with combinations permitted;
this version uses multi-character flags, with abbreviations permitted.
.TP
o
This version
adds the
.BR -tile ,
.BR -random ,
and
.B -sleep
flags.
.TP
o
This version
will read and display multiple rasterfiles in sequence - this plus the
.B -sleep
flag lets you do simple animations.
.TP
o
Old
.IR screenload 's
.B -g
flag gave you the SunView gray pattern;
this version's
.B -gray
flag gives you the X11 gray pattern.
.TP
o
In old
.IR screenload ,
the
.B -h
flag took a hex count and a list of hex 16-bit patterns;
in this version,
the
.B -hex
flag takes a *decimal* count, plus the hex patterns.
.SH "SEE ALSO"
screendump(1)
.SH AUTHOR
Copyright (C) 1991, 1993 by Jef Poskanzer <jef@netcom.com>.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
