# (C) Universitaet Passau, Michael Himsolt 1986-1991
#########################################################################
#									#
#			    GRAPHED MAKEFILE				#
#									#
#########################################################################


#
# Directories
#
GRAPHEDDIR = ../..

#
# Sourcefiles
#
CSOURCES = nature.c springembedder_sf.c
HSOURCES = springembedder.h
MYFILES = $(HSOURCES) $(CSOURCES)

MODULE=springembedder
include ../makefile.template
include $(GRAPHEDDIR)/makefile.template

# DO NOT DELETE THIS LINE -- make depend depends on it.

nature.o: ../../sgraph/std.h /usr/include/assert.h /usr/include/stdio.h
nature.o: /usr/include/malloc.h ../../sgraph/sgraph.h ../../sgraph/slist.h
nature.o: ../../sgraph/graphed.h ../../sgraph/graphed_structures.h
nature.o: /usr/openwin/include/xview/rect.h
nature.o: /usr/openwin/include/xview/xv_c_types.h
nature.o: ../../sgraph/dispatch_commands.h ../../sgraph/sgraph_interface.h
nature.o: ../../sgraph/sgragra_interface.h /usr/include/math.h
nature.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
nature.o: /usr/openwin/include/xview/xview.h
nature.o: /usr/openwin/include/xview/xview_xvin.h /usr/include/signal.h
nature.o: /usr/include/sys/signal.h /usr/include/vm/faultcode.h
nature.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
nature.o: /usr/include/sys/sysmacros.h /usr/include/pixrect/pixrect.h
nature.o: /usr/include/pixrect/pr_planegroups.h
nature.o: /usr/include/pixrect/pr_util.h /usr/include/pixrect/memvar.h
nature.o: /usr/include/pixrect/pixfont.h /usr/include/pixrect/traprop.h
nature.o: /usr/include/pixrect/pr_line.h /usr/openwin/include/xview/generic.h
nature.o: /usr/openwin/include/xview/pkg_public.h
nature.o: /usr/openwin/include/xview/pkg.h /usr/openwin/include/xview/attr.h
nature.o: /usr/openwin/include/xview/base.h /usr/include/string.h
nature.o: /usr/openwin/include/xview/notify.h /usr/include/sys/wait.h
nature.o: /usr/include/sys/time.h /usr/include/sys/time.h
nature.o: /usr/include/sys/resource.h /usr/include/varargs.h
nature.o: /usr/openwin/include/xview/xv_error.h
nature.o: /usr/openwin/include/xview/sun.h
nature.o: /usr/openwin/include/xview/server.h
nature.o: /usr/openwin/include/xview/screen.h
nature.o: /usr/openwin/include/xview/pixwin.h
nature.o: /usr/openwin/include/xview/rectlist.h
nature.o: /usr/openwin/include/xview/win_input.h
nature.o: /usr/openwin/include/X11/Xlib.h /usr/openwin/include/X11/X.h
nature.o: /usr/openwin/include/xview/win_event.h
nature.o: /usr/openwin/include/xview/xv_version.h
nature.o: /usr/openwin/include/xview/icon.h
nature.o: /usr/openwin/include/xview/window.h
nature.o: /usr/openwin/include/xview/drawable.h
nature.o: /usr/openwin/include/xview/attrol.h
nature.o: /usr/openwin/include/xview/svrimage.h
nature.o: /usr/openwin/include/xview/frame.h
nature.o: /usr/openwin/include/xview/openmenu.h springembedder.h
springembedder_sf.o: /usr/openwin/include/xview/xview.h
springembedder_sf.o: /usr/openwin/include/xview/xview_xvin.h
springembedder_sf.o: /usr/include/signal.h /usr/include/sys/signal.h
springembedder_sf.o: /usr/include/vm/faultcode.h /usr/include/sys/types.h
springembedder_sf.o: /usr/include/sys/stdtypes.h /usr/include/sys/sysmacros.h
springembedder_sf.o: /usr/include/pixrect/pixrect.h
springembedder_sf.o: /usr/include/pixrect/pr_planegroups.h
springembedder_sf.o: /usr/include/pixrect/pr_util.h
springembedder_sf.o: /usr/include/pixrect/memvar.h
springembedder_sf.o: /usr/include/pixrect/pixfont.h
springembedder_sf.o: /usr/include/pixrect/traprop.h
springembedder_sf.o: /usr/include/pixrect/pr_line.h
springembedder_sf.o: /usr/openwin/include/xview/xv_c_types.h
springembedder_sf.o: /usr/openwin/include/xview/generic.h
springembedder_sf.o: /usr/openwin/include/xview/pkg_public.h
springembedder_sf.o: /usr/openwin/include/xview/pkg.h
springembedder_sf.o: /usr/openwin/include/xview/attr.h
springembedder_sf.o: /usr/openwin/include/xview/base.h /usr/include/string.h
springembedder_sf.o: /usr/include/malloc.h
springembedder_sf.o: /usr/openwin/include/xview/notify.h /usr/include/stdio.h
springembedder_sf.o: /usr/include/sys/wait.h /usr/include/sys/time.h
springembedder_sf.o: /usr/include/sys/time.h /usr/include/sys/resource.h
springembedder_sf.o: /usr/include/varargs.h
springembedder_sf.o: /usr/openwin/include/xview/xv_error.h
springembedder_sf.o: /usr/openwin/include/xview/sun.h
springembedder_sf.o: /usr/openwin/include/xview/server.h
springembedder_sf.o: /usr/openwin/include/xview/screen.h
springembedder_sf.o: /usr/openwin/include/xview/pixwin.h
springembedder_sf.o: /usr/openwin/include/xview/rect.h
springembedder_sf.o: /usr/openwin/include/xview/rectlist.h
springembedder_sf.o: /usr/openwin/include/xview/win_input.h
springembedder_sf.o: /usr/openwin/include/X11/Xlib.h
springembedder_sf.o: /usr/openwin/include/X11/X.h
springembedder_sf.o: /usr/openwin/include/xview/win_event.h
springembedder_sf.o: /usr/openwin/include/xview/xv_version.h
springembedder_sf.o: /usr/openwin/include/xview/icon.h
springembedder_sf.o: /usr/openwin/include/xview/window.h
springembedder_sf.o: /usr/openwin/include/xview/drawable.h
springembedder_sf.o: /usr/openwin/include/xview/attrol.h
springembedder_sf.o: /usr/openwin/include/xview/svrimage.h
springembedder_sf.o: /usr/openwin/include/xview/frame.h
springembedder_sf.o: /usr/openwin/include/xview/openmenu.h
springembedder_sf.o: /usr/openwin/include/xview/panel.h
springembedder_sf.o: /usr/openwin/include/xview/canvas.h
springembedder_sf.o: /usr/openwin/include/xview/openwin.h ../../sgraph/std.h
springembedder_sf.o: /usr/include/assert.h ../../sgraph/sgraph.h
springembedder_sf.o: ../../sgraph/slist.h ../../sgraph/graphed.h
springembedder_sf.o: ../../sgraph/graphed_structures.h
springembedder_sf.o: ../../sgraph/dispatch_commands.h
springembedder_sf.o: ../../sgraph/sgraph_interface.h
springembedder_sf.o: ../../sgraph/sgragra_interface.h /usr/include/math.h
springembedder_sf.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
springembedder_sf.o: springembedder.h ../../graphed/gridder.h
