.\" $Id: xepsf.man,v 6.1 1994/05/18 23:21:46 asente Exp $
.TH XEPSF 1 "4 May 1994" "Adobe Systems"
.SH NAME
xepsf \- display an Encapsulated PostScript file
.SH SYNOPSIS
.B xepsf 
[
.B \-display \fIname\fR
][
.B \-mag n
] 
.I filename

.SH DESCRIPTION
.LP
.B xepsf
is a Display PostScript program that displays an Encapsulated PostScript file.

.SH OPTIONS
.TP
.BI \-display " name"
specifies the display on which to open a connection to the Display
PostScript system. If no display is specified, the 
DISPLAY environment variable is used.
.TP
.BI \-mag " n"
scales the image by a factor of 
.I n.
The scale factor may be either an integer or a floating-point number.

.SH DIAGNOSTICS
.LP
Error messages are printed to standard output.

.SH AUTHOR
.LP
Adobe Systems Incorporated

.SH NOTES
.LP
PostScript and Display PostScript are trademarks
of Adobe Systems Incorporated which may be registered
in certain jurisdictions.
.LP
Copyright (c) 1990-1994 Adobe Systems Incorporated.  All rights reserved.
