#ifndef	genix_HEADER
#define	genix_HEADER

/*
 * genix_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `genix.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;

extern Xv_opaque	genix_fileMenu_create();
extern Xv_opaque	genix_viewMenu_create();
extern Xv_opaque	genix_editMenu_create();

typedef struct {
	Xv_opaque	rootsWindow;
	Xv_opaque	menubarPanel;
	Xv_opaque	fileButton;
	Xv_opaque	viewButton;
	Xv_opaque	editButton;
	Xv_opaque	locateButton;
	Xv_opaque	persPanel;
	Xv_opaque	persTitle;
	Xv_opaque	surnameTF;
	Xv_opaque	gnameTF;
	Xv_opaque	bdateTF;
	Xv_opaque	bplaceTF;
	Xv_opaque	ddateTF;
	Xv_opaque	dplaceTF;
	Xv_opaque	sexChoice;
	Xv_opaque	applyButton;
} genix_rootsWindow_objects;

extern genix_rootsWindow_objects	*genix_rootsWindow_objects_initialize();

extern Xv_opaque	genix_rootsWindow_rootsWindow_create();
extern Xv_opaque	genix_rootsWindow_menubarPanel_create();
extern Xv_opaque	genix_rootsWindow_fileButton_create();
extern Xv_opaque	genix_rootsWindow_viewButton_create();
extern Xv_opaque	genix_rootsWindow_editButton_create();
extern Xv_opaque	genix_rootsWindow_locateButton_create();
extern Xv_opaque	genix_rootsWindow_persPanel_create();
extern Xv_opaque	genix_rootsWindow_persTitle_create();
extern Xv_opaque	genix_rootsWindow_surnameTF_create();
extern Xv_opaque	genix_rootsWindow_gnameTF_create();
extern Xv_opaque	genix_rootsWindow_bdateTF_create();
extern Xv_opaque	genix_rootsWindow_bplaceTF_create();
extern Xv_opaque	genix_rootsWindow_ddateTF_create();
extern Xv_opaque	genix_rootsWindow_dplaceTF_create();
extern Xv_opaque	genix_rootsWindow_sexChoice_create();
extern Xv_opaque	genix_rootsWindow_applyButton_create();

typedef struct {
	Xv_opaque	relationsWindow;
	Xv_opaque	controls1;
	Xv_opaque	unionTitle;
	Xv_opaque	leftList;
	Xv_opaque	rightList;
	Xv_opaque	relChoice;
	Xv_opaque	relationsListGroup;
	Xv_opaque	unionidTF;
	Xv_opaque	unionapplyButton;
	Xv_opaque	relationsButtonGroup;
} genix_relationsWindow_objects;

extern genix_relationsWindow_objects	*genix_relationsWindow_objects_initialize();

extern Xv_opaque	genix_relationsWindow_relationsWindow_create();
extern Xv_opaque	genix_relationsWindow_controls1_create();
extern Xv_opaque	genix_relationsWindow_unionTitle_create();
extern Xv_opaque	genix_relationsWindow_leftList_create();
extern Xv_opaque	genix_relationsWindow_rightList_create();
extern Xv_opaque	genix_relationsWindow_relChoice_create();
extern Xv_opaque	genix_relationsWindow_relationsListGroup_create();
extern Xv_opaque	genix_relationsWindow_unionidTF_create();
extern Xv_opaque	genix_relationsWindow_unionapplyButton_create();
extern Xv_opaque	genix_relationsWindow_relationsButtonGroup_create();

typedef struct {
	Xv_opaque	treeWindow;
	Xv_opaque	controls2;
	Xv_opaque	message1;
} genix_treeWindow_objects;

extern genix_treeWindow_objects	*genix_treeWindow_objects_initialize();

extern Xv_opaque	genix_treeWindow_treeWindow_create();
extern Xv_opaque	genix_treeWindow_controls2_create();
extern Xv_opaque	genix_treeWindow_message1_create();

typedef struct {
	Xv_opaque	locateWindow;
} genix_locateWindow_objects;

extern genix_locateWindow_objects	*genix_locateWindow_objects_initialize();

extern Xv_opaque	genix_locateWindow_locateWindow_create();
#endif
