.ds xL AFlib \- C Language AF Interface
.na
.de Ds
.nf
.\\$1D \\$2 \\$1
.ft 1
.\".ps \\n(PS
.\".if \\n(VS>=40 .vs \\n(VSu
.\".if \\n(VS<=39 .vs \\n(VSp
..
.de De
.ce 0
.if \\n(BD .DF
.nr BD 0
.in \\n(OIu
.if \\n(TM .ls 2
.sp \\n(DDu
.fi
..
.de FD
.LP
.KS
.TA .5i 3i
.ta .5i 3i
.nf
..
.de FN
.fi
.KE
.LP
..
.de IN		\" send an index entry to the stderr
.tm \\n%:\\$1:\\$2:\\$3
..
.de C{
.KS
.nf
.D
.\"
.\"	choose appropriate monospace font
.\"	the imagen conditional, 480,
.\"	may be changed to L if LB is too
.\"	heavy for your eyes...
.\"
.ie "\\*(.T"480" .ft L
.el .ie "\\*(.T"300" .ft L
.el .ie "\\*(.T"202" .ft PO
.el .ie "\\*(.T"aps" .ft CW
.el .ft R
.ps \\n(PS
.ie \\n(VS>40 .vs \\n(VSu
.el .vs \\n(VSp
..
.de C}
.DE
.R
..
.de Pn
.ie t \\$1\fB\^\\$2\^\fR\\$3
.el \\$1\fI\^\\$2\^\fP\\$3
..
.de PN
.ie t \fB\^\\$1\^\fR\\$2
.el \fI\^\\$1\^\fP\\$2
..
.de NT
.ne 7
.ds NO Note
.if \\n(.$>$1 .if !'\\$2'C' .ds NO \\$2
.if \\n(.$ .if !'\\$1'C' .ds NO \\$1
.ie n .sp
.el .sp 10p
.TB
.ce
\\*(NO
.ie n .sp
.el .sp 5p
.if '\\$1'C' .ce 99
.if '\\$2'C' .ce 99
.in +5n
.ll -5n
.R
..
.		\" Note End -- doug kraft 3/85
.de NE
.ce 0
.in -5n
.ll +5n
.ie n .sp
.el .sp 10p
..
.ny0
.TH AFEnableInput 3 "Release 1" "AF Version 3" 
.SH NAME
\fBAFEnableInput, AFDisableInput, AFEnableOutput, AFDisableOutput\fP \- enable
or disable input or output
.SH SYNTAX
\fB#include <AF/AFlib.h>\fP
.LP
void \fBAFEnableInput\fP (AC \fIac\fP, AMask \fImask\fP, AMask \fI*old_state\fP, AMask \fI*new_state\fP)
.LP
void \fBAFDisableInput\fP (AC \fIac\fP, AMask \fImask\fP, AMask \fI*old_state\fP, AMask \fI*new_state\fP)
.LP
void \fBAFEnableOutput\fP (AC \fIac\fP, AMask \fImask\fP, AMask \fI*old_state\fP, AMask \fI*new_state\fP)
.LP
void \fBAFDisableOutput\fP (AC \fIac\fP, AMask \fImask\fP, AMask \fI*old_state\fP, 
.br
                            AMask \fI*new_state\fP)
.SH ARGUMENTS
.IP \fIac\fP 1i
The audio context of an audio device.
.IP \fImask\fP 1i
A bit vector indicating the inputs (or outputs) to enable (or disable).
.IP \fIold_state\fP 1i
The state of the previous input(output) mask is returned in the location
pointed to by \fIold_state\fP.
.IP \fInew_state\fP 1i
The state of the input(output) mask set by the server as a result
of this call is returned in the location
pointed to by \fInew_state\fP.
.SH DESCRIPTION
Individual inputs on an audio device can be enabled using
.PN AFEnableInput
and disabled with
.PN AFDisableInput.
.LP
Individual outputs on an audio device can be enabled using
.PN AFEnableOutput
and disabled with
.PN AFDisableOutput.
.SH "SEE ALSO"
AF(1)
.br

.SH BUGS
If you encounter a \fBreproducible\fP bug, please 
submit a problem report to (af-bugs@crl.dec.com).
.SH COPYRIGHT
Copyright 1990-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Digital Cambridge Research Lab
