.ds xL AFlib \- C Language AF Interface
.na
.de Ds
.nf
.\\$1D \\$2 \\$1
.ft 1
.\".ps \\n(PS
.\".if \\n(VS>=40 .vs \\n(VSu
.\".if \\n(VS<=39 .vs \\n(VSp
..
.de De
.ce 0
.if \\n(BD .DF
.nr BD 0
.in \\n(OIu
.if \\n(TM .ls 2
.sp \\n(DDu
.fi
..
.de FD
.LP
.KS
.TA .5i 3i
.ta .5i 3i
.nf
..
.de FN
.fi
.KE
.LP
..
.de IN		\" send an index entry to the stderr
.tm \\n%:\\$1:\\$2:\\$3
..
.de C{
.KS
.nf
.D
.\"
.\"	choose appropriate monospace font
.\"	the imagen conditional, 480,
.\"	may be changed to L if LB is too
.\"	heavy for your eyes...
.\"
.ie "\\*(.T"480" .ft L
.el .ie "\\*(.T"300" .ft L
.el .ie "\\*(.T"202" .ft PO
.el .ie "\\*(.T"aps" .ft CW
.el .ft R
.ps \\n(PS
.ie \\n(VS>40 .vs \\n(VSu
.el .vs \\n(VSp
..
.de C}
.DE
.R
..
.de Pn
.ie t \\$1\fB\^\\$2\^\fR\\$3
.el \\$1\fI\^\\$2\^\fP\\$3
..
.de PN
.ie t \fB\^\\$1\^\fR\\$2
.el \fI\^\\$1\^\fP\\$2
..
.de NT
.ne 7
.ds NO Note
.if \\n(.$>$1 .if !'\\$2'C' .ds NO \\$2
.if \\n(.$ .if !'\\$1'C' .ds NO \\$1
.ie n .sp
.el .sp 10p
.TB
.ce
\\*(NO
.ie n .sp
.el .sp 5p
.if '\\$1'C' .ce 99
.if '\\$2'C' .ce 99
.in +5n
.ll -5n
.R
..
.		\" Note End -- doug kraft 3/85
.de NE
.ce 0
.in -5n
.ll +5n
.ie n .sp
.el .sp 10p
..
.ny0
.TH libAF 3 "Release 1" "AF Version 3" 
.SH NAME
\fBlibAF.a\fR \- Core AF Library
.SH Header Files
\fB#include <AF/AFlib.h>\fP
.SH Connection Management
.LP
AFAudioConn \fB*AFOpenAudioConn\fP (char \fI*server\fP)
.LP
void \fBAFCloseAudioConn\fP (AFAudioConn \fI*aud\fP)
.LP
int (*\fBAFSynchronize\fP) (AFAudioConn \fI*aud\fP, int \fIonoff))(\fP)
.LP
int (*\fBAFSetAfterFunction\fP) (AFAudioConn \fI*aud\fP, int \fI(*func)()))(\fP)
.SH Audio Handling
.LP
ATime \fBAFGetTime\fP (AC \fIac\fP)
.LP
ATime \fBAFPlaySamples\fP (AC \fIac\fP, ATime \fIstartTime\fP, 
.br
                                        int \fInbytes\fP, unsigned char \fI*buf\fP)
.LP
ATime \fBAFRecordSamples\fP (AC \fIac\fP, ATime \fIstartTime\fP, int \fInbytes\fP, 
.br
                                        unsigned char \fI*buf\fP, ABool \fIblock\fP)
.SH Audio Contexts
.LP
AC \fBAFCreateAC\fP (AFAudioConn \fI*aud\fP, ADevice \fIdevice\fP, unsigned long \fIvaluemask\fP, 
.br
                                        AFSetACAttributes \fI*attributes\fP)
.LP
void \fBAFChangeACAttributes\fP (AC \fIac\fP, unsigned long \fIvaluemask\fP, 
.br
                                        AFSetACAttributes \fI*attributes\fP)
.LP
void \fBAFFreeAC\fP (AC \fIac\fP)
.SH Event Handling
.LP
int \fBAFEventsQueued\fP (AFAudioConn \fI*aud\fP, int \fImode\fP)
.LP
int \fBAFPending\fP (AFAudioConn \fI*aud\fP)
.LP
void \fBAFIfEvent\fP (AFAudioConn \fI*aud\fP, AFEvent \fI*event_return\fP, 
.br
                                        ABool (*\fIpredicate\fP)(), char \fB*arg\fP)
.LP
ABool \fBAFCheckIfEvent\fP (AFAudioConn \fI*aud\fP, AFEvent \fI*event_return\fP,
.br
                                        ABool (*\fIpredicate\fP), char \fI*arg\fP)
.LP
void \fBAFPeekIfEvent\fP (AFAudioConn \fB*aud,\fP AFEvent \fI*event_return\fP,
.br
                                        ABool \fI(*predicate)()\fP, char \fB*arg)\fP
.LP
void \fBAFNextEvent\fP (AFAudioConn \fI*aud\fP, AFEvent \fI*event\fP)
.LP
void \fBAFSelectEvents\fP (AC \fIac\fP, long \fImask\fP)
.SH Telephone
.LP
AC \fBAFCreatePhoneAC\fP (AFAudioConn \fI*aud\fP, unsigned long \fIvaluemask\fP, 
.br
                                        AFSetACAttributes \fI*attributes\fP)
.LP
int \fBAFDialPhone\fP (AC \fIac\fP, char \fI*dialstring\fP)
.LP
void \fBAFHookSwitch\fP (AC \fIac\fP, int \fIonoff\fP)
.LP
void \fBAFFlashHook\fP (AC \fIac\fP, int \fIduration\fP)
.LP
void \fBAFQueryPhone\fP (AC \fIac\fP, int \fI*hs_state\fP, int \fI*loop_state\fP)
.SH I/O Control
.LP
void \fBAFEnableInput\fP (AC \fIac\fP, AMask \fImask\fP, AMask \fI*old_state\fP, AMask \fI*new_state\fP)
.LP
void \fBAFDisableInput\fP (AC \fIac\fP, AMask \fImask\fP, AMask \fI*old_state\fP, AMask \fI*new_state\fP)
.LP
void \fBAFEnableOutput\fP (AC \fIac\fP, AMask \fImask\fP, AMask \fI*old_state\fP, AMask \fI*new_state\fP)
.LP
void \fBAFDisableOutput\fP ( AC \fIac\fP, AMask \fImask\fP, AMask \fI*old_state\fP, 
.br
                                        AMask \fI*new_state\fP)
.LP
void \fBAFEnablePassThrough\fP (AC \fIac\fP, ABool \fIchange\fP, ABool \fI*old_state\fP, 
.br
                                        ABool \fI*new_state\fP)
.LP
void \fBAFDisablePassThrough\fP (AC \fIac\fP, ABool \fIchange\fP, ABool \fI*old_state\fP, 
.br
                                        ABool \fI*new_state\fP)
.LP
int \fBAFQueryInputGain\fP ( AC \fIac\fP, int \fI*min_input_gain\fP, int \fI*max_input_gain\fP)
.LP
int \fBAFQueryOutputGain\fP ( AC \fIac\fP, int \fI*min_output_gain\fP, int \fI*max_output_gain\fP)
.LP
void \fBAFSetInputGain\fP ( AC \fIac\fP, int \fIgain\fP)
.LP
void \fBAFSetOutputGain\fP ( AC \fIac\fP, int \fIgain\fP)
.SH Access Control
.LP
void \fBAFAddHost\fP(AFAudioConn \fI*aud\fP, AFHostAddress \fI*host\fP)
.LP
void \fBAFAddHosts\fP(AFAudioConn \fI*aud\fP, AFHostAddress \fI*hosts\fP, int \fIn\fP)
.LP
AFHostAddress *\fBAFListHosts\fP(AFAudioConn \fI*aud\fP, int \fI*nhosts_ret\fP, 
.br
                                        ABool \fI*enabled_ret\fP)
.LP
void \fBAFRemoveHost\fP(AFAudioConn \fI*aud\fP, AFHostAddress \fI*host\fP)
.LP
void \fBAFRemoveHosts\fP(AFAudioConn \fI*aud\fP, AFHostAddress \fI*hosts\fP, int \fIn\fP)
.LP
void \fBAFSetAccessControl\fP(AFAudioConn \fI*aud\fP, int \fImode\fP)
.LP
void \fBAFEnableAccessControl\fP(AFAudioConn \fI*aud\fP)
.LP
void \fBAFDisableAccessControl\fP(AFAudioConn \fI*aud\fP)
.SH Properties
int \fBAFGetProperty\fP\^(AC \fIac\fP, AAtom \fIproperty\fP\^, long \fIlong_offset\fP\^,
.br
                    long \fIlong_length\fP\^, ABool \fIdelete\fP\^, AAtom \fIreq_type\fP\^,
.br
                    AAtom \fI*actual_type_return\fP\^, int \fI*actual_format_return\fP\^,
.br
                    unsigned long \fI*nitems_return\fP\^,
.br
                    unsigned long \fI*bytes_after_return\fP\^,
.br
                    unsigned char \fI**prop_return\fP\^)
.LP
AAtom *\fBAFListProperties\fP\^(\^AC \fIac\fP, int \fI*num_prop_return\fP\^)
.LP
\fBAFChangeProperty\fP\^(\^AC \fIac\fP, AAtom \fIproperty\fP\^, AAtom \fItype\fP\^, int \fIformat\fP\^,
.br
                    int \fImode\fP\^, unsigned char \fI*data\fP\^, int \fInelements\fP\^)
.LP
\fBAFDeleteProperty\fP\^(\^AC \fIac\fP, AAtom \fIproperty\fP\^)
.LP
AAtom \fBAFInternAtom\fP(AFAudioConn \fI*aud\fP, char \fI*atom_name\fP, ABool \fIonly_if_exists\fP)
.LP
char *\fBAFGetAtomName\fP(AFAudioConn \fI*aud\fP, AAtom \fIatom\fP)
.SH Error Handling
.LP
int (*\fBAFSetErrorHandler\fP) \fI((*handler)(AFAudioConn *aud, 
.br
                                        AFErrorEvent *event))(\fP)
.LP
int (*\fBAFSetIOErrorHandler\fP) \fI((*handler)(AFAudioConn *aud))(\fP)
.LP
void \fBAFGetErrorText\fP (AFAudioConn \fI*aud\fP, int \fIcode\fP, char \fI*buffer\fP, int \fInbytes\fP)
.LP
void \fBAFGetErrorDatabaseText\fP (AFAudioConn \fI*aud\fP, char \fI*name\fP, char \fI*type\fP, 
.br
                                        char \fI*defaultp\fP, char \fI*buffer\fP, 
.br
                                        int \fInbytes\fP)
.SH Miscellaneous
.LP
char *\fBAFAudioConnName\fP (char \fI*conn\fP)
.LP
void \fBAFFlush\fP(AFAudioConn \fI*aud\fP)
.LP
void \fBAFSync\fP(AFAudioConn \fI*aud\fP, ABool \fIdiscard\fP)
.LP
void \fBAFNoOp\fP(AFAudioConn \fI*aud\fP)
.LP
\fBAFDeviceDescriptor\fP *\fIAAudioDeviceDescriptor\fP (AFAudioConn * \fIaud\fP, 
.br
                                        int \fIdev_index\fP)
.LP
\fBAFree\fP\^(\^\fIdata\fP\^)
.br
     void *\fIdata\fP\^; 
.SH "SEE ALSO"
libAFUtil(3), AF(1)
.br
AFOpenAudioConn(3), AFCloseAudioConn(3), AFSynchronize(3)
.br
AFSetAfterFunction(3), AFGetTime(3), AFPlaySamples(3)
.br
AFRecordSamples(3), AFCreateAC(3), AFChangeACAttributes(3)
.br
AFFreeAC(3), AFEventsQueued(3), AFPending(3)
.br
AFIfEvent(3), AFCheckIfEvent(3), AFPeekIfEvent(3)
.br
AFNextEvent(3), AFSelectEvents(3), AFCreatePhoneAC(3)
.br
AFDialPhone(3), AFHookSwitch(3), AFFlashHook(3)
.br
AFQueryPhone(3), AFEnableInput(3), AFDisableInput(3)
.br
AFEnableOutput(3), AFDisableOutput(3), AFEnablePassThrough(3)
.br
AFDisablePassThrough(3), AFQueryInputGain(3), AFQueryOutputGain(3)
.br
AFSetInputGain(3), AFSetOutputGain(3), AFAddHost(3)
.br
AFAddHosts(3), AFListHosts(3), AFRemoveHost(3)
.br
AFRemoveHosts(3), AFSetAccessControl(3), AFEnableAccessControl(3)
.br
AFDisableAccessControl(3), AFGetProperty(3), AFListProperties(3)
.br
AFChangeProperty(3), AFDeleteProperty(3), AFInternAtom(3)
.br
AFGetAtomName(3), AFSetErrorHandler(3), AFSetIOErrorHandler(3)
.br
AFGetErrorText(3), AFGetErrorDatabaseText(3), AFAudioConnName(3)
.br
AFFlush(3), AFSync(3), AFNoOp(3)
.br
AAudioDeviceDescriptor(3), AFree(3)
.SH BUGS
If you encounter a \fBreproducible\fP bug, please 
submit a problem report to (af-bugs@crl.dec.com).
.SH COPYRIGHT
Copyright 1990-1994, Digital Equipment Corporation.
.br
See \fIAF(1)\fP for a full statement of rights and permissions.
.SH AUTHORS
Digital Cambridge Research Lab
